//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
AWater.AOcean.Materials.Ocean.splashMaterial = {
  uniforms: {
    //Vertex stage
    uViewportHeight: {value: 1080.0},
    uMaxPointSize: {value: 512.0},
    uSizeScale: {value: 5.0},
    uWind: {value: new THREE.Vector2(0.0, 0.0)},
    sunColor: {value: new THREE.Color(1.0, 1.0, 1.0)},
    skyAmbientColor: {value: new THREE.Color(0.3, 0.4, 0.5)},
    uSunScale: {value: 0.8},
    uAmbientScale: {value: 1.0},
    sunDir: {value: new THREE.Vector3(0.0, 1.0, 0.0)},
    uPhaseG: {value: 0.85},
    uPhaseGain: {value: 0.6},
    sunShadowMatrix: {value: new THREE.Matrix4()},
    sunShadowMap: {value: null},
    sunShadowMapSize: {value: new THREE.Vector2(2048.0, 2048.0)},
    sunShadowRadius: {value: 1.0},
    sunShadowBias: {value: 0.0},
    sunShadowEnabled: {value: 0},

    //Fragment stage
    splashSprite: {value: null},
    uLinearDepth: {value: null},
    uResolution: {value: new THREE.Vector2(1920.0, 1080.0)},
    uSoftRange: {value: 1.5},
    uOpacity: {value: 0.55},
    uDebugMode: {value: 0},
    uNoiseScale: {value: 2.5},
    uErode: {value: 0.35},
    uSoftEdge: {value: 0.25},
    uNoiseEvolve: {value: 0.6},
    uOpacityCoarse: {value: 0.95},
    uErodeCoarse: {value: 0.06},
    uSparkle: {value: 1.2},
    uDropletCells: {value: 6.0},
    uDropletRadius: {value: 1.0},
    uDropletSpread: {value: 3.0},
    uAbsorb: {value: 1.2},
    meteringSurveyTexture: {value: null},
    uHasSkyTex: {value: 0},
    uTime: {value: 0.0},
    uWobbleFreq: {value: 8.0},
    uWobbleAmp: {value: 0.18},
    uHarmonic: {value: 0.14},
    uSizeFalloff: {value: 5.0},
    uSkyBoost: {value: 3.0},
    uWindNoiseSpeed: {value: 0.4},
  },

  fragmentShader: [
    'precision highp float;',

    '//Ocean splash particle fragment stage (THREE.Points, GLSL1).',
    '//',
    '//Each point is a camera-facing sprite quad (gl_PointCoord spans 0..1). We',
    '//composite a supplied spray sprite, fade it in/out over the particle lifetime,',
    '//and soft-fade it against scene geometry using the refraction G-buffer linear',
    '//depth so droplets sink into terrain and hulls instead of hard-clipping.',

    'uniform sampler2D splashSprite;   //retained for compatibility, now unused (shape is procedural)',
    'uniform sampler2D uLinearDepth;   //G-buffer attachment 2: positive view-Z, a=hasGeom',
    'uniform vec2 uResolution;         //G-buffer / drawing-buffer size in pixels',
    'uniform float uSoftRange;         //metres over which we soft-fade into geometry',
    'uniform float uOpacity;           //global artistic opacity (FUDGE)',
    'uniform int uDebugMode;           //0 = normal, 1 = tint by emitter type',
    'uniform float uNoiseScale;        //3D noise frequency across the droplet',
    'uniform float uErode;             //silhouette erosion threshold (higher = grainier)',
    'uniform float uSoftEdge;          //erosion smoothstep width (lower = sharper, sparklier)',
    'uniform float uNoiseEvolve;       //noise dissolve rate over the particle life',
    'uniform float uOpacityCoarse;     //peak opacity at coarse=1 (droplets are dense/bright)',
    'uniform float uErodeCoarse;       //erosion threshold at coarse=1 (near 0 = coherent blob)',
    'uniform float uSparkle;           //sun-specular strength on the SDF water beads',
    'uniform float uDropletCells;      //droplet cluster: grid cells across the billboard',
    'uniform float uDropletRadius;     //droplet cluster: individual drop size scale',
    'uniform float uDropletSpread;     //droplet cluster: gaussian tightness (higher = tighter)',
    'uniform float uAbsorb;            //droplet body absorption (water tint, not soap bubble)',
    'uniform sampler2D meteringSurveyTexture; //a-starry-sky fisheye sky (worldXZ->UV) for rim reflection',
    'uniform int uHasSkyTex;           //1 = meteringSurveyTexture is bound this frame',
    'uniform float uTime;              //seconds, drives the droplet wobble animation',
    'uniform float uWobbleFreq;        //droplet wobble frequency (rad/s)',
    'uniform float uWobbleAmp;         //droplet aspect-breathe amplitude (jitters the a/b ratio)',
    'uniform float uHarmonic;          //droplet spherical-harmonic surface-wobble amplitude',
    'uniform float uSizeFalloff;       //cluster size distribution exponent (higher = big drops rarer)',
    'uniform float uSkyBoost;          //brightness lift on the drop sky-reflection (rim reads as sky)',
    'uniform float uWindNoiseSpeed;    //rate the haze noise scrolls along the wind (wisps blow past)',

    "//Scene sun shadow receive (same map + params as the water shader's sunShadow*).",
    'uniform sampler2D sunShadowMap;   //THREE directional-light depth shadow map',
    'uniform vec2 sunShadowMapSize;    //shadow map resolution in texels',
    'uniform float sunShadowRadius;    //PCF tap spread (light.shadow.radius)',
    'uniform float sunShadowBias;      //depth bias (light.shadow.bias + console offset)',
    'uniform int sunShadowEnabled;     //0 = no shadow map this frame',

    'varying float vAge01;',
    'varying float vSeed;',
    'varying float vType;',
    'varying float vCoarse;',
    'varying vec3 vToCamW;       //world-space direction from the particle to the camera',
    'varying vec2 vWindDir;      //view-space (billboard-plane) wind direction, drives the noise scroll',
    'varying float vViewZ;',
    'varying vec3 vAmbient;      //smooth sky-ambient term',
    'varying vec3 vSunCol;       //sun colour * scale, wrapped over the synthesized normal',
    'varying float vGlow;        //forward-scatter additive (backlit through-glow)',
    'varying vec3 vSunDirView;   //view-space direction TO the sun',
    'varying vec4 vSunShadowCoord;',

    '//This is a raw ShaderMaterial, so (unlike THREE built-ins) no tonemap or output',
    '//color-space conversion is applied for us. The water surface self-applies the',
    '//same pair, and we blend over its already-sRGB-encoded pixels, so we must match',
    '//or the spray reads too dark on the shadow side and clips harshly on the lit one.',
    'vec3 acesTonemap(vec3 x){',
      'const float a = 2.51; const float b = 0.03;',
      'const float c = 2.43; const float d = 0.59; const float e = 0.14;',
      'return clamp((x * (a * x + b)) / (x * (c * x + d) + e), 0.0, 1.0);',
    '}',
    'vec3 linearToSrgb(vec3 c){ return pow(clamp(c, 0.0, 1.0), vec3(1.0 / 2.2)); }',

    '//Compact 3D value noise (iq-style integer hash + trilinear smoothstep interp). Cheap',
    '//enough to run per-fragment on hundreds of sprites; quality is fine for soft mist.',
    'float hash3(vec3 p){',
      'p = fract(p * 0.3183099 + 0.1);',
      'p *= 17.0;',
      'return fract(p.x * p.y * p.z * (p.x + p.y + p.z));',
    '}',
    'float vnoise3(vec3 x){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'return mix(mix(mix(hash3(i + vec3(0.0, 0.0, 0.0)), hash3(i + vec3(1.0, 0.0, 0.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 0.0)), hash3(i + vec3(1.0, 1.0, 0.0)), f.x), f.y),',
                 'mix(mix(hash3(i + vec3(0.0, 0.0, 1.0)), hash3(i + vec3(1.0, 0.0, 1.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 1.0)), hash3(i + vec3(1.0, 1.0, 1.0)), f.x), f.y), f.z);',
    '}',
    '//Three-octave fractal sum -> billowy cloud-style field in roughly [0,1].',
    'float fbm3(vec3 p){',
      'float a = 0.5;',
      'float s = 0.0;',
      'for(int i = 0; i < 3; i++){',
        's += a * vnoise3(p);',
        'p *= 2.0;',
        'a *= 0.5;',
      '}',
      'return s;',
    '}',

    '//Core water-drop primitive: an oriented, volume-conserving, harmonic-wobbling spheroid at a',
    '//local billboard offset p (centred-quad pc space, y-DOWN), rest radius rad, stretched by `aspect`',
    '//(a/b) along axA, with surface-wobble amplitude wobAmp. The Wolfram aspect-breathe (uWobbleAmp)',
    '//and the spherical-harmonic surface ripple (modes 2-4, bubble_builder style) both ride uTime.',
    '//Writes a VIEW-space normal (y flipped UP, so the sun glint sits on top) plus the camera-ward',
    '//height to outZ; returns soft silhouette coverage. Used by the small-drop cluster.',
    'float wobbleDrop(vec2 p, float rad, vec2 axA, vec2 axP, float aspect, float wobAmp,',
                     'float pseed, out vec3 outN, out float outZ){',
      'outN = vec3(0.0, 0.0, 1.0);',
      'outZ = 0.0;',
      'float breathe = 1.0 + uWobbleAmp * sin(uWobbleFreq * uTime + pseed * 6.2831853);',
      'float A = max(0.35, aspect * breathe);',
      'float a = rad * pow(A, 0.6666667);                //long semi-axis along axA (a*b^2 = rad^3)',
      'float b = rad * pow(A, -0.3333333);               //short semi-axes (perpendicular + to camera)',
      'float al = dot(p, axA);',
      'float pe = dot(p, axP);',
      'float u = al / a;',
      'float v = pe / b;',
      'float rho = sqrt(u * u + v * v);                  //1 at the unperturbed edge',
      'float theta = atan(v, u);',
      'float W = 0.0;',
      'float dW = 0.0;',
      'for(int k = 0; k < 3; k++){',
        'float m = float(k) + 2.0;                       //modes 2, 3, 4',
        'float ph = uWobbleFreq * uTime * (0.7 + 0.3 * float(k)) + pseed * 6.2831853 * (float(k) + 1.0);',
        'float amp = wobAmp * (0.6 / m);                 //taper the higher modes',
        'W  += amp * sin(m * theta + ph);',
        'dW += amp * m * cos(m * theta + ph);',
      '}',
      'float edge = 1.0 + W;                             //wobbly boundary radius',
      'if(rho > edge) return 0.0;',
      'outZ = b * sqrt(max(0.0, edge * edge - rho * rho));',
      '//Surface normal: radial ellipsoid gradient tilted tangentially by the harmonic slope. Flip y:',
      '//p is y-DOWN gl_PointCoord space, lighting wants a y-UP view normal (glint on top, not bottom).',
      'vec2 tang = vec2(-sin(theta), cos(theta));',
      'vec2 nUV = vec2(u, v) - tang * dW;',
      'vec2 nxy = axA * (nUV.x / a) + axP * (nUV.y / b);',
      'outN = normalize(vec3(nxy.x, -nxy.y, outZ / (b * b)));',
      'return smoothstep(1.0, 0.8, rho / edge);          //soft wobbly silhouette',
    '}',

    '//Cluster of small SDF water droplets inside one billboard. Tiles the sprite into a grid; each',
    '//cell may host one wobbling drop, gaussian-culled toward the centre so the whole reads as a soft',
    '//puff of finite drops. Each drop now wobbles (less for the smaller ones — surface tension holds',
    '//them rigid). Writes the hit droplet view-space normal to outN; returns soft coverage.',
    'float dropletCluster(vec2 uv, float seed, out vec3 outN){',
      'outN = vec3(0.0, 0.0, 1.0);',
      'vec2 g = uv * uDropletCells;',
      'vec2 cell = floor(g);',
      'float r0 = hash3(vec3(cell, seed));',
      'float r1 = hash3(vec3(cell.yx, seed + 9.0));',
      '//Gaussian presence: cells near the billboard centre almost always carry a drop; outer',
      '//cells are progressively culled, so the cluster tapers to a soft round puff of drops.',
      'vec2 cc = (cell + 0.5) / uDropletCells - 0.5;     //cell centre in [-0.5, 0.5]',
      'float gauss = exp(-dot(cc, cc) * 4.0 * uDropletSpread);',
      'if(r0 > gauss) return 0.0;',
      'vec2 jit = (vec2(r0, r1) - 0.5) * 0.35;           //keep the drop inside its cell',
      '//Exponential size falloff: raising r1 to uSizeFalloff makes MOST drops tiny and large ones',
      '//increasingly rare (the bubble-breakup distribution). Higher uSizeFalloff = fewer big drops.',
      'float radMin = 0.04;',
      'float radMax = 0.20;',
      'float rad = mix(radMin, radMax, pow(r1, uSizeFalloff)) * uDropletRadius;   //cell-local units',
      '//Map the cell-local drop into the centred billboard (pc, -1..1) frame for wobbleDrop.',
      'vec2 centerPc = ((cell + 0.5 + jit) / uDropletCells) * 2.0 - 1.0;',
      'vec2 pc = uv * 2.0 - 1.0;',
      'float radPc = rad * 2.0 / uDropletCells;',
      '//Smaller drops wobble LESS (surface tension holds them spherical); larger members jiggle more.',
      'float wobAmp = uHarmonic * clamp(rad / (radMax * uDropletRadius), 0.2, 1.0);',
      'float pseed = seed + cell.x * 1.7 + cell.y * 3.1;',
      'float zc;',
      'return wobbleDrop(pc - centerPc, radPc, vec2(1.0, 0.0), vec2(0.0, 1.0), 1.0, wobAmp, pseed, outN, zc);',
    '}',

    '//Sky reflection colour for a view-space drop normal. The water surface reflects the sky via the',
    '//atmospheric LUT (computeSkyRadiance), which the splash shader does not have; the metering-survey',
    '//fisheye it CAN reach is dim/low-res, so a drop sampling it alone read as a dark-rimmed bubble.',
    '//Instead we synthesize a reliable BRIGHT sky: a vertical gradient anchored to the scene ambient',
    '//(so it tracks time of day) and lifted by uSkyBoost so the Fresnel rim reads as real reflected',
    '//sky, then blend in the fisheye for directional detail when it is actually bound.',
    'vec3 skyReflect(vec3 viewN){',
      'vec3 worldN = normalize(viewN * mat3(viewMatrix));   //view->world (orthonormal transpose)',
      'vec3 reflectDir = reflect(-normalize(vToCamW), worldN);',
      'float up = clamp(reflectDir.y * 0.5 + 0.5, 0.0, 1.0); //horizon (0) .. zenith (1)',
      'vec3 sky = vAmbient * uSkyBoost * mix(0.8, 1.6, up);  //brighter, bluer toward the zenith',
      'if(uHasSkyTex == 1){',
        'vec2 skyUV = clamp(reflectDir.xz * 0.5 + 0.5, 0.01, 0.99);',
        'sky = mix(sky, texture2D(meteringSurveyTexture, skyUV).rgb * uSkyBoost, 0.4);',
      '}',
      'return sky;',
    '}',

    '//Scene sun shadow: 3x3 PCF on the directional-light depth map. A derivative-free',
    '//cut of the water shader getSunShadow (no dFdx slope bias) so it stays GLSL1-safe;',
    '//soft spray does not need acne suppression. Returns 1 = lit, 0 = fully shadowed.',
    'float getSplashSunShadow(){',
      'if(sunShadowEnabled == 0) return 1.0;',
      'vec3 sc = vSunShadowCoord.xyz / vSunShadowCoord.w;',
      'if(sc.z > 1.0 || sc.z < 0.0) return 1.0;',
      'vec2 edgeDist = min(sc.xy, vec2(1.0) - sc.xy);',
      'float edge = min(edgeDist.x, edgeDist.y);',
      'if(edge < 0.0) return 1.0;',
      'float refZ = sc.z + sunShadowBias;',
      'vec2 texelSize = (1.0 / sunShadowMapSize) * sunShadowRadius;',
      'float shadow = 0.0;',
      'for(int x = -1; x <= 1; x++){',
        'for(int y = -1; y <= 1; y++){',
          'float d = texture2D(sunShadowMap, sc.xy + vec2(float(x), float(y)) * texelSize).r;',
          'shadow += refZ < d ? 1.0 : 0.0;',
        '}',
      '}',
      'shadow *= (1.0 / 9.0);',
      '//Fade toward lit over the outer 5% of the frustum so the boundary is not a hard line.',
      'float fade = smoothstep(0.0, 0.05, edge);',
      'return mix(1.0, shadow, fade);',
    '}',

    'void main(){',
      '//Procedural mist droplet: a soft sphere whose silhouette is eroded by 3D noise so',
      '//each billboard reads as a rough-edged, cloud-like puff rather than a flat disc.',
      'vec2 pc = (gl_PointCoord - 0.5) * 2.0;   //-1..1 across the quad',
      'float r = length(pc);                    //0 at centre .. ~1.41 at the corner',
      '//Reconstruct a hemisphere height so the noise wraps over a 3D surface (a fake',
      '//volume cue) instead of lying flat on the disc.',
      'float z = sqrt(max(0.0, 1.0 - r * r));',
      'vec3 spherePos = vec3(pc, z);',
      '//Per-particle offset (vSeed) makes every billboard unique; advancing along Z by vAge01 evolves',
      '//the field so the puff dissolves as it ages. On TOP of that, scroll the noise across the',
      '//billboard along the wind direction (vWindDir, view-space) over uTime, so the wisps appear to',
      '//stream with the wind rather than sit static — the breeze blowing through the spray.',
      'vec2 windScroll = vWindDir * (uTime * uWindNoiseSpeed);',
      'vec3 nCoord = spherePos * uNoiseScale',
                  '+ vec3(vSeed * 51.3 + windScroll.x, vSeed * 17.7 + windScroll.y, vAge01 * uNoiseEvolve);',
      'float n = fbm3(nCoord);                  //~0..1',
      '//Sharp mist->bead transition (matches the vertex size taper) so there is no big glassy',
      '//boulder middle: it drives the haze->bead blend below as well as the size in the vertex.',
      'float beadMix = smoothstep(0.4, 0.65, vCoarse);',
      '//── HAZE branch (mist end): the soft noise-eroded puff. corePow/erode track coarseness',
      '//   but this branch is mixed OUT toward the droplet end, so it mainly shapes the mist.',
      'float corePow = mix(2.0, 4.0, vCoarse);',
      'float erode = mix(uErode, uErodeCoarse, vCoarse);',
      'float core = pow(clamp(1.0 - r, 0.0, 1.0), corePow);',
      'float carve = smoothstep(erode, erode + uSoftEdge, n);',
      'float hazeDensity = core * carve;',

      '//── Shared sun half-vector and scene sun shadow (both droplet tiers + the haze use them).',
      'vec3 Hh = normalize(vSunDirView + vec3(0.0, 0.0, 1.0));//half-vector to the sun',
      'float sunShadow = getSplashSunShadow();',

      '//── DROPLET appearance: coarse particles render as a gaussian CLUSTER of many small water beads',
      '//   (clear bodies that transmit the background, a sky-Fresnel rim + a tight sun glint each, alpha',
      '//   near-zero in the clear centre). Skipped for pure mist (beadMix ~ 0), where it would only be',
      '//   mixed out below anyway. beadMix is per-billboard constant, so the branch is GPU-coherent.',
      'float dropDensity = 0.0;',
      'vec3 dropLit = vec3(0.0);',
      'if(beadMix > 0.001){',
        'vec3 dN;',
        'float cov = dropletCluster(gl_PointCoord, vSeed, dN);',
        '//Water drop, NOT a soap bubble: a clear body that transmits the background (alpha near zero in',
        '//the centre), opaque only where it REFLECTS — a bright Fresnel rim reflecting the sky and a',
        '//crisp sun sparkle. The rim is the lead read; the body is a dim cool water tint, not a glow.',
        'float fres = pow(1.0 - clamp(dN.z, 0.0, 1.0), 3.0);          //sharper grazing-angle rim',
        'float dGlint = pow(max(0.0, dot(dN, Hh)), 80.0) * uSparkle * sunShadow; //crisp wet sun sparkle',
        'vec3 sky = skyReflect(dN);                                   //bright reflected sky on the rim',
        '//Light absorption tints the rim toward water (deeper at grazing where rays cross more water),',
        '//but gently so it does not darken the reflection back into a bubble.',
        'vec3 absorb = pow(vec3(0.86, 0.93, 0.98), vec3(uAbsorb * (1.0 - dN.z)));',
        'dropLit = sky * fres * 1.6 * absorb                          //sky reflection (the bright rim)',
                '+ vAmbient * vec3(0.55, 0.72, 0.9) * 0.14            //dim cool water body (transmits)',
                '+ vSunCol * (dGlint + vGlow * 0.25);                 //wet sparkle + a little backlit glow',
        'float dAlpha = clamp(fres * 0.7 + dGlint + 0.05, 0.0, 1.0);',
        'dropDensity = cov * dAlpha;',
      '}',

      '//── Blend mist <-> droplet by coarseness: mist shows haze, a coarse particle is a drop.',
      'float density = mix(hazeDensity, dropDensity, beadMix);',

      '//Lifetime fade: a quick rise then a long ease-out, like real spray thinning.',
      'float fadeIn = smoothstep(0.0, 0.15, vAge01);',
      'float fadeOut = 1.0 - smoothstep(0.55, 1.0, vAge01);',
      'float ageAlpha = fadeIn * fadeOut;',

      '//Soft-particle fade. Sample scene depth under this fragment. .a marks where solid',
      '//geometry was written; over open water / sky it is 0 and we must NOT fade (otherwise',
      '//spray over the open sea vanishes against the cleared buffer).',
      'vec2 screenUV = gl_FragCoord.xy / uResolution;',
      'vec4 depthSample = texture2D(uLinearDepth, screenUV);',
      'float sceneZ = depthSample.r;',
      'float hasGeom = depthSample.a;',
      'float softFade = 1.0;',
      'if(hasGeom > 0.5){',
        'softFade = clamp((sceneZ - vViewZ) / max(0.001, uSoftRange), 0.0, 1.0);',
      '}',

      '//Droplets are denser and brighter than haze, so peak opacity climbs toward the drop end.',
      'float op = mix(uOpacity, uOpacityCoarse, beadMix);',
      'float alpha = density * ageAlpha * softFade * op;',

      '//HAZE lighting: half-Lambert wrap of the sun over a synthesized spherical normal so the',
      '//mist reads as a 3D billow (sun side bright, far side to sky-ambient). The +0.3 z-bias',
      '//keeps rim normals off a harsh black terminator; vGlow is added ungated so a backlit puff',
      '//still blooms. Scene sun shadow gates the direct terms.',
      'vec3 N = normalize(vec3(pc.x, -pc.y, z + 0.3));  //negate y: gl_PointCoord is y-down',
      'float wrap = clamp(dot(N, vSunDirView) * 0.5 + 0.5, 0.0, 1.0);',
      'vec3 hazeLit = vAmbient + vSunCol * (wrap + vGlow) * sunShadow;',

      'vec3 lit = mix(hazeLit, dropLit, beadMix);',
      'vec3 color = linearToSrgb(acesTonemap(lit));',

      'if(uDebugMode == 1){',
        '//Crest mist = red, impact burst = magenta; procedural density kept as the alpha.',
        'vec3 tint = mix(vec3(1.0, 0.1, 0.1), vec3(1.0, 0.2, 0.8), step(0.5, vType));',
        'color = tint;',
        'alpha = density * ageAlpha;',
      '} else if(uDebugMode == 2){',
        '//Coarseness ramp: deep blue = fine mist, white = coarse droplet. Lets the emission',
        '//bands (crest/impact Coarse Min/Max) be eyeballed directly on screen while tuning.',
        'color = mix(vec3(0.1, 0.2, 0.9), vec3(1.0, 1.0, 1.0), vCoarse);',
        'alpha = density * ageAlpha;',
      '}',

      'if(alpha < 0.01) discard;',
      'gl_FragColor = vec4(color, alpha);',
    '}',
  ].join('\n'),

  vertexShader: [
    'precision highp float;',

    '//Ocean splash particle vertex stage (THREE.Points, GLSL1).',
    '//',
    '//The Points mesh lives at the world origin with an identity model matrix, so',
    '//the per-particle `position` attribute already holds a WORLD-space point and',
    '//modelViewMatrix collapses to the plain view matrix. CPU sim writes position,',
    '//age and size every frame; spawn-time constants (seed, type) ride along in',
    '//their own attributes and are only refreshed when a slot is recycled.',

    'attribute float aSize;     //world-space radius of this droplet (metres)',
    'attribute float aAge01;    //age / lifetime, 0 at birth .. 1 at death',
    'attribute float aSeed;     //per-particle random in [0,1] for shader variety',
    'attribute float aType;     //0 = open-water crest mist, 1 = impact burst',
    'attribute float aCoarse;   //0 = fine hanging mist .. 1 = coherent falling droplet',

    'uniform float uViewportHeight; //renderer drawing-buffer height in pixels',
    'uniform float uMaxPointSize;   //hardware-safe clamp for gl_PointSize',
    'uniform float uSizeScale;      //size multiplier for the mist puff + the small-drop cluster',
    'uniform vec2 uWind;            //world-space wind (x, z); projected into the billboard plane below',

    '//Lighting is per-particle (vertex) rather than per-fragment: spray is a bright',
    '//omnidirectional scatterer with no meaningful surface normal, so a single',
    '//ambient + sun term is both cheaper and visually sufficient.',
    'uniform vec3 sunColor;         //brightest directional light colour * intensity',
    'uniform vec3 skyAmbientColor;  //a-starry-sky y-hemisphere ambient',
    'uniform float uSunScale;       //artistic sun contribution (FUDGE)',
    'uniform float uAmbientScale;   //artistic ambient contribution (FUDGE)',

    '//Forward-scatter (Mie) phase. Spray droplets scatter overwhelmingly forward, so the',
    '//mist blooms when you look THROUGH it toward the sun. uSunDir is the world-space',
    '//direction TO the sun; uPhaseG is the forward-lobe tightness; uPhaseGain dials how',
    '//strongly the halo brightens the sun term.',
    'uniform vec3 sunDir;           //world-space direction TO the sun (normalised)',
    'uniform float uPhaseG;         //forward lobe asymmetry g in [0,1)',
    'uniform float uPhaseGain;      //forward-scatter halo strength (FUDGE)',

    '//Scene sun shadow receive. Same matrix the water shader uses (THREE directional',
    '//light shadow.matrix): maps world -> shadow-map UV+depth. position is already',
    '//world-space (identity model), so this matches the water surface exactly.',
    'uniform mat4 sunShadowMatrix;',

    'varying float vAge01;',
    'varying float vSeed;',
    'varying float vType;',
    'varying float vCoarse;         //fine-mist..droplet grade, drives the fragment look',
    'varying float vViewZ;          //positive view-space depth, matches G-buffer',
    'varying vec3 vAmbient;         //smooth sky-ambient term (unshadowed)',
    'varying vec3 vSunCol;          //sun colour * scale; the fragment wraps it over a normal',
    'varying float vGlow;           //forward-scatter additive (backlit through-glow)',
    'varying vec3 vSunDirView;      //view-space direction TO the sun, for the wrap normal',
    'varying vec4 vSunShadowCoord;  //world position in scene-sun shadow space',
    'varying vec3 vToCamW;          //world-space direction from the particle to the camera',
    'varying vec2 vWindDir;         //view-space (billboard-plane) wind direction for the noise scroll',

    '//Henyey-Greenstein single-lobe phase. g>0 biases scattering forward (toward sun).',
    'float hgPhase(float cosT, float g){',
      'float g2 = g * g;',
      'return (1.0 / (4.0 * 3.14159265)) * (1.0 - g2) / pow(max(1e-4, 1.0 + g2 - 2.0 * g * cosT), 1.5);',
    '}',
    '//Dual-lobe blend: a strong forward lobe (gF) plus a weak wide/back lobe. This is the',
    '//practical minimum that reads as spray Mie scattering rather than a flat sprite.',
    'float dualPhase(float cosT, float gF){',
      'const float gB = -0.2;',
      'const float w = 0.15;',
      'return mix(hgPhase(cosT, gF), hgPhase(cosT, gB), w);',
    '}',

    'void main(){',
      'vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);',
      'vViewZ = -mvPosition.z;',

      '//Perspective size attenuation: a droplet of world radius aSize subtends',
      '//(aSize * focalLengthPixels / distance) pixels. projectionMatrix[1][1] is',
      '//the vertical focal length in clip units, so 0.5 * viewportHeight * that',
      '//converts a world radius at unit distance into pixels.',
      'float focalPx = 0.5 * uViewportHeight * projectionMatrix[1][1];',
      '//The mist puff and the small-drop cluster share one billboard size; the cluster needs the',
      '//room for its many tiny drops, so we keep the full uSizeScale multiplier for every particle.',
      'float pointPx = aSize * uSizeScale * focalPx / max(0.001, vViewZ);',
      'gl_PointSize = clamp(pointPx, 1.0, uMaxPointSize);',

      'vAge01 = aAge01;',
      'vSeed = aSeed;',
      'vType = aType;',
      'vCoarse = aCoarse;',

      '//Forward-scatter cosine. position is world-space (identity model matrix), so the',
      '//camera ray travels camera -> particle, i.e. -toCam; it then continues toward the',
      '//sun (sunDir). cosT peaks at +1 when looking through the mist toward the sun.',
      'vec3 toCam = normalize(cameraPosition - position);',
      'vToCamW = toCam;',
      'float cosT = dot(-toCam, sunDir);',
      'float phase = dualPhase(cosT, uPhaseG);',

      '//Split the lighting so the fragment can SHAPE it: a smooth sky-ambient term, a sun',
      '//colour the fragment wraps over a synthesized spherical normal (sun-facing side',
      '//bright, far side -> ambient, so the puff reads as a 3D billow not flat steam), and',
      '//a view-dependent forward-scatter glow added ungated (the backlit bloom, which must',
      '//NOT be multiplied by the wrap or it would cancel the through-light). The ambient',
      '//term stays smooth and unshadowed (the Ghost of Tsushima Mie-vs-ambient split).',
      'vAmbient = skyAmbientColor * uAmbientScale;',
      'vSunCol = sunColor * uSunScale;',
      'vGlow = uPhaseGain * phase;',
      'vSunDirView = normalize((viewMatrix * vec4(sunDir, 0.0)).xyz);',
      'vSunShadowCoord = sunShadowMatrix * vec4(position, 1.0);',
      '//Wind direction in the billboard plane (view space), so the fragment can scroll the haze noise',
      '//along it. World wind is horizontal (uWind.x, 0, uWind.y); y is negated to match gl_PointCoord',
      "//y-down. Normalised to a pure direction — the scroll RATE is the fragment's uWindNoiseSpeed.",
      'vec3 windView = (viewMatrix * vec4(uWind.x, 0.0, uWind.y, 0.0)).xyz;',
      'vWindDir = (length(windView.xy) > 1e-4) ? normalize(vec2(windView.x, -windView.y)) : vec2(0.0, 0.0);',

      'gl_Position = projectionMatrix * mvPosition;',
    '}',
  ].join('\n'),
};
