//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
AWater.AOcean.Materials.Ocean.waterMaterial = {
  uniforms: {
    cascadeDisplacementTextures: {value: [null, null, null, null, null, null]},
    cascadeSlopeTextures: {value: [null, null, null, null, null, null]},
    cascadePatchSizes: {value: [1000.0, 250.0, 64.0, 16.0, 4.0, 1.0]},
    //Per-cascade spatial UV offsets to break visual tiling periodicity.
    //Golden-ratio derived fractions of each cascade's patch size — different per cascade
    //so tile seams never align with each other.
    cascadeSpatialOffsets: {value: [
      new THREE.Vector2(382.0,  618.0),  //C0 1000m: 0.382L, 0.618L
      new THREE.Vector2( 59.0,  154.5),  //C1  250m: 0.236L, 0.618L
      new THREE.Vector2( 54.7,   15.1),  //C2   64m: 0.854L, 0.236L
      new THREE.Vector2(  7.55,  13.7),  //C3   16m: 0.472L, 0.854L
      new THREE.Vector2(  0.36,   1.89), //C4    4m: 0.090L, 0.472L
      new THREE.Vector2(  0.708,  0.09)  //C5    1m: 0.708L, 0.090L
    ]},
    waveHeightMultiplier: {type: 'f', value: 1.0},
    smallNormalMap: {type: 't', value: null},
    largeNormalMap: {type: 't', value: null},
    causticMap: {type: 't', value: null},
    causticIntensityMultiplier: {type: 'f', value: null},
    foamDiffuseMap: {type: 't', value: null},
    foamOpacityMap: {type: 't', value: null},
    foamNormalMap: {type: 't', value: null},
    foamRoughnessMap: {type: 't', value: null},
    foamRenderMap: {type: 't', value: null},
    foamStartLevel: {type: 'f', value: 0.0},
    exclusionMap: {type: 't', value: null},
    smallNormalMapVelocity: {type: 'vec2', value: new THREE.Vector2()},
    largeNormalMapVelocity: {type: 'vec2', value: new THREE.Vector2()},
    reflectionTexture: {type: 't', value: null},
    refractionColorTexture: {type: 't', value: null},
    refractionDepthTexture: {type: 't', value: null},
    screenResolution: {type: 'vec2', value: new THREE.Vector2()},
    cameraNearFar: {type: 'vec2', value: new THREE.Vector2()},
    inverseProjectionMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    inverseViewMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    reflectionViewProjectionMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    ssrViewMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    ssrProjectionMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    meteringSurveyTexture: {type: 't', value: null},
    sizeOfOceanPatch: {type: 'f', value: 1.0},
    ringIndex: {type: 'i', value: 0},
    baseHeightOffset: {type: 'f', value: 0.0},
    fogNear: {type: 'f', value: null},
    fogFar: {type: 'f', value: null},
    fogDensity: {type: 'f', value: null},
    fogColor: {type: 'v3', value: new THREE.Color()},
    t: {type: 'f', value: 0.0},
    brightestDirectionalLight: {type: 'vec3', value: new THREE.Vector3(1.0,1.0,1.0)},
    brightestDirectionalLightDirection: {type: 'vec3', value: new THREE.Vector3(1.0,1.0,1.0)},
    // Ambient directional lights (for water scattering)
    ambientLightCount: {type: 'i', value: 0},
    ambientLightColors: {type: 'vec3', value: [new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0)]},
    ambientLightDirections: {type: 'vec3', value: [new THREE.Vector3(0,1,0), new THREE.Vector3(1,0,0), new THREE.Vector3(0,-1,0), new THREE.Vector3(-1,0,0), new THREE.Vector3(0,0,1), new THREE.Vector3(0,0,-1), new THREE.Vector3(0,1,0), new THREE.Vector3(0,1,0)]},
    skyAmbientColor: {type: 'vec3', value: new THREE.Vector3(0.1, 0.15, 0.2)},
    largeNormalMapStrength: {type: 'f', value: 0.45},
    smallNormalMapStrength: {type: 'f', value: 0.35},
    waterAbsorption: {type: 'vec3', value: new THREE.Vector3(0.06, 0.012, 0.004)},
    waterScattering: {type: 'vec3', value: new THREE.Vector3(0.010, 0.038, 0.040)},
    waterMieG: {type: 'f', value: 0.7},
    // New physically-based scattering parameters
    k1ScatterAmount: {type: 'f', value: 1.5},
    k2ViewDependence: {type: 'f', value: 1.2},
    k3DirectScatter: {type: 'f', value: 0.6},
    k4ParallaxScatter: {type: 'f', value: 0.2},
    waterTurbidity: {type: 'f', value: 1.0},
    fresnelAbsorptionAmount: {type: 'f', value: 1.0},
    linearScatteringHeightOffset: {type: 'f', value: 10.0},
    linearScatteringTotalScatteringWaveHeight: {type: 'f', value: 20.0},
    patchDataSize: {type: 'f', value: 1024.0},
    atmosphereTransmittance: {type: 't', value: null},
    atmosphereMieInscattering: {type: 't', value: null},
    atmosphereRayleighInscattering: {type: 't', value: null},
    atmSunPosition: {type: 'vec3', value: new THREE.Vector3(0.0, 1.0, 0.0)},
    atmMoonPosition: {type: 'vec3', value: new THREE.Vector3(0.0, -1.0, 0.0)},
    atmSunHorizonFade: {type: 'f', value: 1.0},
    atmMoonHorizonFade: {type: 'f', value: 0.0},
    atmScatteringSunIntensity: {type: 'f', value: 1.0},
    atmScatteringMoonIntensity: {type: 'f', value: 0.0},
    atmMoonLightColor: {type: 'vec3', value: new THREE.Vector3(1.0, 1.0, 1.0)},
    atmCameraHeight: {type: 'f', value: 0.0},
    atmDistanceScale: {type: 'f', value: 1.0},
    blueNoiseTexture: {type: 't', value: null},
    blueNoiseTime: {type: 'f', value: 0.0},
    chop: {type: 'f', value: 1.0}
  },

  fragmentShader: function(causticsEnabled, foamEnabled, atmosphericPerspectiveEnabled, atmosphereFunctionsGLSL){
    let originalGLSL = [
    'precision highp float;',

    'varying vec2 vUv;',
    'varying vec2 vWorldXZ;',
    'varying vec3 vPosition;',
    'varying vec3 vDisplacedPosition;',
    'varying vec3 vTangent;',
    'varying vec3 vBitangent;',
    'varying vec3 vInView;',
    'varying mat4 vInstanceMatrix;',
    'varying mat4 vModelMatrix;',
    'varying mat3 vNormalMatrix;',

    '//uniform vec3 cameraDirection;',
    'uniform float sizeOfOceanPatch;',
    'uniform int ringIndex;',
    'uniform float chop;',
    'uniform float largeNormalMapStrength;',
    'uniform float smallNormalMapStrength;',
    'uniform float baseHeightOffset;',
    'uniform sampler2D cascadeDisplacementTextures[6];',
    'uniform sampler2D cascadeSlopeTextures[6];',
    'uniform float cascadePatchSizes[6];',
    'uniform vec2 cascadeSpatialOffsets[6];',
    'uniform float waveHeightMultiplier;',
    'uniform sampler2D smallNormalMap;',
    'uniform sampler2D largeNormalMap;',
    'uniform sampler2D exclusionMap;',
    'uniform sampler2D reflectionTexture;',
    'uniform sampler2D refractionColorTexture;',
    'uniform sampler2D refractionDepthTexture;',
    'uniform vec2 screenResolution;',
    'uniform vec2 cameraNearFar;',
    'uniform mat4 inverseProjectionMatrix;',
    'uniform mat4 inverseViewMatrix;',
    'uniform mat4 reflectionViewProjectionMatrix;',
    'uniform mat4 ssrViewMatrix;',
    'uniform mat4 ssrProjectionMatrix;',
    'uniform sampler2D meteringSurveyTexture;',

    '#if($caustics_enabled)',
      'uniform sampler2D causticMap;',
      'uniform float causticIntensityMultiplier;',
    '#endif',

    '#if($foam_enabled)',
      '//Foam maps',
      'uniform sampler2D foamRenderMap;',
      'uniform sampler2D foamDiffuseMap;',
      'uniform sampler2D foamOpacityMap;',
      'uniform sampler2D foamNormalMap;',
      'uniform sampler2D foamRoughnessMap;',
      'uniform float foamStartLevel;',
    '#endif',

    'uniform vec2 smallNormalMapVelocity;',
    'uniform vec2 largeNormalMapVelocity;',

    'uniform vec3 brightestDirectionalLight;',
    'uniform vec3 brightestDirectionalLightDirection;',
    'uniform vec3 skyAmbientColor;',
    'uniform vec3 waterAbsorption;',
    'uniform vec3 waterScattering;',
    'uniform float waterMieG;',

    '// Ambient directional lights (for scattering contributions)',
    'uniform int ambientLightCount;',
    'uniform vec3 ambientLightColors[8];',
    'uniform vec3 ambientLightDirections[8];',

    '// New physically-based scattering parameters',
    'uniform float k1ScatterAmount;',
    'uniform float k2ViewDependence;',
    'uniform float k3DirectScatter;',
    'uniform float k4ParallaxScatter;',
    'uniform float waterTurbidity;',
    'uniform float fresnelAbsorptionAmount;',

    'uniform float linearScatteringHeightOffset;',
    'uniform float linearScatteringTotalScatteringWaveHeight;',

    'uniform float t;',
    'uniform float patchDataSize;',

    '//Fog variables',
    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_fragment>',
    '#endif',

    '#if($atmospheric_perspective_enabled)',
      'precision highp sampler3D;',
      'uniform sampler2D atmosphereTransmittance;',
      'uniform sampler3D atmosphereMieInscattering;',
      'uniform sampler3D atmosphereRayleighInscattering;',
      'uniform vec3 atmSunPosition;',
      'uniform vec3 atmMoonPosition;',
      'uniform float atmSunHorizonFade;',
      'uniform float atmMoonHorizonFade;',
      'uniform float atmScatteringSunIntensity;',
      'uniform float atmScatteringMoonIntensity;',
      'uniform vec3 atmMoonLightColor;',
      'uniform float atmCameraHeight;',
      'uniform float atmDistanceScale;',

      '//ATMOSPHERE_FUNCTIONS_INJECTION_POINT',
    '#endif',

    'uniform sampler2D blueNoiseTexture;',
    'uniform float blueNoiseTime;',


    "//R0 For Schlick's Approximation",
    '//With n1 = 1.33 and n0 = 1.0',
    'const float r0 = 0.02;',
    'const vec3 inverseGamma = vec3(0.454545454545454545454545);',
    'const vec3 gamma = vec3(2.2);',

    'vec2 vec2Modulo(vec2 inputUV){',
      'return (inputUV - floor(inputUV));',
    '}',

    'float linearizeDepth(float depthSample){',
      'float near = cameraNearFar.x;',
      'float far = cameraNearFar.y;',
      'return near * far / (far - depthSample * (far - near));',
    '}',

    '#if($atmospheric_perspective_enabled)',
      '//Forward declaration — defined later, alongside applyAtmosphericPerspective.',
      'vec3 computeSkyRadiance(vec3 worldDir);',
    '#endif',

    '//Screen-space reflection using the refraction color+depth buffer (already rendered',
    '//from the main camera with water hidden — zero extra render passes).',
    '//Exponential stepping covers nearby geometry detail AND distant sky.',
    '//Sky fallback: LUT-based atmosphere (when enabled) or metering survey fisheye.',
    '//Returns LINEAR radiance — caller must NOT apply sRGBToLinear to the result.',
    '//Geometry hits come from the sRGB refraction buffer and are converted here.',
    'vec3 screenSpaceReflection(vec3 worldPos, vec3 reflectDir){',
      'vec3 viewPos     = (ssrViewMatrix * vec4(worldPos,    1.0)).xyz;',
      'vec3 viewReflect = normalize(mat3(ssrViewMatrix) * reflectDir);',

      '//Sky fallback: use LUT-based sky radiance when atmosphere is enabled for correct horizon',
      '//colors; fall back to metering survey fisheye for the no-atmosphere build path.',
      '#if($atmospheric_perspective_enabled)',
        'vec3 skyColor = computeSkyRadiance(reflectDir);',
      '#else',
        'vec2 skyUV = clamp(reflectDir.xz * 0.5 + 0.5, 0.01, 0.99);',
        'vec3 skyColor = min(texture2D(meteringSurveyTexture, skyUV).rgb, vec3(4.0));',
      '#endif',

      '//Reflected ray pointing behind the camera — skip march, return sky directly.',
      'if(viewReflect.z > 0.0){',
        'return skyColor;',
      '}',

      '//Exponential step: starts at 0.5m, grows 1.3x each step.',
      'float stepLen = 0.5;',
      'vec3 curPos = viewPos;',

      'for(int i = 0; i < 48; i++){',
        'curPos  += viewReflect * stepLen;',
        'stepLen *= 1.3;',

        'vec4 clip = ssrProjectionMatrix * vec4(curPos, 1.0);',
        'if(clip.w <= 0.0) break;',
        'vec2 uv = clip.xy / clip.w * 0.5 + 0.5;',

        '//Ray exited screen — return sky.',
        'if(uv.x < 0.01 || uv.x > 0.99 || uv.y < 0.01 || uv.y > 0.99){',
          'return skyColor;',
        '}',

        'float sceneDepth = linearizeDepth(texture2D(refractionDepthTexture, uv).r);',
        'float rayDepth   = -curPos.z;',

        '//Reject hits in the lower screen half — foreground geometry (trees, terrain)',
        '//reflected at wrong parallax. Only trust hits above the horizon.',
        'if(rayDepth > sceneDepth + 0.5 && uv.y > 0.5){',
          '//Geometry hit — refraction texture is sRGB; convert to linear to match sky path.',
          'vec2  edgeDist = abs(uv * 2.0 - 1.0);',
          'float edgeFade = 1.0 - smoothstep(0.80, 1.0, max(edgeDist.x, edgeDist.y));',
          'vec3  hitColor = sRGBToLinear(vec4(texture2D(refractionColorTexture, uv).rgb, 1.0)).rgb;',
          'return mix(skyColor, hitColor, edgeFade);',
        '}',
      '}',

      '//Max steps without hit — sky.',
      'return skyColor;',
    '}',

    '#if(!$atmospheric_perspective_enabled)',
      '//When atmospheric perspective is enabled, sRGBToLinear is provided by the injected atmosphere functions',
      'vec4 sRGBToLinear( in vec4 value ) {',
      '	return vec4( mix( pow( value.rgb * 0.9478672986 + vec3( 0.0521327014 ), vec3( 2.4 ) ), value.rgb * 0.0773993808, vec3( lessThanEqual( value.rgb, vec3( 0.04045 ) ) ) ), value.a );',
      '}',
    '#endif',

    'vec4 linearTosRGB(vec4 value ) {',
      'return vec4( mix( pow( value.rgb, vec3( 0.41666 ) ) * 1.055 - vec3( 0.055 ), value.rgb * 12.92, vec3( lessThanEqual( value.rgb, vec3( 0.0031308 ) ) ) ), value.a );',
    '}',

    '//From https://blog.selfshadow.com/publications/blending-in-detail/',
    'vec3 combineNormals(vec3 normal1, vec3 normal2){',
      'vec4 n1 = vec4(normal1.xyz, 1.0);',
      'vec4 n2 = vec4(normal2.xyz, 1.0);',
      'n1 = n1.xyzz * vec4(2.0, 2.0, 2.0, -2.0) + vec4(-1.0, -1.0, -1.0, 1.0);',
      'n2 = n2 * 2.0 - vec4(1.0);',
      'vec3 r;',
      'r.x = dot(n1.zxx,  n2.xyz);',
      'r.y = dot(n1.yzy,  n2.xyz);',
      'r.z = dot(n1.xyw, -n2.xyz);',

      'return 0.5 * (normalize(r) + vec3(1.0));',
    '}',

    '//Including this because someone removed this in a future versio of THREE. Why?!',
    'vec3 MyAESFilmicToneMapping(vec3 color) {',
      'return clamp((color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14), 0.0, 1.0);',
    '}',

    '//GGX microfacet normal distribution (D term)',
    '//From Atlas GDC 2019 / Cook-Torrance: cos_theta = dot(N, H), alpha = roughness',
    'float ggxDistribution(float cosTheta, float alpha) {',
      'float a2 = alpha * alpha;',
      'float d = 1.0 + (a2 - 1.0) * cosTheta * cosTheta;',
      'return a2 / (3.14159265 * d * d);',
    '}',

    '//Smith masking-shadowing (G term) — Beckmann rational approximation',
    "//cos_theta is either NdotL or NdotV depending on which term you're computing",
    'float smithMaskingShadowing(float cosTheta, float alpha) {',
      'float a = cosTheta / (alpha * sqrt(max(1.0 - cosTheta * cosTheta, 1e-6)));',
      'float a2 = a * a;',
      'return a < 1.6 ? (1.0 - 1.259 * a + 0.396 * a2) / (3.535 * a + 2.181 * a2) : 0.0;',
    '}',

    '//Henyey-Greenstein phase function for Mie scattering in water',
    '//g = asymmetry parameter (0.85-0.95 for ocean particles, strongly forward-scattering)',
    'float waterMiePhase(float cosTheta, float g){',
      'float g2 = g * g;',
      'float denom = 1.0 + g2 - 2.0 * g * cosTheta;',
      'return (1.0 - g2) / (4.0 * 3.14159265 * denom * sqrt(denom));',
    '}',

    '//Fresnel reflectance at air->water interface (for light entering the water from above)',
    '//Schlick approximation with n_water = 1.33',
    'float fresnelAirToWater(float cosTheta){',
      'float r0 = 0.02;',
      'return r0 + (1.0 - r0) * pow(1.0 - cosTheta, 5.0);',
    '}',

    '// New physically-based scattering terms',
    '// H(x) - Heaviside step function (0 if x < 0, 1 if x >= 0)',
    'float heaviside(float x) {',
      'return x >= 0.0 ? 1.0 : 0.0;',
    '}',

    '// Term 1: k₁ H ⟨ωᵢ · -ωₒ⟩⁴(0.5 - 0.5(ωᵢ · ωₙ))³',
    '// Wave height scattering — H is wave height, backlit + normal modulation',
    'float scatterTerm1(vec3 sunDir, vec3 viewDir, vec3 normal, float waveHeight, float k1) {',
      '// H: wave height drives scattering amount (reference: displacementFoam.y * _HeightModifier)',
      'float H = max(0.0, waveHeight);',

      '// ⟨ωᵢ · -ωₒ⟩⁴: clamped backlit dot raised to 4th power',
      'float backlitDot = max(dot(sunDir, -viewDir), 0.0);',
      'float backlitTerm = backlitDot * backlitDot * backlitDot * backlitDot; // pow 4',

      '// (0.5 - 0.5(ωᵢ · ωₙ))³: sun-normal angle modulation',
      'float sunNormalDot = dot(sunDir, normal);',
      'float normalModulation = pow(0.5 - 0.5 * sunNormalDot, 3.0);',

      'return k1 * H * backlitTerm * normalModulation;',
    '}',

    '// Term 2: k₂(ωₒ · ωₙ)²',
    '// View-dependent scattering from surface orientation',
    '// Bright when normal faces camera, dark at grazing angles',
    'float scatterTerm2(vec3 viewDir, vec3 normal, float k2) {',
      '// Use negative view direction: points FROM camera TO surface',
      '// This makes it positive when normal faces camera',
      'float viewNormalDot = max(dot(-viewDir, normal), 0.0);',
      'return k2 * viewNormalDot * viewNormalDot;',
    '}',

    '// Fresnel denominator: 1/(1 + A(ωᵢ))',
    '// A(ωᵢ) based on absorption at incident angle',
    'float fresnelAbsorption(vec3 sunDir, vec3 normal, float absorptionAmount) {',
      'float sunNormalDot = max(dot(sunDir, normal), 0.0);',
      'float A = absorptionAmount * (1.0 - sunNormalDot);',
      'return 1.0 / (1.0 + A);',
    '}',

    '// Term 3: k₃(ωᵢ · ωₙ)',
    '// Direct sun-normal scattering',
    'float scatterTerm3(vec3 sunDir, vec3 normal, float k3) {',
      'return k3 * max(dot(sunDir, normal), 0.0);',
    '}',

    '// Term 4: k₄ P_f',
    '// P_f = bubble density (foam/turbulence driven)',
    'float scatterTerm4(float bubbleDensity, float k4) {',
      'return k4 * bubbleDensity;',
    '}',

    '// Accumulate ambient light scattering from all directional lights',
    'vec3 ambientLightScattering(vec3 viewDir, vec3 normal, float waveElevation) {',
      'vec3 totalAmbientScatter = vec3(0.0);',

      'for(int i = 0; i < ambientLightCount && i < 8; ++i) {',
        '// Simple ambient contribution: backlit scattering weighted by light color',
        'float ambientBacklit = max(-dot(viewDir, ambientLightDirections[i]), 0.0);',
        'ambientBacklit *= ambientBacklit; // Square for contrast',

        '// Modulate by wave elevation (higher crests scatter more)',
        'float ambientTerm = ambientBacklit * waveElevation;',

        '// Add contribution from this light',
        'totalAmbientScatter += ambientLightColors[i] * ambientTerm;',
      '}',

      'return totalAmbientScatter;',
    '}',

    '#if($caustics_enabled)',
      'float causticShader(vec2 uv, float t){',
        'float tModified = (t / 20.0);',
        'vec2 uv1 = uv + vec2(0.8, 0.1) * tModified;',
        'vec2 uv2 = uv - vec2(0.2, 0.7) * tModified;',
        'float aSample1 = texture(causticMap, uv1).r;',
        'float aSample2 = texture(causticMap, uv2).g;',
        'return min(aSample1, aSample2);',
      '}',
    '#endif',

    '//Converted from the Minstrel Water Engine',
    '/*',
    'MIT License',

    'Copyright (c) 2018 Jingping Yu',

    'Permission is hereby granted, free of charge, to any person obtaining a copy',
    'of this software and associated documentation files (the "Software"), to deal',
    'in the Software without restriction, including without limitation the rights',
    'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
    'copies of the Software, and to permit persons to whom the Software is',
    'furnished to do so, subject to the following conditions:',

    'The above copyright notice and this permission notice shall be included in all',
    'copies or substantial portions of the Software.',

    'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
    'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
    'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
    'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
    'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,',
    'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE',
    'SOFTWARE.',
    '*/',
    '#if($foam_enabled)',
      '//Foam amount is now pre-computed in the FFT normal map alpha channel',
    '#endif',

    '#if($atmospheric_perspective_enabled)',
      '//Compute sky radiance in a given world-space direction using the same atmosphere LUTs',
      "//as applyAtmosphericPerspective. This matches a-starry-sky's own sky rendering, so",
      '//reflection colors are continuous with the visible sky at any view direction.',
      '//Returns LINEAR radiance (same convention as the rest of the SSR path).',
      'vec3 computeSkyRadiance(vec3 worldDir){',
        '//Convert from THREE.js world coords to a-starry-sky coords (same transform as applyAtmosphericPerspective)',
        'vec3 skyDir = vec3(-worldDir.z, worldDir.y, -worldDir.x);',

        '//Clamp to horizon so reflection rays pointing slightly below horizon (off wave faces',
        '//tilted toward the viewer) snap to horizon color rather than sampling invalid LUT coords.',
        'float viewCosZenith = max(skyDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscatter',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(skyDir, atmSunPosition);',
        'vec3 skySun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun);',

        '//Moon inscatter',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(skyDir, atmMoonPosition);',
        'vec3 skyMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon);',

        "//Base sky ambient — matches a-starry-sky's own atmosphere pass main() (not linearAtmosphericPass).",
        '//Small bluish floor that fades with altitude/horizon via the 2D transmittance LUT.',
        'vec3 transmittanceFade = texture(atmosphereTransmittance, vec2(xParam, yHeight)).rgb;',
        'vec3 baseSkyLighting = 0.25 * vec3(2E-3, 3.5E-3, 9E-3) * transmittanceFade;',

        'return skySun + skyMoon + baseSkyLighting;',
      '}',

      '//Atmospheric perspective for ground-level surfaces.',
      '//Uses distance-based extinction with LUT-sampled multi-scattered inscattering.',
      '//At the same height: S(A->B) = S(A->inf) * (1 - T(A->B))',
      'vec3 applyAtmosphericPerspective(vec3 color, vec3 worldPos){',
        'vec3 worldViewDir = normalize(worldPos - cameraPosition);',
        "//Convert view direction from THREE.js world space to a-starry-sky's coordinate",
        '//system. Sun world direction = (-sp.z, sp.y, -sp.x) from quadOffset, so the',
        '//inverse transform from world to sky coords is: skyDir = (-world.z, world.y, -world.x)',
        'vec3 viewDir = vec3(-worldViewDir.z, worldViewDir.y, -worldViewDir.x);',
        'float dist = length(worldPos - cameraPosition) * METERS_TO_KM * atmDistanceScale;',

        '//Distance-based extinction along the camera-to-surface path',
        'vec3 extinction = exp(-(RAYLEIGH_BETA + EARTH_MIE_BETA_EXTINCTION) * dist);',

        '//Attenuate surface color',
        'color *= extinction;',

        '//LUT coordinates for inscattering lookup',
        'float viewCosZenith = max(viewDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscattering from 3D LUTs',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(viewDir, atmSunPosition);',
        'vec3 fogSun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun)',
                    '* (1.0 - extinction);',

        '//Moon inscattering from 3D LUTs',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(viewDir, atmMoonPosition);',
        'vec3 fogMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon)',
                     '* (1.0 - extinction);',

        'return color + fogSun + fogMoon;',
      '}',
    '#endif',

    'void main(){',
      'mat3 instanceMatrixMat3 = mat3(vInstanceMatrix[0].xyz, vInstanceMatrix[1].xyz, vInstanceMatrix[2].xyz );',
      'mat3 modelMatrixMat3 = mat3(vModelMatrix[0].xyz, vModelMatrix[1].xyz, vModelMatrix[2].xyz );',

      '//Use the displaced position from the vertex shader directly — ensures worldPosition',
      '//matches the actual geometry (vertex shader applies displacementFade; resampling here',
      '//would skip that, causing LOD tile edge divergence).',
      'vec3 offsetPosition = vDisplacedPosition;',
      '//Still need displacement for height-based effects (translucency, scattering)',
      'vec3 displacement = offsetPosition - vPosition;',
      'float height = (offsetPosition.y + linearScatteringHeightOffset) / linearScatteringTotalScatteringWaveHeight;',
      'vec4 worldPosition = vModelMatrix * vInstanceMatrix * vec4(offsetPosition, 1.0);',
      'vec2 exclusionPosition = 0.5 * (((worldPosition.xz - cameraPosition.xz) / vec2(1024.0)) + 1.0);',
      'exclusionPosition = vec2(exclusionPosition.x, 1.0 - exclusionPosition.y);',
      'if(exclusionPosition.x < 1.0 && exclusionPosition.x > 0.0 && exclusionPosition.y < 1.0 && exclusionPosition.y > 0.0){',
        'vec2 discardHeightData = texture2D(exclusionMap, exclusionPosition).ga;',
        'float discardHeight = discardHeightData.x;',
        'if((discardHeightData.y > 0.5) && worldPosition.y > discardHeight){',
          'discard;',
        '}',
      '}',
      'float distanceToWorldPosition = distance(worldPosition.xyz, cameraPosition.xyz);',
      'float LOD = pow(2.0, clamp(7.0 - (distanceToWorldPosition / (sizeOfOceanPatch * 7.0)), 2.0, 7.0));',

      '//Analytical surface normals from FFT slope textures.',
      "//Each cascade's slope texture contains R=dh/dx, G=dh/dz computed in the frequency domain",
      '//(h_k spectrum multiplied by i*kx / i*kz, then IFFTed). This gives exact gradients at ALL',
      '//frequencies with zero finite-difference aliasing — replaces the old Sobel approach that',
      '//was limited to cascades 0-1 due to Nyquist constraints.',
      'float normalLodFactor = clamp(1.0 - distanceToWorldPosition / (sizeOfOceanPatch * 7.0), 0.0, 1.0);',
      'float normalDetailFade = mix(0.15, 1.0, normalLodFactor * normalLodFactor);',

      '//Central differences on displacement for Jacobian and normals — cascades 0-1 only.',
      '//Computes full 3D displacement derivatives (not just XZ) so the surface normal',
      '//can be computed from the cross product of displaced tangent vectors (Crest-style).',
      '//Using finite differences for ALL components ensures height and chop derivatives',
      '//are consistent — mixing analytical FFT slopes with finite-difference chop derivatives',
      '//creates a precision mismatch that produces incorrect normals.',
      'vec3 rawDdx = vec3(0.0);',
      'vec3 rawDdz = vec3(0.0);',
      '//Cascade 0 height slope saved separately for macro normal (specular)',
      'vec2 cascade0HeightSlope;',
      '{',
        'float eps = 1.0 / patchDataSize;',
        'float worldStep = cascadePatchSizes[0] / patchDataSize;',
        'vec2 uv = (vWorldXZ + cascadeSpatialOffsets[0]) / cascadePatchSizes[0];',
        'vec3 rawL = texture2D(cascadeDisplacementTextures[0], uv + vec2(-eps,  0.0)).xyz;',
        'vec3 rawR = texture2D(cascadeDisplacementTextures[0], uv + vec2( eps,  0.0)).xyz;',
        'vec3 rawB = texture2D(cascadeDisplacementTextures[0], uv + vec2( 0.0, -eps)).xyz;',
        'vec3 rawT = texture2D(cascadeDisplacementTextures[0], uv + vec2( 0.0,  eps)).xyz;',
        'rawDdx += (rawR - rawL) / (2.0 * worldStep);',
        'rawDdz += (rawT - rawB) / (2.0 * worldStep);',
        'cascade0HeightSlope = vec2(rawDdx.y, rawDdz.y);',
      '}',
      '{',
        'float eps = 1.0 / patchDataSize;',
        'float worldStep = cascadePatchSizes[1] / patchDataSize;',
        'vec2 uv = (vWorldXZ + cascadeSpatialOffsets[1]) / cascadePatchSizes[1];',
        'vec3 rawL = texture2D(cascadeDisplacementTextures[1], uv + vec2(-eps,  0.0)).xyz;',
        'vec3 rawR = texture2D(cascadeDisplacementTextures[1], uv + vec2( eps,  0.0)).xyz;',
        'vec3 rawB = texture2D(cascadeDisplacementTextures[1], uv + vec2( 0.0, -eps)).xyz;',
        'vec3 rawT = texture2D(cascadeDisplacementTextures[1], uv + vec2( 0.0,  eps)).xyz;',
        'rawDdx += (rawR - rawL) / (2.0 * worldStep);',
        'rawDdz += (rawT - rawB) / (2.0 * worldStep);',
      '}',
      'if(ringIndex <= 3){',
        'float eps = 1.0 / patchDataSize;',
        'float worldStep = cascadePatchSizes[2] / patchDataSize;',
        'float fade = clamp(1.0 - distanceToWorldPosition / (cascadePatchSizes[2] * 10.0), 0.0, 1.0);',
        'vec2 uv = (vWorldXZ + cascadeSpatialOffsets[2]) / cascadePatchSizes[2];',
        'vec3 rawL = texture2D(cascadeDisplacementTextures[2], uv + vec2(-eps,  0.0)).xyz;',
        'vec3 rawR = texture2D(cascadeDisplacementTextures[2], uv + vec2( eps,  0.0)).xyz;',
        'vec3 rawB = texture2D(cascadeDisplacementTextures[2], uv + vec2( 0.0, -eps)).xyz;',
        'vec3 rawT = texture2D(cascadeDisplacementTextures[2], uv + vec2( 0.0,  eps)).xyz;',
        'rawDdx += fade * (rawR - rawL) / (2.0 * worldStep);',
        'rawDdz += fade * (rawT - rawB) / (2.0 * worldStep);',
      '}',
      'if(ringIndex <= 2){',
        'float eps = 1.0 / patchDataSize;',
        'float worldStep = cascadePatchSizes[3] / patchDataSize;',
        'float fade = clamp(1.0 - distanceToWorldPosition / (cascadePatchSizes[3] * 10.0), 0.0, 1.0);',
        'vec2 uv = (vWorldXZ + cascadeSpatialOffsets[3]) / cascadePatchSizes[3];',
        'vec3 rawL = texture2D(cascadeDisplacementTextures[3], uv + vec2(-eps,  0.0)).xyz;',
        'vec3 rawR = texture2D(cascadeDisplacementTextures[3], uv + vec2( eps,  0.0)).xyz;',
        'vec3 rawB = texture2D(cascadeDisplacementTextures[3], uv + vec2( 0.0, -eps)).xyz;',
        'vec3 rawT = texture2D(cascadeDisplacementTextures[3], uv + vec2( 0.0,  eps)).xyz;',
        'rawDdx += fade * (rawR - rawL) / (2.0 * worldStep);',
        'rawDdz += fade * (rawT - rawB) / (2.0 * worldStep);',
      '}',
      'if(ringIndex <= 1){',
        'float eps = 1.0 / patchDataSize;',
        'float worldStep = cascadePatchSizes[4] / patchDataSize;',
        'float fade = clamp(1.0 - distanceToWorldPosition / (cascadePatchSizes[4] * 10.0), 0.0, 1.0);',
        'vec2 uv = (vWorldXZ + cascadeSpatialOffsets[4]) / cascadePatchSizes[4];',
        'vec3 rawL = texture2D(cascadeDisplacementTextures[4], uv + vec2(-eps,  0.0)).xyz;',
        'vec3 rawR = texture2D(cascadeDisplacementTextures[4], uv + vec2( eps,  0.0)).xyz;',
        'vec3 rawB = texture2D(cascadeDisplacementTextures[4], uv + vec2( 0.0, -eps)).xyz;',
        'vec3 rawT = texture2D(cascadeDisplacementTextures[4], uv + vec2( 0.0,  eps)).xyz;',
        'rawDdx += fade * (rawR - rawL) / (2.0 * worldStep);',
        'rawDdz += fade * (rawT - rawB) / (2.0 * worldStep);',
      '}',
      'if(ringIndex == 0){',
        'float eps = 1.0 / patchDataSize;',
        'float worldStep = cascadePatchSizes[5] / patchDataSize;',
        'float fade = clamp(1.0 - distanceToWorldPosition / (cascadePatchSizes[5] * 10.0), 0.0, 1.0);',
        'vec2 uv = (vWorldXZ + cascadeSpatialOffsets[5]) / cascadePatchSizes[5];',
        'vec3 rawL = texture2D(cascadeDisplacementTextures[5], uv + vec2(-eps,  0.0)).xyz;',
        'vec3 rawR = texture2D(cascadeDisplacementTextures[5], uv + vec2( eps,  0.0)).xyz;',
        'vec3 rawB = texture2D(cascadeDisplacementTextures[5], uv + vec2( 0.0, -eps)).xyz;',
        'vec3 rawT = texture2D(cascadeDisplacementTextures[5], uv + vec2( 0.0,  eps)).xyz;',
        'rawDdx += fade * (rawR - rawL) / (2.0 * worldStep);',
        'rawDdz += fade * (rawT - rawB) / (2.0 * worldStep);',
      '}',
      'rawDdx *= waveHeightMultiplier;',
      'rawDdz *= waveHeightMultiplier;',

      '//Jacobian: detect surface folds — still used for inscatter modulation and normal blending',
      'vec2 foamDdx = -chop * rawDdx.xz;',
      'vec2 foamDdz = -chop * rawDdz.xz;',
      'float jacobian = (1.0 + foamDdx.x) * (1.0 + foamDdz.y) - foamDdx.y * foamDdz.x;',
      'float turbulence = max(0.0, 1.0 - jacobian);',

      '//Persistent foam: read from displacement texture alpha (accumulated by the composer',
      '//via Jacobian-based ping-pong each frame). Sum active cascades with LOD fade.',
      'float fftFoamAmount = 0.0;',
      '{',
        'vec2 uv0 = (vWorldXZ + cascadeSpatialOffsets[0]) / cascadePatchSizes[0];',
        'fftFoamAmount += texture2D(cascadeDisplacementTextures[0], uv0).a;',
      '}',
      '{',
        'vec2 uv1 = (vWorldXZ + cascadeSpatialOffsets[1]) / cascadePatchSizes[1];',
        'fftFoamAmount += texture2D(cascadeDisplacementTextures[1], uv1).a;',
      '}',
      'if(ringIndex <= 3){',
        'vec2 uv2 = (vWorldXZ + cascadeSpatialOffsets[2]) / cascadePatchSizes[2];',
        'float fade2 = clamp(1.0 - distanceToWorldPosition / (cascadePatchSizes[2] * 10.0), 0.0, 1.0);',
        'fftFoamAmount += fade2 * texture2D(cascadeDisplacementTextures[2], uv2).a;',
      '}',
      'if(ringIndex <= 2){',
        'vec2 uv3 = (vWorldXZ + cascadeSpatialOffsets[3]) / cascadePatchSizes[3];',
        'float fade3 = clamp(1.0 - distanceToWorldPosition / (cascadePatchSizes[3] * 10.0), 0.0, 1.0);',
        'fftFoamAmount += fade3 * texture2D(cascadeDisplacementTextures[3], uv3).a;',
      '}',
      'fftFoamAmount = clamp(fftFoamAmount, 0.0, 1.0);',

      '//Crest-style surface normal from cross product of displaced tangent vectors.',
      '//Surface parameterization: P(u,v) = (u - chop*Dx, Dy, v - chop*Dz)',
      '//Tangent vectors include the full Jacobian of the displacement mapping:',
      '//  Tx = dP/du = (1 - chop*dDx/du, dDy/du, -chop*dDz/du)',
      '//  Tz = dP/dv = (-chop*dDx/dv, dDy/dv, 1 - chop*dDz/dv)',
      '//All derivatives come from the same finite-difference samples for consistency.',
      'vec2 totalSlope = vec2(rawDdx.y, rawDdz.y);',
      'vec3 Tx = vec3(1.0 + foamDdx.x, totalSlope.x, foamDdx.y);',
      'vec3 Tz = vec3(foamDdz.x, totalSlope.y, 1.0 + foamDdz.y);',
      'vec3 displacedNormal = normalize(cross(Tz, Tx));',
      '//Cross product Y component equals the Jacobian determinant — positive when surface is',
      '//well-behaved, negative at folds. Force upward to avoid lighting inversion (Crest does',
      '//the same: crossProd.y = max(crossProd.y, 0.0001)).',
      'if(displacedNormal.y < 0.0) displacedNormal = -displacedNormal;',
      '//Blend toward flat normal at fold points and at distance',
      'float foldBlend = smoothstep(0.0, 0.3, jacobian);',
      'displacedNormal = normalize(mix(vec3(0.0, 1.0, 0.0), displacedNormal, foldBlend * normalDetailFade));',
      'if(displacedNormal.y < 0.0) displacedNormal = -displacedNormal;',

      '//Macro-scale normal from cascade 0 only — used for GGX specular orientation.',
      '//Using cascade 0+1 normals for NdotH creates a "sand-ripple" pattern when the moon',
      '//is perpendicular to the view: each 1-4m wave face creates its own sharp specular',
      '//hotspot. Cascade 0 only gives a wide, smooth specular lobe (Sea of Thieves style).',
      '//Fresnel still uses displacedNormal (cascade 0+1) so it correctly matches the geometry.',
      'vec2 macroSlope = cascade0HeightSlope * waveHeightMultiplier;',
      'float macroSlopeLen = length(macroSlope);',
      'if(macroSlopeLen > 1.2) macroSlope *= 1.2 / macroSlopeLen;',
      'vec3 macroNormal = normalize(vec3(-macroSlope.x, 1.0, -macroSlope.y));',
      'if(macroNormal.y < 0.0) macroNormal = -macroNormal;',
      'macroNormal = normalize(mix(vec3(0.0, 1.0, 0.0), macroNormal, foldBlend * normalDetailFade));',
      'if(macroNormal.y < 0.0) macroNormal = -macroNormal;',

      '//Additive world-space normal blending (Crest-style):',
      '//Decode only xy of each map (tangent x → world x, tangent y → world z) and',
      '//add directly to displacedNormal.xz. The y component stays anchored to the',
      '//FFT value, so hemisphere inversions from steep waves + strong maps are impossible.',
      '//Normal map UV scale: tile at world-space frequencies appropriate for micro-ripples.',
      '//Small: ~12m tiles (capillary/wind ripples). Large: sampled at two perpendicular',
      '//angles (~80m) and averaged — breaks the corduroy banding that comes from scrolling',
      '//a single directional map in the wind direction.',
      'vec2 smallNormalMapOffset = (worldPosition.xz + t * smallNormalMapVelocity) / 12.0;',
      'vec2 largeNormalMapOffset = (worldPosition.xz + t * largeNormalMapVelocity) / 80.0;',
      '//90°-rotated second sample of the large map to kill directional bias',
      'vec2 largeNormalMapOffset2 = (vec2(-worldPosition.z, worldPosition.x) + t * largeNormalMapVelocity) / 80.0;',
      "//Foam textures use a separate UV at a larger world-scale so they don't tile tiny.",
      '//Two layers: one rotated 90° at a different scale (Crest technique) to kill the brick-tiling pattern.',
      'vec2 foamTextureUV  = (worldPosition.xz + t * smallNormalMapVelocity) / (sizeOfOceanPatch / 2.0);',
      'vec2 foamTextureUV2 = (vec2(-worldPosition.z, worldPosition.x) + t * smallNormalMapVelocity) / (sizeOfOceanPatch * 0.365);',
      'float smallNormalMapFadeout = clamp((500.0 - distanceToWorldPosition) / 250.0, 0.0, 1.0);',
      'float largeNormalMapFadeout = clamp((3000.0 - distanceToWorldPosition) / 2500.0, 0.0, 1.0);',

      '//Normal maps re-enabled at reduced strength.',
      '//The current textures (water-normal-1/2.png) are too rocky — ideally replace them',
      "//with softer water ripple textures (like Crest's WaveNormals.png). For now, use",
      '//very low multipliers (0.05) so they add subtle variation to break up coherent FFT',
      '//banding without imposing a stone-like texture on the surface.',
      'float normalMapScale = 0.15;',
      'vec2 smallNM = texture2D(smallNormalMap, smallNormalMapOffset).xy * 2.0 - 1.0;',
      'vec2 largeNM = (texture2D(largeNormalMap, largeNormalMapOffset).xy +',
                      'texture2D(largeNormalMap, largeNormalMapOffset2).xy) - 1.0;',

      'vec3 combinedNormalMap = displacedNormal;',
      'combinedNormalMap.xz += smallNM * smallNormalMapStrength * normalMapScale * smallNormalMapFadeout;',
      'combinedNormalMap.xz += largeNM * largeNormalMapStrength * normalMapScale * largeNormalMapFadeout;',
      '#if($foam_enabled)',
        'float foamAmount = fftFoamAmount;',
        'vec2 foamPosition = 0.5 * (((worldPosition.xz - cameraPosition.xz) / vec2(2048.0)) + 1.0);',
        'foamPosition = vec2(foamPosition.x, 1.0 - foamPosition.y);',
        'if(foamPosition.x < 1.0 && foamPosition.x > 0.0 && foamPosition.y < 1.0 && foamPosition.y > 0.0){',
          'vec2 foamHeightData = texture2D(foamRenderMap, foamPosition).ga;',
          'if((foamHeightData.y > 0.5)){',
            'foamAmount = max(foamAmount, 1.0 - abs(clamp(worldPosition.y - foamHeightData.x - 10.0, 0.0, 10.0) / 10.0));',
          '}',
        '}',
        'vec2 foamNM = texture2D(foamNormalMap, smallNormalMapOffset).xy * 2.0 - 1.0;',
        'combinedNormalMap.xz += foamNM * 0.5 * foamAmount * largeNormalMapFadeout;',
      '#else',
        'float foamAmount = 0.0;',
      '#endif',
      'combinedNormalMap = normalize(combinedNormalMap);',

      'vec3 normalizedViewVector = normalize(worldPosition.xyz - cameraPosition);',
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',

      '//Screen-space reflection: reflect the view ray off the displaced water normal and',
      '//ray-march against the refraction depth buffer (already rendered this frame, free).',
      '//Correctly samples sky/atmosphere at the horizon — no planar camera terrain capture.',
      'vec3 worldIncidentDir = normalize(worldPosition.xyz - cameraPosition);',
      '//Use macroNormal (cascade 0 only, ~2m/texel) for SSR ray direction — avoids the',
      '//high-frequency per-pixel noise that displacedNormal causes in reflection lookups.',
      'vec3 ssrReflectDir    = reflect(worldIncidentDir, macroNormal);',
      '//screenSpaceReflection() always returns LINEAR values (see function comment).',
      'vec3 reflectedLight   = screenSpaceReflection(worldPosition.xyz, ssrReflectDir);',

      '//Screen-space refraction',
      '//Distort UVs based on FFT normal only — same reason as reflection: avoids visible normal map tiling',
      'vec2 distortion = displacedNormal.xz * 0.03;',
      'vec2 refractedUV = clamp(screenUV + distortion, 0.001, 0.999);',

      '//Sample refraction color and depth',
      'float refractionDepthRaw = texture2D(refractionDepthTexture, refractedUV).r;',
      'float refractionDepthLinear = linearizeDepth(refractionDepthRaw);',
      'float surfaceDepthLinear = linearizeDepth(gl_FragCoord.z);',

      '//If distorted UV samples something closer than the water surface, fall back to undistorted',
      'if(refractionDepthLinear < surfaceDepthLinear - 0.5){',
        'refractedUV = screenUV;',
        'refractionDepthRaw = texture2D(refractionDepthTexture, refractedUV).r;',
        'refractionDepthLinear = linearizeDepth(refractionDepthRaw);',
      '}',

      'vec3 refractedLight = texture2D(refractionColorTexture, refractedUV).rgb;',

      '//Reconstruct world-space position from refraction depth',
      'vec4 clipPos = vec4(refractedUV * 2.0 - 1.0, refractionDepthRaw * 2.0 - 1.0, 1.0);',
      'vec4 viewPos = inverseProjectionMatrix * clipPos;',
      'viewPos /= viewPos.w;',
      'vec3 pointXYZ = (inverseViewMatrix * viewPos).xyz;',

      '//Use the reconstructed Y position to distinguish underwater vs above-water geometry',
      'float distanceToPoint;',
      'bool isDeepWater;',
      '//Detect sky/far-plane fragments: if the refraction depth is near the far plane,',
      '//this is sky bleeding through, not real underwater geometry.',
      'bool isFarPlane = refractionDepthLinear > cameraNearFar.y * 0.99;',
      'if(!isFarPlane && pointXYZ.y < baseHeightOffset && refractionDepthLinear > surfaceDepthLinear){',
        '//Underwater geometry visible - use actual vertical water column depth (surface Y minus seabed Y).',
        '//Camera-depth difference (refractionDepthLinear - surfaceDepthLinear) blows up at oblique angles:',
        '//a 1m deep seabed seen at a grazing angle has huge camera-depth delta but only 1m of actual water.',
        '//worldPosition.y is the displaced surface height; pointXYZ.y is the refracted geometry height.',
        'distanceToPoint = min(worldPosition.y - pointXYZ.y, 500.0);',
        'isDeepWater = false;',
      '}',
      'else{',
        '//Above-water geometry, sky, or far-plane - no background light survives this depth.',
        '//Zero out refracted light to prevent HDR sky/sun from bleeding through.',
        'distanceToPoint = 1000.0;',
        'isDeepWater = true;',
      '}',

      '//Physically-based underwater light transport',
      '//Extinction = absorption + scattering (Beer-Lambert for both)',
      'vec3 extinction = waterAbsorption + waterScattering;',
      'vec3 transmittance = exp(-extinction * distanceToPoint);',

      'refractedLight = sRGBToLinear(vec4(refractedLight, 1.0)).rgb;',
      'if(isDeepWater){',
        'refractedLight = vec3(0.0);',
      '}',

      '//Sun light entering the water column',
      '//Fresnel transmission at the air->water interface from above',
      'float sunCosZenith = max(dot(-brightestDirectionalLightDirection, vec3(0.0, 1.0, 0.0)), 0.0);',
      'float sunTransmission = 1.0 - fresnelAirToWater(sunCosZenith);',

      '//Mie phase function: how much scattered light reaches the camera',
      '//The scattered light must travel TOWARD the camera (-normalizedViewVector),',
      '//so the scattering angle is between the incoming sun direction and the',
      '//outgoing direction toward the camera.',
      'float cosViewSun = dot(-normalizedViewVector, brightestDirectionalLightDirection);',
      'float phaseSingle = waterMiePhase(cosViewSun, waterMieG);',

      '//Multi-scattering approximation: in a thick water column, repeated scattering',
      '//events isotropize the light field. Model this as an additive isotropic term.',
      'float phaseMulti = 1.0 / (4.0 * 3.14159265);',

      '//Single-scattering integral over the water column depth',
      '//integral of scattering * exp(-extinction * d) dd from 0 to depth',
      '//= (scattering / extinction) * (1 - exp(-extinction * depth))',
      'vec3 inscatterIntegral = waterScattering / max(extinction, vec3(0.0001)) * (1.0 - transmittance);',

      '// === NEW PHYSICALLY-BASED SCATTERING MODEL ===',
      '// Calculate each scattering term separately for debugging/visualization',

      'float waveElevation = max(height, 0.0);',

      '// Calculate individual scattering terms',
      'float term1 = scatterTerm1(-brightestDirectionalLightDirection, normalizedViewVector, displacedNormal, height, k1ScatterAmount);',
      'float term2 = scatterTerm2(normalizedViewVector, displacedNormal, k2ViewDependence);',
      'float fresnelFresnel = fresnelAbsorption(-brightestDirectionalLightDirection, displacedNormal, fresnelAbsorptionAmount);',
      'float term3 = scatterTerm3(-brightestDirectionalLightDirection, displacedNormal, k3DirectScatter);',
      '//Bubble turbidity: microbubble haze present in all ocean water, not just at foam crests.',
      '//Uses turbulence (instant Jacobian compression) for wave-dependent churn, plus a constant',
      '//floor (0.2) for the baseline scatter always present in ocean water.',
      '//fftFoamAmount is kept for white foam rendering; turbulence drives the scatter model.',
      'float bubbleDensity = clamp(turbulence + 0.2, 0.0, 1.0);',
      'float term4 = scatterTerm4(bubbleDensity, k4ParallaxScatter);',

      '// First scattering term: (k₁ ... + k₂ ...) * C_ss * L_sun * Fresnel',
      'vec3 mainScatter = (term1 + term2) * waterScattering * brightestDirectionalLight * fresnelFresnel;',

      '// Second scattering term: k₃(ωᵢ · ωₙ) * C_ss * L_sun',
      'vec3 directScatter = term3 * waterScattering * brightestDirectionalLight;',

      '// Fourth scattering term: k₄ P_b * L_sun (bubble density, not foam accumulation)',
      'vec3 term4Scatter = term4 * brightestDirectionalLight;',

      '// L_scatter = (k1 + k2) * C_ss * L_sun * 1/(1 + A(ωᵢ))',
      '//           + k3 * C_ss * L_sun',
      '//           + k4 * P_f * L_sun',
      'vec3 inscatterLight = (mainScatter + directScatter + term4Scatter) * waterTurbidity;',

      '// Add ambient light contributions from all directional lights',
      'vec3 ambientScatter = ambientLightScattering(normalizedViewVector, displacedNormal, waveElevation);',
      'inscatterLight += ambientScatter * waterScattering;',

      '/* OLD CODE - COMMENTED OUT FOR REFERENCE',
      '//Jacobian SSS modulation (Crest technique): flat areas appear clearer/deeper by reducing',
      '//inscatter; wave crests remain bright as the Jacobian pinches and thins the water column.',
      '//turbulence is 0 on flat water, >0 at compressed crests.',
      '//NOTE: was mix(0.5, 1.0) but the 2x contrast made wave crests pitch-black at night',
      '//(crests have turbulence=0 → inscatter halved → only visible light source gone).',
      '//Reduced to mix(0.8, 1.0) — still physically meaningful but visually acceptable at night.',
      'inscatterLight *= mix(0.8, 1.0, turbulence);',

      '//Wave-crest translucency: estimate light path thickness through the wave body.',
      '//At a crest the water is thin - light from the sun side passes through a short',
      '//path and exits toward the camera, giving the characteristic green-gold glow.',
      '//This only occurs when the crest is backlit (looking through the wave toward the sun).',
      '//',
      '//Thickness is approximated from wave height above base water level and the',
      '//angle between the surface normal and the sun direction. No ray marching needed -',
      '//just geometry: a steep wave face lit from behind has a very short internal path.',
      'float minCrestThickness = 3.0;',
      'float crestThickness = max(linearScatteringTotalScatteringWaveHeight * (1.0 - waveElevation) / sunNormalDot, minCrestThickness);',
      'float waveThickness = mix(distanceToPoint, crestThickness, waveElevation);',
      'vec3 waveTransmittance = exp(-extinction * waveThickness);',

      '//Backlit factor: the translucent glow is only visible when looking through',
      '//the wave toward the sun. The view vector and light direction face toward each',
      '//other when backlit (dot < 0), so negate to get a positive value for backlit crests.',
      'float backlitFactor = max(-dot(normalizedViewVector, brightestDirectionalLightDirection), 0.0);',
      'backlitFactor *= backlitFactor;',

      '//Thin crests: transmitted sunlight passes through the wave body with its own',
      '//absorption color (green-gold for thin water), added on top of the volume inscatter.',
      'vec3 crestLight = waveTransmittance * sunTransmission * brightestDirectionalLight * waveElevation * backlitFactor;',
      'inscatterLight += crestLight;',
      '*/',

      "//Apply Schlick's approximation for the fresnel amount",
      '//https://graphicscompendium.com/raytracing/11-fresnel-beer',
      '//Use macro-scale FFT normal (displacedNormal) rather than the full micro-detail combinedNormalMap.',
      '//Micro-ripples drive the GGX specular D term above; using them here too floods every steep',
      '//wave face with sky reflection, washing out the whole surface with white.',
      'float cosTheta = clamp(dot(displacedNormal, -normalizedViewVector), 0.0, 1.0);',
      'float fresnelFactor = r0 + (1.0 - r0) * pow(1.0 - cosTheta, 5.0);',
      '//Cap Fresnel so the water body color always shows through — at grazing angles the',
      '//planar reflection only captures sky (no ocean self-reflection), so uncapped Fresnel',
      '//makes everything sky-colored. Cap gives a floor of body-color contribution.',
      '//Cap at 0.65 (Crest uses _Specular=0.7 for the same reason): prevents the horizon',
      '//from becoming 90%+ sky reflection which washes out to bright white.',
      '//Cap Fresnel: at grazing angles (horizon) this hits 1.0 but the planar reflection',
      '//only captures sky — at 65% cap, individual stars reflect visibly in dark water.',
      '//0.35 keeps the horizon glossy while preventing star points from dominating.',
      'fresnelFactor = min(fresnelFactor, 0.35);',
      '//Trough damping: wave troughs sit below surrounding crests which occlude the sky at',
      '//grazing angles. Reduce Fresnel in troughs so they show water body color rather than',
      '//sky. height ≈ 0 at deep troughs, ≈ 0.5 at mean level, ≈ 1 at crests.',
      'float troughDampen = smoothstep(0.1, 0.55, height);',
      'fresnelFactor *= mix(0.4, 1.0, troughDampen);',
      '//Clamp HDR values — metering survey is linear float and can be bright near the sun.',
      '//Cap at 4.0 to prevent saturation while preserving sky brightness range.',
      'reflectedLight = min(reflectedLight, vec3(4.0));',

      '#if($caustics_enabled)',
        '//Calculate caustic lighting using reconstructed world position',
        'float causticLightingR = causticShader(0.01 * pointXYZ.xz + 0.005, t);',
        'float causticLightingG = causticShader(0.01 * pointXYZ.xz, t);',
        'float causticLightingB = causticShader(0.01 * pointXYZ.xz - 0.005, t);',
        'vec3 causticLighting = causticIntensityMultiplier * 20.0 * vec3(causticLightingR, causticLightingG, causticLightingB);',
        'if(distance(cameraPosition, pointXYZ.xyz) > 2500.0){',
          'causticLighting = vec3(1.0);',
        '}',
        'refractedLight *= (causticLighting);',
      '#endif',
      'refractedLight *= transmittance;',

      '//Calculate specular lighting and surface lighting',
      'float lightMag = length(brightestDirectionalLight);',
      'vec3 normalizedLightIntensity = lightMag > 0.001 ? brightestDirectionalLight / lightMag : vec3(0.0);',
      'vec3 directionalSurfaceLighting = normalizedLightIntensity * max(dot(macroNormal, -brightestDirectionalLightDirection), 0.0);',

      '//GGX Cook-Torrance specular',
      'float waterRoughness = mix(0.22, 0.40, fftFoamAmount);',
      'vec3 H = normalize(-normalizedViewVector + (-brightestDirectionalLightDirection));',
      '//Use displacedNormal (all active FFT cascades, no texture maps) for specular.',
      '//macroNormal (cascade 0 only, ~2m/texel) is too coarse — specular follows the low-poly',
      '//mesh silhouette rather than the wave surface. displacedNormal has per-ring detail',
      '//without texture-map tiling artifacts (the old "sand-ripple" concern was about combinedNormalMap).',
      'float NdotH = max(dot(displacedNormal, H), 1e-5);',
      'float NdotV = max(dot(displacedNormal, -normalizedViewVector), 1e-5);',
      'float NdotL = max(dot(displacedNormal, -brightestDirectionalLightDirection), 1e-5);',

      'float D = min(ggxDistribution(NdotH, waterRoughness), 100.0);',
      'float G_light = smithMaskingShadowing(NdotL, waterRoughness);',
      'float G_view  = smithMaskingShadowing(NdotV, waterRoughness);',
      'float G = 1.0 / (1.0 + G_light + G_view);',

      '//Lazányi-Schlick Fresnel — roughness spreads the grazing-angle Fresnel peak',
      'float fresnelSpec = mix(',
        'pow(1.0 - NdotV, 5.0 * exp(-2.69 * waterRoughness)) / (1.0 + 22.7 * pow(waterRoughness, 1.5)),',
        '1.0, r0);',

      'vec3 specular = fresnelSpec * D * G / (4.0 * NdotV + 0.001) * lightMag * normalizedLightIntensity;',

      '//Total light',
      'vec3 totalLight = specular + (2.0 / 255.0) * directionalSurfaceLighting + (253.0 / 255.0) * ((inscatterLight + refractedLight) * (1.0 - fresnelFactor) + reflectedLight * fresnelFactor);',
      '//Ambient sky irradiance: diffuse illumination from the sky dome hitting the surface.',
      '//Without this, high-Fresnel wave faces (crests tilted toward camera) appear black when',
      '//there is nothing bright to reflect — the Fresnel model alone produces no light there.',
      '//NdotUp weights by sky exposure; (1-fresnel) keeps this from fighting reflections.',
      '//Hemisphere ambient: 1.0 facing straight up, 0.5 facing horizontal, 0.0 facing down.',
      '//Prevents steep wave faces from going black — a vertical face still sees half the sky dome.',
      "//Hemisphere sky ambient: color from a-starry-sky's y-axis hemisphere light.",
      '//View-independent and color-correct at all times of day (blue at noon, orange-tinted at sunset).',
      '//skyFactor: 1.0 facing straight up, 0.5 horizontal, 0.0 facing down.',
      '//Use FFT geometry normal (no texture maps) for ambient — avoids printing normal map pattern onto the lighting.',
      '//Crest does the same: geometry normals for SSS/ambient, texture normals only for specular/refraction.',
      'float skyFactor = 0.5 + 0.5 * dot(displacedNormal, vec3(0.0, 1.0, 0.0));',
      'totalLight += skyAmbientColor * skyFactor * (1.0 - fresnelFactor) * 0.1;',
      '#if($foam_enabled)',
        '//Two-layer foam sampling: average a 90°-rotated, differently-scaled second sample',
        '//with the first to break up the repeating brick pattern (same trick as the large normal map).',
        'vec3  foamAlbedo = 0.5 * (texture2D(foamDiffuseMap, foamTextureUV).rgb  + texture2D(foamDiffuseMap, foamTextureUV2).rgb);',
        'float foamMask   = 0.5 * (texture2D(foamOpacityMap, foamTextureUV).r    + texture2D(foamOpacityMap, foamTextureUV2).r);',
        '//Average packed normals in [0,1] space, then decode once',
        'vec2  foamNMXZ   = (texture2D(foamNormalMap, foamTextureUV).xy + texture2D(foamNormalMap, foamTextureUV2).xy) - 1.0;',

        '//Foam normal: perturb the FFT surface normal with the foam normal map.',
        'vec3 foamSurfaceNormal = normalize(displacedNormal + vec3(foamNMXZ.x, 0.0, foamNMXZ.y) * 0.5);',

        '//Lambert diffuse from the primary directional light (sun/moon)',
        'float foamNdotL = max(0.0, dot(foamSurfaceNormal, -brightestDirectionalLightDirection));',
        'vec3 foamDiffuse = foamNdotL * lightMag * normalizedLightIntensity * foamAlbedo;',

        '//Sky ambient: same hemisphere model as the water surface ambient above.',
        'float foamSkyFactor = 0.5 + 0.5 * dot(foamSurfaceNormal, vec3(0.0, 1.0, 0.0));',
        'vec3 foamAmbient = skyAmbientColor * foamSkyFactor * foamAlbedo;',

        '//Crest WhiteFoamTexture technique: foam amount sets a sliding black-point on the',
        '//opacity texture. High foamAmount → black point near 0 → all texture values pass.',
        '//Low foamAmount → black point near 1 → only the brightest foam patches show.',
        '//This is fundamentally different from foamMask*foamAmount which suppresses both.',
        "//_WaveFoamFeather = 0.4 in Crest's defaults.",
        'float foamBlackPoint = clamp(1.0 - foamAmount, 0.0, 1.0);',
        'float foamBlend = smoothstep(foamBlackPoint, foamBlackPoint + 0.4, foamMask);',
        'totalLight = mix(totalLight, foamDiffuse + foamAmbient, foamBlend);',
      '#endif',

      '#if($atmospheric_perspective_enabled)',
        'totalLight = applyAtmosphericPerspective(totalLight, worldPosition.xyz);',
      '#endif',

      'gl_FragColor = linearTosRGB(vec4(MyAESFilmicToneMapping(totalLight), 1.0));',

      '//TEMP DEBUG: bottom-left = raw jacobian mapped [0,2] → [0,1] (grey=1.0=flat, black=0=folded, white=2=stretched)',
      '//            bottom-right = fftFoamAmount [0,1]',
      '{',
        'float panelSize = 200.0;',
        'vec2 fc = gl_FragCoord.xy;',
        'if(fc.x < panelSize && fc.y < panelSize){',
          'gl_FragColor = vec4(vec3(jacobian * 0.5), 1.0);',
        '}',
        'if(fc.x > screenResolution.x - panelSize && fc.y < panelSize){',
          'gl_FragColor = vec4(vec3(fftFoamAmount), 1.0);',
        '}',
      '}',

      '//Blue noise dithering to break banding (same technique as a-starry-sky)',
      'float goldenRatio = 1.61803398875;',
      'float framePhase = fract(blueNoiseTime * 0.001);',
      'ivec2 temporalOffset = ivec2(',
        '128.0 * fract(framePhase * goldenRatio),',
        '128.0 * fract(framePhase * goldenRatio * goldenRatio)',
      ');',
      'gl_FragColor.rgb += (texelFetch(blueNoiseTexture, (ivec2(mod(gl_FragCoord.xy, 128.0)) + temporalOffset) % 128, 0).rgb - vec3(0.5)) / vec3(128.0);',

      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',
    ];

    let updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedCode = originalGLSL[i];
      updatedCode = updatedCode.replace(/\$foam_enabled/g, foamEnabled ? '1' : '0');
      updatedCode = updatedCode.replace(/\$caustics_enabled/g, causticsEnabled ? '1' : '0');
      updatedCode = updatedCode.replace(/\$atmospheric_perspective_enabled/g, atmosphericPerspectiveEnabled ? '1' : '0');
      //Inject atmosphere parameterization functions where the marker is
      if(atmosphericPerspectiveEnabled && atmosphereFunctionsGLSL && updatedCode.indexOf('//ATMOSPHERE_FUNCTIONS_INJECTION_POINT') !== -1){
        updatedCode = atmosphereFunctionsGLSL;
      }
      updatedLines.push(updatedCode);
    }

    return updatedLines.join('\n');
  },

  vertexShader: [
    'precision highp float;',

    'attribute vec3 tangent;',
    'attribute vec3 bitangent;',

    'varying vec2 vUv;',
    'varying vec2 vWorldXZ;',
    'varying vec3 vPosition;',
    'varying vec3 vDisplacedPosition;',
    'varying vec3 vTangent;',
    'varying vec3 vBitangent;',
    'varying vec3 vInView;',
    'varying mat4 vInstanceMatrix;',
    'varying mat4 vModelMatrix;',
    'varying mat3 vNormalMatrix;',

    'uniform float sizeOfOceanPatch;',
    'uniform int ringIndex;',
    'uniform sampler2D cascadeDisplacementTextures[6];',
    'uniform float cascadePatchSizes[6];',
    'uniform vec2 cascadeSpatialOffsets[6];',
    'uniform float waveHeightMultiplier;',
    'uniform float chop;',

    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_vertex>',
    '#endif',


    'void main() {',
      'vec3 offsetPosition = position;',
      'mat3 instanceMatrixMat3 = mat3(instanceMatrix[0].xyz, instanceMatrix[1].xyz, instanceMatrix[2].xyz );',
      'mat3 modelMatrixMat3 = mat3(modelMatrix[0].xyz, modelMatrix[1].xyz, modelMatrix[2].xyz );',

      'vec4 worldPositionOfVertex = (modelMatrix * instanceMatrix * vec4(position, 1.0));',
      'float distanceToVertex = distance(cameraPosition.xyz, worldPositionOfVertex.xyz);',
      'vec2 worldXZ = worldPositionOfVertex.xz;',

      '//Crest-style cascade-to-LOD binding: each ring only samples cascades it can resolve.',
      '//Ring k uses cascades 0 through (5 - k), clamped to [1, 5]. Fine cascades still get',
      '//a distance fade within their ring for smooth transitions at ring boundaries.',
      '//maxCascadeIdx: ring 0 → 5, ring 1 → 4, ring 2 → 3, ring 3 → 2, ring 4+ → 1',
      'vec3 displacement = vec3(0.0);',
      'displacement += texture2D(cascadeDisplacementTextures[0], (worldXZ + cascadeSpatialOffsets[0]) / cascadePatchSizes[0]).xyz;',
      'displacement += texture2D(cascadeDisplacementTextures[1], (worldXZ + cascadeSpatialOffsets[1]) / cascadePatchSizes[1]).xyz;',
      'if(ringIndex <= 3){',
        'displacement += clamp(1.0 - distanceToVertex / (cascadePatchSizes[2] * 10.0), 0.0, 1.0) * texture2D(cascadeDisplacementTextures[2], (worldXZ + cascadeSpatialOffsets[2]) / cascadePatchSizes[2]).xyz;',
      '}',
      'if(ringIndex <= 2){',
        'displacement += clamp(1.0 - distanceToVertex / (cascadePatchSizes[3] * 10.0), 0.0, 1.0) * texture2D(cascadeDisplacementTextures[3], (worldXZ + cascadeSpatialOffsets[3]) / cascadePatchSizes[3]).xyz;',
      '}',
      'if(ringIndex <= 1){',
        'displacement += clamp(1.0 - distanceToVertex / (cascadePatchSizes[4] * 10.0), 0.0, 1.0) * texture2D(cascadeDisplacementTextures[4], (worldXZ + cascadeSpatialOffsets[4]) / cascadePatchSizes[4]).xyz;',
      '}',
      'if(ringIndex == 0){',
        'displacement += clamp(1.0 - distanceToVertex / (cascadePatchSizes[5] * 10.0), 0.0, 1.0) * texture2D(cascadeDisplacementTextures[5], (worldXZ + cascadeSpatialOffsets[5]) / cascadePatchSizes[5]).xyz;',
      '}',
      'displacement *= waveHeightMultiplier;',
      'displacement.x *= -chop;',
      'displacement.z *= -chop;',

      'offsetPosition += displacement;',

      '//Set up our varyings',
      'vUv = uv;',
      'vWorldXZ = worldPositionOfVertex.xz;',
      'vDisplacedPosition = offsetPosition;',
      'vTangent = tangent;',
      'vBitangent = bitangent;',
      'vPosition = position;',
      '//From https://stackoverflow.com/questions/59492385/angle-between-view-vector-and-normal',
      'vec4 posInView = (modelViewMatrix * instanceMatrix * vec4(offsetPosition, 1.0));',
      'posInView /= posInView[3];',
      'vInView = normalize(-posInView.xyz);',
      'vInstanceMatrix = instanceMatrix;',
      'vModelMatrix = modelMatrix;',
      'vNormalMatrix = normalMatrix;',

      '//Add support for three.js fog',
      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_vertex>',
      '#endif',

      'gl_Position = projectionMatrix * viewMatrix * modelMatrix * instanceMatrix * vec4(offsetPosition, 1.0);',
    '}',
  ].join('\n'),
};
