//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
AWater.AOcean.Materials.Ocean.waterMaterial = {
  uniforms: {
    displacementMap: {type: 't', value: null},
    fftNormalMap: {type: 't', value: null},
    smallNormalMap: {type: 't', value: null},
    largeNormalMap: {type: 't', value: null},
    causticMap: {type: 't', value: null},
    causticIntensityMultiplier: {type: 'f', value: null},
    foamDiffuseMap: {type: 't', value: null},
    foamOpacityMap: {type: 't', value: null},
    foamNormalMap: {type: 't', value: null},
    foamRoughnessMap: {type: 't', value: null},
    foamRenderMap: {type: 't', value: null},
    foamStartLevel: {type: 'f', value: 0.0},
    exclusionMap: {type: 't', value: null},
    smallNormalMapVelocity: {type: 'vec2', value: new THREE.Vector2()},
    largeNormalMapVelocity: {type: 'vec2', value: new THREE.Vector2()},
    reflectionTexture: {type: 't', value: null},
    refractionColorTexture: {type: 't', value: null},
    refractionDepthTexture: {type: 't', value: null},
    screenResolution: {type: 'vec2', value: new THREE.Vector2()},
    cameraNearFar: {type: 'vec2', value: new THREE.Vector2()},
    inverseProjectionMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    inverseViewMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    reflectionViewProjectionMatrix: {type: 'mat4', value: new THREE.Matrix4()},
    sizeOfOceanPatch: {type: 'f', value: 1.0},
    baseHeightOffset: {type: 'f', value: 0.0},
    fogNear: {type: 'f', value: null},
    fogFar: {type: 'f', value: null},
    fogDensity: {type: 'f', value: null},
    fogColor: {type: 'v3', value: new THREE.Color()},
    t: {type: 'f', value: 0.0},
    brightestDirectionalLight: {type: 'vec3', value: new THREE.Vector3(1.0,1.0,1.0)},
    brightestDirectionalLightDirection: {type: 'vec3', value: new THREE.Vector3(1.0,1.0,1.0)},
    largeNormalMapStrength: {type: 'f', value: 0.45},
    smallNormalMapStrength: {type: 'f', value: 0.35},
    lightScatteringAmounts: {type: 'vec3', value: new THREE.Vector3(88.0, 108.0, 112.0)},
    linearScatteringHeightOffset: {type: 'f', value: 10.0},
    linearScatteringTotalScatteringWaveHeight: {type: 'f', value: 20.0},
    patchDataSize: {type: 'f', value: 1024.0},
    atmosphereTransmittance: {type: 't', value: null},
    atmosphereMieInscattering: {type: 't', value: null},
    atmosphereRayleighInscattering: {type: 't', value: null},
    atmSunPosition: {type: 'vec3', value: new THREE.Vector3(0.0, 1.0, 0.0)},
    atmMoonPosition: {type: 'vec3', value: new THREE.Vector3(0.0, -1.0, 0.0)},
    atmSunHorizonFade: {type: 'f', value: 1.0},
    atmMoonHorizonFade: {type: 'f', value: 0.0},
    atmScatteringSunIntensity: {type: 'f', value: 1.0},
    atmScatteringMoonIntensity: {type: 'f', value: 0.0},
    atmMoonLightColor: {type: 'vec3', value: new THREE.Vector3(1.0, 1.0, 1.0)},
    atmCameraHeight: {type: 'f', value: 0.0},
    atmDistanceScale: {type: 'f', value: 1.0},
    blueNoiseTexture: {type: 't', value: null},
    blueNoiseTime: {type: 'f', value: 0.0}
  },

  fragmentShader: function(causticsEnabled, foamEnabled, atmosphericPerspectiveEnabled, atmosphereFunctionsGLSL){
    let originalGLSL = [
    'precision highp float;',

    'varying vec2 vUv;',
    'varying vec3 vPosition;',
    'varying vec3 vTangent;',
    'varying vec3 vBitangent;',
    'varying vec3 vInView;',
    'varying mat4 vInstanceMatrix;',
    'varying mat4 vModelMatrix;',
    'varying mat3 vNormalMatrix;',

    '//uniform vec3 cameraDirection;',
    'uniform float sizeOfOceanPatch;',
    'uniform float largeNormalMapStrength;',
    'uniform float smallNormalMapStrength;',
    'uniform float baseHeightOffset;',
    'uniform sampler2D displacementMap;',
    'uniform sampler2D fftNormalMap;',
    'uniform sampler2D smallNormalMap;',
    'uniform sampler2D largeNormalMap;',
    'uniform sampler2D exclusionMap;',
    'uniform sampler2D reflectionTexture;',
    'uniform sampler2D refractionColorTexture;',
    'uniform sampler2D refractionDepthTexture;',
    'uniform vec2 screenResolution;',
    'uniform vec2 cameraNearFar;',
    'uniform mat4 inverseProjectionMatrix;',
    'uniform mat4 inverseViewMatrix;',
    'uniform mat4 reflectionViewProjectionMatrix;',

    '#if($caustics_enabled)',
      'uniform sampler2D causticMap;',
      'uniform float causticIntensityMultiplier;',
    '#endif',

    '#if($foam_enabled)',
      '//Foam maps',
      'uniform sampler2D foamRenderMap;',
      'uniform sampler2D foamDiffuseMap;',
      'uniform sampler2D foamOpacityMap;',
      'uniform sampler2D foamNormalMap;',
      'uniform sampler2D foamRoughnessMap;',
      'uniform float foamStartLevel;',
    '#endif',

    'uniform vec2 smallNormalMapVelocity;',
    'uniform vec2 largeNormalMapVelocity;',

    'uniform vec3 brightestDirectionalLight;',
    'uniform vec3 brightestDirectionalLightDirection;',
    'uniform vec3 lightScatteringAmounts;',

    'uniform float linearScatteringHeightOffset;',
    'uniform float linearScatteringTotalScatteringWaveHeight;',

    'uniform float t;',
    'uniform float patchDataSize;',

    '//Fog variables',
    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_fragment>',
    '#endif',

    '#if($atmospheric_perspective_enabled)',
      'precision highp sampler3D;',
      'uniform sampler2D atmosphereTransmittance;',
      'uniform sampler3D atmosphereMieInscattering;',
      'uniform sampler3D atmosphereRayleighInscattering;',
      'uniform vec3 atmSunPosition;',
      'uniform vec3 atmMoonPosition;',
      'uniform float atmSunHorizonFade;',
      'uniform float atmMoonHorizonFade;',
      'uniform float atmScatteringSunIntensity;',
      'uniform float atmScatteringMoonIntensity;',
      'uniform vec3 atmMoonLightColor;',
      'uniform float atmCameraHeight;',
      'uniform float atmDistanceScale;',

      '//ATMOSPHERE_FUNCTIONS_INJECTION_POINT',
    '#endif',

    'uniform sampler2D blueNoiseTexture;',
    'uniform float blueNoiseTime;',


    "//R0 For Schlick's Approximation",
    '//With n1 = 1.33 and n0 = 1.0',
    'const float r0 = 0.02;',
    'const vec3 inverseGamma = vec3(0.454545454545454545454545);',
    'const vec3 gamma = vec3(2.2);',

    'vec2 vec2Modulo(vec2 inputUV){',
        'return (inputUV - floor(inputUV));',
    '}',

    'float linearizeDepth(float depthSample){',
      'float near = cameraNearFar.x;',
      'float far = cameraNearFar.y;',
      'return near * far / (far - depthSample * (far - near));',
    '}',

    '#if(!$atmospheric_perspective_enabled)',
      '//When atmospheric perspective is enabled, sRGBToLinear is provided by the injected atmosphere functions',
      'vec4 sRGBToLinear( in vec4 value ) {',
      '	return vec4( mix( pow( value.rgb * 0.9478672986 + vec3( 0.0521327014 ), vec3( 2.4 ) ), value.rgb * 0.0773993808, vec3( lessThanEqual( value.rgb, vec3( 0.04045 ) ) ) ), value.a );',
      '}',
    '#endif',

    'vec4 linearTosRGB(vec4 value ) {',
      'return vec4( mix( pow( value.rgb, vec3( 0.41666 ) ) * 1.055 - vec3( 0.055 ), value.rgb * 12.92, vec3( lessThanEqual( value.rgb, vec3( 0.0031308 ) ) ) ), value.a );',
    '}',

    '//From https://blog.selfshadow.com/publications/blending-in-detail/',
    'vec3 combineNormals(vec3 normal1, vec3 normal2){',
      'vec4 n1 = vec4(normal1.xyz, 1.0);',
      'vec4 n2 = vec4(normal2.xyz, 1.0);',
      'n1 = n1.xyzz * vec4(2.0, 2.0, 2.0, -2.0) + vec4(-1.0, -1.0, -1.0, 1.0);',
      'n2 = n2 * 2.0 - vec4(1.0);',
      'vec3 r;',
      'r.x = dot(n1.zxx,  n2.xyz);',
      'r.y = dot(n1.yzy,  n2.xyz);',
      'r.z = dot(n1.xyw, -n2.xyz);',

      'return 0.5 * (normalize(r) + vec3(1.0));',
    '}',

    '//Including this because someone removed this in a future versio of THREE. Why?!',
    'vec3 MyAESFilmicToneMapping(vec3 color) {',
      'return clamp((color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14), 0.0, 1.0);',
    '}',

    '#if($caustics_enabled)',
      'float causticShader(vec2 uv, float t){',
        'float tModified = (t / 20.0);',
        'vec2 uv1 = uv + vec2(0.8, 0.1) * tModified;',
        'vec2 uv2 = uv - vec2(0.2, 0.7) * tModified;',
        'float aSample1 = texture(causticMap, uv1).r;',
        'float aSample2 = texture(causticMap, uv2).g;',
        'return min(aSample1, aSample2);',
      '}',
    '#endif',

    '//Converted from the Minstrel Water Engine',
    '/*',
    'MIT License',

    'Copyright (c) 2018 Jingping Yu',

    'Permission is hereby granted, free of charge, to any person obtaining a copy',
    'of this software and associated documentation files (the "Software"), to deal',
    'in the Software without restriction, including without limitation the rights',
    'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
    'copies of the Software, and to permit persons to whom the Software is',
    'furnished to do so, subject to the following conditions:',

    'The above copyright notice and this permission notice shall be included in all',
    'copies or substantial portions of the Software.',

    'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
    'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
    'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
    'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
    'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,',
    'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE',
    'SOFTWARE.',
    '*/',
    '#if($foam_enabled)',
      '//Foam amount is now pre-computed in the FFT normal map alpha channel',
    '#endif',

    '#if($atmospheric_perspective_enabled)',
      '//Atmospheric perspective for ground-level surfaces.',
      '//Uses distance-based extinction with LUT-sampled multi-scattered inscattering.',
      '//At the same height: S(A->B) = S(A->inf) * (1 - T(A->B))',
      'vec3 applyAtmosphericPerspective(vec3 color, vec3 worldPos){',
        'vec3 worldViewDir = normalize(worldPos - cameraPosition);',
        "//Convert view direction from THREE.js world space to a-starry-sky's coordinate",
        '//system. Sun world direction = (-sp.z, sp.y, -sp.x) from quadOffset, so the',
        '//inverse transform from world to sky coords is: skyDir = (-world.z, world.y, -world.x)',
        'vec3 viewDir = vec3(-worldViewDir.z, worldViewDir.y, -worldViewDir.x);',
        'float dist = length(worldPos - cameraPosition) * METERS_TO_KM * atmDistanceScale;',

        '//Distance-based extinction along the camera-to-surface path',
        'vec3 extinction = exp(-(RAYLEIGH_BETA + EARTH_MIE_BETA_EXTINCTION) * dist);',

        '//Attenuate surface color',
        'color *= extinction;',

        '//LUT coordinates for inscattering lookup',
        'float viewCosZenith = max(viewDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscattering from 3D LUTs',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(viewDir, atmSunPosition);',
        'vec3 fogSun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun)',
                    '* (1.0 - extinction);',

        '//Moon inscattering from 3D LUTs',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(viewDir, atmMoonPosition);',
        'vec3 fogMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon)',
                     '* (1.0 - extinction);',

        'return color + fogSun + fogMoon;',
      '}',
    '#endif',

    'void main(){',
      'mat3 instanceMatrixMat3 = mat3(vInstanceMatrix[0].xyz, vInstanceMatrix[1].xyz, vInstanceMatrix[2].xyz );',
      'mat3 modelMatrixMat3 = mat3(vModelMatrix[0].xyz, vModelMatrix[1].xyz, vModelMatrix[2].xyz );',
      'vec2 cameraOffset = vec2(cameraPosition.x, cameraPosition.z);',

      'vec2 uvOffset = (vUv * sizeOfOceanPatch + cameraOffset) / sizeOfOceanPatch;',
      'vec3 displacement = texture2D(displacementMap, uvOffset).xyz;',
      'displacement.x *= -1.0;',
      'displacement.z *= -1.0;',
      'vec3 offsetPosition = vPosition + displacement;',
      'float height = (offsetPosition.y  + linearScatteringHeightOffset) / linearScatteringTotalScatteringWaveHeight;',
      'vec4 worldPosition = vModelMatrix * vInstanceMatrix * vec4(offsetPosition, 1.0);',
      'vec2 exclusionPosition = 0.5 * (((worldPosition.xz - cameraPosition.xz) / vec2(1024.0)) + 1.0);',
      'exclusionPosition = vec2(exclusionPosition.x, 1.0 - exclusionPosition.y);',
      'if(exclusionPosition.x < 1.0 && exclusionPosition.x > 0.0 && exclusionPosition.y < 1.0 && exclusionPosition.y > 0.0){',
        'vec2 discardHeightData = texture2D(exclusionMap, exclusionPosition).ga;',
        'float discardHeight = discardHeightData.x;',
        'if((discardHeightData.y > 0.5) && worldPosition.y > discardHeight){',
          'discard;',
        '}',
      '}',
      'float distanceToWorldPosition = distance(worldPosition.xyz, cameraPosition.xyz);',
      'float LOD = pow(2.0, clamp(7.0 - (distanceToWorldPosition / (sizeOfOceanPatch * 7.0)), 2.0, 7.0));',

      '//Sample the pre-computed FFT normal map (computed via central differences on displacement in a GPU pass)',
      '//Fade normal detail proportional to mesh LOD to avoid grainy aliasing',
      'float normalLodFactor = clamp(1.0 - distanceToWorldPosition / (sizeOfOceanPatch * 7.0), 0.0, 1.0);',
      'float normalDetailFade = mix(0.15, 1.0, normalLodFactor * normalLodFactor);',
      'vec4 fftNormalSample = texture2D(fftNormalMap, uvOffset);',
      'vec3 displacedNormal = fftNormalSample.xyz * 2.0 - 1.0;',
      'displacedNormal = normalize(mix(vec3(0.0, 1.0, 0.0), displacedNormal, normalDetailFade));',
      '//The FFT normal is in object space (x, y, z) - swizzle to match expected xzy convention',
      'displacedNormal = displacedNormal.xzy;',

      '//Get the reflected and refracted information of the scene',
      'vec2 smallNormalMapOffset = (((vUv * 2.0) * (sizeOfOceanPatch / 2.0) + cameraOffset + t * smallNormalMapVelocity) / (sizeOfOceanPatch / 2.0));',
      'vec2 largeNormalMapOffset = (((vUv * 1.0) * (sizeOfOceanPatch / 1.0) + cameraOffset - t * largeNormalMapVelocity) / (sizeOfOceanPatch / 1.0));',
      'vec3 smallNormalMap = texture2D(smallNormalMap, smallNormalMapOffset).xyz;',
      'smallNormalMap = 2.0 * smallNormalMap - 1.0;',
      'float smallNormalMapFadeout = clamp((500.0 - distanceToWorldPosition) / 250.0, 0.0, 1.0);',
      'smallNormalMap.x *= smallNormalMapStrength * smallNormalMapFadeout;',
      'smallNormalMap.y *= smallNormalMapStrength * smallNormalMapFadeout;',
      'smallNormalMap = normalize(smallNormalMap);',
      'smallNormalMap = (smallNormalMap + 1.0) * 0.5;',
      'vec3 largeNormalMap = texture2D(largeNormalMap, largeNormalMapOffset).xyz;',
      'largeNormalMap = 2.0 * largeNormalMap - 1.0;',
      'float largeNormalMapFadeout = clamp((3000.0 - distanceToWorldPosition) / 2500.0, 0.0, 1.0);',
      'largeNormalMap.x *= largeNormalMapStrength * largeNormalMapFadeout;',
      'largeNormalMap.y *= largeNormalMapStrength * largeNormalMapFadeout;',
      'largeNormalMap = normalize(largeNormalMap);',
      'largeNormalMap = (largeNormalMap + 1.0) * 0.5;',
      'vec3 combinedNormalMap = combineNormals(smallNormalMap, largeNormalMap);',
      '#if($foam_enabled)',
        'vec3 foamNormal = texture2D(foamNormalMap, smallNormalMapOffset).xyz;',
        'foamNormal = 2.0 * foamNormal - 1.0;',
        'float foamAmount = fftNormalSample.a;',
        'vec2 foamPosition = 0.5 * (((worldPosition.xz - cameraPosition.xz) / vec2(2048.0)) + 1.0);',
        'foamPosition = vec2(foamPosition.x, 1.0 - foamPosition.y);',
        'if(foamPosition.x < 1.0 && foamPosition.x > 0.0 && foamPosition.y < 1.0 && foamPosition.y > 0.0){',
          'vec2 foamHeightData = texture2D(foamRenderMap, foamPosition).ga;',
          'if((foamHeightData.y > 0.5)){',
            'foamAmount = max(foamAmount, 1.0 - abs(clamp(worldPosition.y - foamHeightData.x - 10.0, 0.0, 10.0) / 10.0));',
          '}',
        '}',
        'foamNormal.x *= 0.5 * foamAmount * largeNormalMapFadeout;',
        'foamNormal.y *= 0.5 * foamAmount * largeNormalMapFadeout;',
        'foamNormal = normalize(foamNormal);',
        'foamNormal = (foamNormal + 1.0) * 0.5;',
        'combinedNormalMap = combineNormals(combinedNormalMap, foamNormal);',
      '#endif',
      'vec3 normalizedDisplacedNormalMap = (normalize(displacedNormal) + vec3(1.0)) * 0.5;',
      'combinedNormalMap = combineNormals(normalizedDisplacedNormalMap, combinedNormalMap);',
      'combinedNormalMap = combinedNormalMap * 2.0 - vec3(1.0);',
      'combinedNormalMap = normalize(combinedNormalMap);',
      'combinedNormalMap = combinedNormalMap.xzy;',

      'vec3 normalizedViewVector = normalize(worldPosition.xyz - cameraPosition);',
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',

      "//Planar reflection: project world position through the reflection camera's VP matrix",
      'vec4 reflectionClipPos = reflectionViewProjectionMatrix * worldPosition;',
      'vec2 reflectionUV = reflectionClipPos.xy / reflectionClipPos.w * 0.5 + 0.5;',
      'reflectionUV += combinedNormalMap.xz * 0.02; //Distort by surface normal',
      'reflectionUV = clamp(reflectionUV, 0.001, 0.999);',
      'vec3 reflectedLight = texture2D(reflectionTexture, reflectionUV).rgb;',
      '//At the horizon the reflection projection degenerates and samples black.',
      '//Detect near-black reflection samples and replace with a sky-area sample',
      '//from the reflection texture to avoid a dark seam at the horizon.',
      'float reflBrightness = dot(reflectedLight, vec3(0.299, 0.587, 0.114));',
      'vec3 horizonFallback = texture2D(reflectionTexture, vec2(0.5, 0.85)).rgb;',
      'reflectedLight = mix(reflectedLight, horizonFallback, 1.0 - smoothstep(0.0, 0.005, reflBrightness));',

      '//Screen-space refraction',
      '//Distort UVs based on the surface normal to simulate refraction',
      'vec2 distortion = combinedNormalMap.xz * 0.03;',
      'vec2 refractedUV = clamp(screenUV + distortion, 0.001, 0.999);',

      '//Sample refraction color and depth',
      'float refractionDepthRaw = texture2D(refractionDepthTexture, refractedUV).r;',
      'float refractionDepthLinear = linearizeDepth(refractionDepthRaw);',
      'float surfaceDepthLinear = linearizeDepth(gl_FragCoord.z);',

      '//If distorted UV samples something closer than the water surface, fall back to undistorted',
      'if(refractionDepthLinear < surfaceDepthLinear - 0.5){',
        'refractedUV = screenUV;',
        'refractionDepthRaw = texture2D(refractionDepthTexture, refractedUV).r;',
        'refractionDepthLinear = linearizeDepth(refractionDepthRaw);',
      '}',

      'vec3 refractedLight = texture2D(refractionColorTexture, refractedUV).rgb;',

      '//Reconstruct world-space position from refraction depth',
      'vec4 clipPos = vec4(refractedUV * 2.0 - 1.0, refractionDepthRaw * 2.0 - 1.0, 1.0);',
      'vec4 viewPos = inverseProjectionMatrix * clipPos;',
      'viewPos /= viewPos.w;',
      'vec3 pointXYZ = (inverseViewMatrix * viewPos).xyz;',

      '//Use the reconstructed Y position to distinguish underwater vs above-water geometry',
      'float distanceToPoint;',
      'if(pointXYZ.y < baseHeightOffset && refractionDepthLinear > surfaceDepthLinear){',
        '//Underwater geometry visible - use actual depth difference for scattering',
        'distanceToPoint = min(refractionDepthLinear - surfaceDepthLinear, 100.0);',
      '}',
      'else{',
        '//Above-water geometry or sky - treat as deep water',
        '//Keep the scene color so scattering can tint it (matches old cube map behavior)',
        'distanceToPoint = 100.0;',
      '}',

      'vec3 normalizedTransmittancePercentColor = normalize(lightScatteringAmounts);',
      'vec3 percentOfSourceLight = clamp(exp(-2.25 * distanceToPoint / (lightScatteringAmounts)), 0.0, 1.0);',
      'refractedLight = sRGBToLinear(vec4(refractedLight, 1.0)).rgb;',
      '//Increasing brightness with height inspired by, https://80.lv/articles/tutorial-ocean-shader-with-gerstner-waves/',
      'float lightMag = length(brightestDirectionalLight);',
      'vec3 normalizedLightIntensity = lightMag > 0.001 ? brightestDirectionalLight / lightMag : vec3(0.0);',
      'vec3 inscatterLight = pow(max(height, 0.0) * length(vec3(1.0) - percentOfSourceLight) * pow(normalizedTransmittancePercentColor, vec3(2.5)) * normalizedLightIntensity, gamma);',

      "//Apply Schlick's approximation for the fresnel amount",
      '//https://graphicscompendium.com/raytracing/11-fresnel-beer',

      'float cosTheta = clamp(dot(combinedNormalMap, -normalizedViewVector), 0.0, 1.0);',
      'float fresnelFactor = r0 + (1.0 - r0) * pow(1.0 - cosTheta, 5.0);',
      'reflectedLight = sRGBToLinear(vec4(reflectedLight, 1.0)).rgb;',

      '#if($caustics_enabled)',
        '//Calculate caustic lighting using reconstructed world position',
        'float causticLightingR = causticShader(0.01 * pointXYZ.xz + 0.005, t);',
        'float causticLightingG = causticShader(0.01 * pointXYZ.xz, t);',
        'float causticLightingB = causticShader(0.01 * pointXYZ.xz - 0.005, t);',
        'vec3 causticLighting = causticIntensityMultiplier * 20.0 * vec3(causticLightingR, causticLightingG, causticLightingB);',
        'if(distance(cameraPosition, pointXYZ.xyz) > 2500.0){',
          'causticLighting = vec3(1.0);',
        '}',
        'refractedLight *= (causticLighting);',
      '#endif',
      'refractedLight *= percentOfSourceLight;',

      '//Calculate specular lighting and surface lighting',
      'vec3 directionalSurfaceLighting = normalizedLightIntensity * max(dot(combinedNormalMap, -brightestDirectionalLightDirection), 0.0);',
      'vec3 reflectedViewDir = reflect(normalizedViewVector, combinedNormalMap);',
      'vec3 specular = 1.7 * normalizedLightIntensity * clamp((dot(reflectedViewDir, -brightestDirectionalLightDirection) - 0.995) / 0.005, 0.0, 1.0);',

      '//Total light',
      'vec3 totalLight = specular + (2.0 / 255.0) * directionalSurfaceLighting + (253.0 / 255.0) * ((inscatterLight + refractedLight) * (1.0 - fresnelFactor) + reflectedLight * fresnelFactor);',
      '#if($foam_enabled)',
        'float foamOpacity = foamAmount * texture2D(foamOpacityMap, smallNormalMapOffset).r;',
        'vec3 foamLight = texture2D(foamDiffuseMap, smallNormalMapOffset).rgb;',
        'totalLight = mix(totalLight, 2.0 * directionalSurfaceLighting * foamLight, (foamOpacity * foamAmount));',
      '#endif',

      '#if($atmospheric_perspective_enabled)',
        'totalLight = applyAtmosphericPerspective(totalLight, worldPosition.xyz);',
      '#endif',

      'gl_FragColor = linearTosRGB(vec4(MyAESFilmicToneMapping(totalLight), 1.0));',

      '//Blue noise dithering to break banding (same technique as a-starry-sky)',
      'float goldenRatio = 1.61803398875;',
      'float framePhase = fract(blueNoiseTime * 0.001);',
      'ivec2 temporalOffset = ivec2(',
        '128.0 * fract(framePhase * goldenRatio),',
        '128.0 * fract(framePhase * goldenRatio * goldenRatio)',
      ');',
      'gl_FragColor.rgb += (texelFetch(blueNoiseTexture, (ivec2(gl_FragCoord.xy) + temporalOffset) % 128, 0).rgb - vec3(0.5)) / vec3(128.0);',

      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',
    ];

    let updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedCode = originalGLSL[i];
      updatedCode = updatedCode.replace(/\$foam_enabled/g, foamEnabled ? '1' : '0');
      updatedCode = updatedCode.replace(/\$caustics_enabled/g, causticsEnabled ? '1' : '0');
      updatedCode = updatedCode.replace(/\$atmospheric_perspective_enabled/g, atmosphericPerspectiveEnabled ? '1' : '0');
      //Inject atmosphere parameterization functions where the marker is
      if(atmosphericPerspectiveEnabled && atmosphereFunctionsGLSL && updatedCode.indexOf('//ATMOSPHERE_FUNCTIONS_INJECTION_POINT') !== -1){
        updatedCode = atmosphereFunctionsGLSL;
      }
      updatedLines.push(updatedCode);
    }

    return updatedLines.join('\n');
  },

  vertexShader: [
    'precision highp float;',

    'attribute vec3 tangent;',
    'attribute vec3 bitangent;',

    'varying vec2 vUv;',
    'varying vec3 vPosition;',
    'varying vec3 vTangent;',
    'varying vec3 vBitangent;',
    'varying vec3 vInView;',
    'varying mat4 vInstanceMatrix;',
    'varying mat4 vModelMatrix;',
    'varying mat3 vNormalMatrix;',

    'uniform float sizeOfOceanPatch;',
    'uniform sampler2D displacementMap;',
    'uniform float linearScatteringHeightOffset;',
    'uniform float linearScatteringTotalScatteringWaveHeight;',

    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_vertex>',
    '#endif',

    'vec2 vec2Modulo(vec2 inputUV){',
        'return (inputUV - floor(inputUV));',
    '}',

    '//Hash-based value noise to break FFT tiling repetition at distance',
    'float hash(vec2 p){',
      'return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);',
    '}',

    'float valueNoise(vec2 p){',
      'vec2 i = floor(p);',
      'vec2 f = fract(p);',
      'f = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);',
      'float a = hash(i);',
      'float b = hash(i + vec2(1.0, 0.0));',
      'float c = hash(i + vec2(0.0, 1.0));',
      'float d = hash(i + vec2(1.0, 1.0));',
      'return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);',
    '}',

    'float fbmNoise(vec2 p){',
      'float v = 0.0;',
      'v += 0.5 * valueNoise(p);',
      'v += 0.25 * valueNoise(p * 2.03);',
      'v += 0.125 * valueNoise(p * 4.01);',
      'return v / 0.875;',
    '}',

    'void main() {',
      '//Set up our displacement map',
      'vec3 offsetPosition = position;',
      'mat3 instanceMatrixMat3 = mat3(instanceMatrix[0].xyz, instanceMatrix[1].xyz, instanceMatrix[2].xyz );',
      'mat3 modelMatrixMat3 = mat3(modelMatrix[0].xyz, modelMatrix[1].xyz, modelMatrix[2].xyz );',

      'vec2 cameraOffset = vec2(cameraPosition.x, cameraPosition.z);',
      'vec4 worldPositionOfVertex = (modelMatrix * instanceMatrix * vec4(position, 1.0));',
      'float distanceToVertex = distance(cameraPosition.xyz, worldPositionOfVertex.xyz);',
      'vec2 uvOffset = (uv * sizeOfOceanPatch + cameraOffset) / sizeOfOceanPatch;',
      '//Fade FFT displacement proportional to mesh LOD to prevent vertex-density aliasing',
      '//Matches LOD curve: full detail near camera, tapers as tessellation drops',
      'float lodFactor = clamp(1.0 - distanceToVertex / (sizeOfOceanPatch * 7.0), 0.0, 1.0);',
      'float displacementFade = mix(0.15, 1.0, lodFactor * lodFactor);',
      'vec3 displacement = texture2D(displacementMap, uvOffset).xyz * displacementFade;',
      'displacement.x *= -1.0;',
      'displacement.z *= -1.0;',

      '//Add procedural noise that fades in with distance to break FFT tiling repetition',
      'float noiseFadeIn = smoothstep(200.0, 1500.0, distanceToVertex);',
      'float noiseHeight = (fbmNoise(worldPositionOfVertex.xz * 0.003) - 0.5) * 2.0;',
      'displacement.y += noiseHeight * noiseFadeIn * linearScatteringTotalScatteringWaveHeight * 0.15;',

      'offsetPosition += displacement;',

      '//Set up our varyings',
      'vUv = uv;',
      'vTangent = tangent;',
      'vBitangent = bitangent;',
      'vPosition = position;',
      '//From https://stackoverflow.com/questions/59492385/angle-between-view-vector-and-normal',
      'vec4 posInView = (modelViewMatrix * instanceMatrix * vec4(offsetPosition, 1.0));',
      'posInView /= posInView[3];',
      'vInView = normalize(-posInView.xyz);',
      'vInstanceMatrix = instanceMatrix;',
      'vModelMatrix = modelMatrix;',
      'vNormalMatrix = normalMatrix;',

      '//Add support for three.js fog',
      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_vertex>',
      '#endif',

      'gl_Position = projectionMatrix * viewMatrix * modelMatrix * instanceMatrix * vec4(offsetPosition, 1.0);',
    '}',
  ].join('\n'),
};
