//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
//
//Waterfall mist (volumetric). The SHARED block is replaced at init by the flowing-water
//material's own uniform objects (WaterfallMistPass.init aliases them, as the sheet does), so the
//mist is lit by exactly the sun, sky, shadow and atmosphere the fall and the creek are. The
//defaults here only matter if the mist is ever drawn without a flowing surface.
ARestlessOcean.Materials.Ocean.waterfallMistMaterial = {
  uniforms: {
    //SHARED with the flowing-water material
    brightestDirectionalLight: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    brightestDirectionalLightDirection: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    skyAmbientColor: {value: new THREE.Vector3(0.3, 0.4, 0.5)},
    t: {value: 0.0},
    //The land's skyline and sky visibility (field/land-light.js LandLight.update, every frame): SHARED, aliased from the flowing material.
    landHorizonTex: {value: null},
    landHorizonAtlas: {value: new THREE.Vector4(1, 1, 1, 1)},
    landHorizonFrame: {value: new THREE.Vector4(0, 0, 1, 1)},
    landHorizonParams: {value: new THREE.Vector2(24, 0.03)},
    landGroundTex: {value: null},
    landGroundFrame: {value: new THREE.Vector4(0, 0, 1, 1)},
    landLightOn: {value: new THREE.Vector2(0, 0)},
    //SHARED: 1 = the sky irradiance gets the Lambert 1/PI (physical); 0 = the old PI x fill (oceanGrid.ambientPiFix).
    ambientPiFix: {value: 1.0},
    //The falls' shadow (passes/waterfall-shadow-pass.js writeUniforms): SHARED.
    fallShadowMap: {value: null},
    fallShadowMatrix: {value: new THREE.Matrix4()},
    fallShadowParams: {value: new THREE.Vector2(0, 0.005)},
    sunShadowMap: {value: null},
    sunShadowMatrix: {value: new THREE.Matrix4()},
    sunShadowMapSize: {value: new THREE.Vector2(2048.0, 2048.0)},
    sunShadowRadius: {value: 1.0},
    sunShadowBias: {value: 0.0},
    sunShadowEnabled: {value: 0},
    refractionDepthTexture: {value: null},
    inverseProjectionMatrix: {value: new THREE.Matrix4()},
    screenResolution: {value: new THREE.Vector2(1920.0, 1080.0)},
    underwaterFactor: {value: 0.0},
    atmosphereTransmittance: {value: null},
    atmosphereMieInscattering: {value: null},
    atmosphereRayleighInscattering: {value: null},
    atmSunPosition: {value: new THREE.Vector3(0.0, 1.0, 0.0)},
    atmMoonPosition: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    atmSunHorizonFade: {value: 1.0},
    atmMoonHorizonFade: {value: 0.0},
    atmScatteringSunIntensity: {value: 1.0},
    atmScatteringMoonIntensity: {value: 0.0},
    atmMoonLightColor: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    atmCameraHeight: {value: 0.0},
    atmDistanceScale: {value: 1.0},

    //Scene fog (see waterfall-sheet-template.txt: the material is fog:true)
    fogNear: {value: 1.0},
    fogFar: {value: 1000.0},
    fogDensity: {value: 0.00025},
    fogColor: {value: new THREE.Color()},
    uwSunDir: {value: new THREE.Vector3(0.0, -1.0, 0.0)},

    //The mist's own. FUDGE: all look choices, none a plume model. Foam in the middle of the fall
    //(dense, bright, round lumps with some stretch), haze toward the landing (thin, soft, big puffs).
    uMistDensity: {value: 1.0},
    uFoamDensity: {value: 3.0},
    uHazeDensity: {value: 1.0},
    uScaleRef: {value: 10.0},
    uFoamScale: {value: 0.55},
    uHazeScale: {value: 1.6},
    uFoamRate: {value: 10.0},
    uHazeRate: {value: 4.5},
    uErodeFoam: {value: 0.38},
    uErodeHaze: {value: 0.45},
    uErodeSoft: {value: 0.22},
    uRadialPow: {value: 1.3},
    uFadeIn: {value: 0.12},
    uFadeOutStart: {value: 0.75},
    uFadeOutEnd: {value: 1.0},
    uHazeStart: {value: 0.4},
    uMinBody: {value: 0.55},
    uAerationLo: {value: 0.15},
    uAerationHi: {value: 0.55},
    uGroundFade: {value: 0.4},
    uSteps: {value: 24.0},
    uLightSteps: {value: 3.0},
    uLightLength: {value: 2.0},
    uAbsorption: {value: 1.0},
    uPhaseG: {value: 0.7},
    //Step 4b: Wrenninge multiple scattering (1) or the old stand-in (0); the diffusion floor's weight.
    uMultiScatter: {value: 1.0},
    uDiffusion: {value: 0.5},
    uAmbient: {value: 1.0},
    //The night gate (the sea spray's): the sky fill falls to uNightAmbient of itself as the sun sets, so white
    //water over a dark sea does not glow. uSunElevation (sin of the TRUE solar elevation) is set every frame.
    uSunElevation: {value: 1.0},
    uNightAmbient: {value: 0.07},
    uSunGain: {value: 1.0},
    uAlbedoFoam: {value: new THREE.Vector3(0.97, 0.98, 1.0)},
    uAlbedoHaze: {value: new THREE.Vector3(0.86, 0.9, 0.97)},
    uMaxChord: {value: 14.0},
    uSoftRange: {value: 0.6},
    uSheetOcclusion: {value: 0.6},
    uMistOpacity: {value: 1.0},
    uDebugMode: {value: 0},
  },

  //Built like the sheet's (waterfall-sheet-template.txt): $atmospheric_perspective_enabled is
  //substituted, and with it on the atmosphere functions replace the injection marker line.
  //WaterfallMistPass rebuilds it when atmospheric perspective becomes ready.
  fragmentShader: function(atmosphericPerspectiveEnabled, atmosphereFunctionsGLSL){
    const originalGLSL = [
    'precision highp float;',

    '//Waterfall mist fragment stage: a raymarched volume inside the CONES ARestlessOcean.WaterfallMistHull',
    "//builds along the water's paths (a closed round tube per few strands and per free-fall run: narrow at",
    '//the lip, opening downward, running on a little way over the pool past the landing).',
    '//',
    '//WHAT IT DRAWS. Each cone is closed and wound outward; the material culls its FRONT faces, so each',
    '//fragment is the point X where a view ray LEAVES the cone. From X the stage marches back toward the',
    "//camera (never past it: the camera may be inside) over the length of the ray's chord through the cone,",
    "//and integrates the volume front to back. The chord is exact for a cylinder about the cone's axis.",
    '//',
    "//THE DENSITY is a function of the distance to the cone's AXIS over its radius, not of any frame that",
    "//follows the ribbon, so it is zero on the cone's wall by construction (no flat sheets of mist standing",
    '//in the air) and the cones cannot twist:',
    '//  radial    (1 - x^2)^p, x = distance to the axis / radius',
    '//  along     u runs 0 at the lip, 1 at the landing, 1..2 over the run-out. It fades the cone in below',
    '//            the lip (uFadeIn) and out over the run-out, and sets WHAT the mist is:',
    '//              FOAM in the middle of the fall: dense, bright, round lumps with some stretch along the',
    '//                flow, so it reads as foam blasting down, riding the water at its own speed;',
    '//              HAZE toward the landing (uHazeStart..1) and over the pool: thin, soft, large round',
    '//                puffs, bluer, drifting out.',
    "//            u is measured per SAMPLE (axial position / the run's length), so one tall cone changes",
    '//            from foam to haze along its own length, and a short fall is all foam with a short haze tail.',
    "//  noise     3D value noise laid out in the water's TIME OF FLIGHT along the flow (so it rides the water at",
    "//            its real speed and its cells stretch as the jet accelerates, like the sheet's grain) and in",
    '//            metres across it, periodic in time (it loops, no seam), shaped by smoothstep so the lumps',
    '//            have defined, billowy edges and the thin rim erodes into clumps.',
    "//  ground    nothing below the landing's height: the cone is allowed to dip under the pool, it just",
    '//            has no density there (it is not clamped to the floor, which made flat walls).',
    '//',
    '//THE LIGHT. Each sample marches a few steps toward the sun for its own SELF-SHADOWING (Beer-Lambert,',
    '//with a cheap multiple-scatter floor so the shaded side is not black), takes a dual-lobe Henyey-',
    "//Greenstein phase (forward-scattering: a backlit fall glows), the scene's sun shadow map and the sky's",
    "//ambient. Units are the sheet's: a white Lambert surface under the sun is INV_PI * brightestDirectionalLight.",
    '//',
    '//OCCLUSION. No depth test (the cones straddle the curtain, whose own depth would hide the half of',
    '//the mist in front of it). Instead (1) the refraction G-buffer (terrain, objects) clips the march, soft',
    '//by uSoftRange, and (2) the curtain is treated as the mostly opaque plane it is: samples behind it,',
    '//inside its width and alongside the falling part of the cone, are dimmed (uSheetOcclusion).',
    '//',
    '//ATMOSPHERE and fog exactly as the sheet does them (see waterfall-sheet.glsl).',

    'uniform vec3 brightestDirectionalLight;',
    'uniform vec3 brightestDirectionalLightDirection;   //from the sun TOWARD the scene',
    'uniform vec3 skyAmbientColor;',
    'uniform float t;',

    'uniform sampler2D sunShadowMap;',
    'uniform mat4 sunShadowMatrix;',
    'uniform vec2 sunShadowMapSize;',
    'uniform float sunShadowRadius;',
    'uniform float sunShadowBias;',
    'uniform int sunShadowEnabled;',

    'uniform sampler2D refractionDepthTexture;',
    'uniform mat4 inverseProjectionMatrix;',
    'uniform vec2 screenResolution;',
    'uniform float underwaterFactor;',

    'uniform float uMistDensity;      //global multiplier on the extinction below',
    'uniform float uFoamDensity;      //1/m extinction at the core of the foam',
    'uniform float uHazeDensity;      //... and of the haze',
    'uniform float uScaleRef;         //m: the run length at which the lump sizes below apply; shorter falls get finer lumps, taller ones coarser (sqrt, within 0.5 .. 1.6)',
    'uniform float uFoamScale;        //m per noise cell in the foam (at uScaleRef)',
    'uniform float uHazeScale;        //... in the haze',
    "uniform float uFoamRate;         //foam noise cells per second of the water's flight along the flow (a cell is that long x the water's speed: streaks that stretch as it accelerates)",
    'uniform float uHazeRate;         //... in the haze (fewer, and the water is slower there: rounder puffs)',
    'uniform float uErodeFoam;        //0..1: noise level below which the foam is carved away',
    'uniform float uErodeHaze;        //... and the haze',
    "uniform float uErodeSoft;        //width of the carve's edge (small: lumps with defined edges)",
    'uniform float uRadialPow;        //exponent of the radial profile (1: soft cone, higher: dense core, soft rim)',
    'uniform float uFadeIn;           //u over which the cone fades in below the lip',
    'uniform float uFadeOutStart;     //u where the mist starts to fade out toward the landing (smoothly: no chop where the cones end)',
    'uniform float uFadeOutEnd;       //u where it is gone (1: the landing; more only with the run-out on)',
    'uniform float uHazeStart;        //u where foam begins to give way to haze (it is all haze by the landing)',
    'uniform float uMinBody;          //least fraction of full density at low aeration',
    'uniform float uAerationLo;       //aeration where the body starts to rise above uMinBody',
    'uniform float uAerationHi;       //aeration where it is full',
    "uniform float uGroundFade;       //m above the landing's height over which the mist fades in",
    'uniform float uSteps;            //view-ray steps',
    'uniform float uLightSteps;       //sun-ray steps',
    'uniform float uLightLength;      //m the sun ray reaches',
    "uniform float uAbsorption;       //sun-ray extinction as a multiple of the view's",
    'uniform float uPhaseG;           //forward lobe of the phase function',
    'uniform float uMultiScatter;     //1: Wrenninge octaves + diffusion floor (step 4b); 0: the old two-exponential stand-in',
    "uniform float uDiffusion;        //the multiple-scatter diffusion floor's weight (isotropic units)",
    'uniform float uAmbient;          //sky fill',
    'uniform float ambientPiFix;   //1: the sky irradiance gets the Lambert 1/PI a-land and three apply (physical); 0: the old, PI x too bright sky fill. A/B, 2026-10-02',
    'uniform float uSunElevation;     //sin of the TRUE solar elevation (the moon is the brightest light at night)',
    "uniform float uNightAmbient;     //the sky fill's floor at night, as a share of itself (OceanSplash nightAmbient)",
    'uniform float uSunGain;          //sun scatter gain',
    'uniform vec3 uAlbedoFoam;        //single-scatter albedo of the foam',
    'uniform vec3 uAlbedoHaze;        //... and of the haze',
    'uniform float uMaxChord;         //m, longest run marched through a cone',
    'uniform float uSoftRange;        //m of depth over which the mist fades into the ground',
    'uniform float uSheetOcclusion;   //0..1: how opaque the curtain is to the mist behind it',
    'uniform float uMistOpacity;',
    'uniform int uDebugMode;',

    'varying vec3 vWorldPos;',
    "varying vec3 vCenter;  //the cone's axis point at this fragment",
    "varying vec3 vN;       //the CURTAIN's normal here (for the occlusion only)",
    "varying vec3 vT;       //the cone's axis direction (down the flow)",
    "varying vec3 vA;       //the curtain's across direction (for the occlusion only)",
    "varying vec4 vMistA;   //across (m from the curtain's middle), u, radius, seed",
    "varying vec4 vMistB;   //aeration, run length (m), the water's speed (m/s), curtain half-width",
    "varying vec3 vEnd;     //the run's landing point",
    "varying float vTau;    //the water's time of flight at this fragment (s)",
    'varying float vViewDepth;',

    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_fragment>',
    '#endif',
    '#if($atmospheric_perspective_enabled)',
      'precision highp sampler3D;',
      'uniform sampler2D atmosphereTransmittance;',
      'uniform sampler3D atmosphereMieInscattering;',
      'uniform sampler3D atmosphereRayleighInscattering;',
      'uniform vec3 atmSunPosition;',
      'uniform vec3 atmMoonPosition;',
      'uniform float atmSunHorizonFade;',
      'uniform float atmMoonHorizonFade;',
      'uniform float atmScatteringSunIntensity;',
      'uniform float atmScatteringMoonIntensity;',
      'uniform vec3 atmMoonLightColor;',
      'uniform float atmCameraHeight;',
      'uniform float atmDistanceScale;',

      '//ATMOSPHERE_FUNCTIONS_INJECTION_POINT',

      '//Lifted verbatim from waterfall-sheet.glsl (keep in step). The injected functions are the LUT',
      '//helpers only; the sheet and the creek each define their own applyAtmosphericPerspective on top.',
      '//Atmospheric perspective for ground-level surfaces.',
      '//Uses distance-based extinction with LUT-sampled multi-scattered inscattering.',
      '//At the same height: S(A->B) = S(A->inf) * (1 - T(A->B))',
      'vec3 applyAtmosphericPerspective(vec3 color, vec3 worldPos){',
        'vec3 worldViewDir = normalize(worldPos - cameraPosition);',
        "//Convert view direction from THREE.js world space to a-starry-sky's coordinate",
        '//system. Sun world direction = (-sp.z, sp.y, -sp.x) from quadOffset, so the',
        '//inverse transform from world to sky coords is: skyDir = (-world.z, world.y, -world.x)',
        'vec3 viewDir = vec3(-worldViewDir.z, worldViewDir.y, -worldViewDir.x);',
        'float dist = length(worldPos - cameraPosition) * METERS_TO_KM * atmDistanceScale;',

        '//Distance-based extinction along the camera-to-surface path',
        'vec3 extinction = exp(-(RAYLEIGH_BETA + EARTH_MIE_BETA_EXTINCTION) * dist);',

        '//Attenuate surface color',
        'color *= extinction;',

        '//LUT coordinates for inscattering lookup',
        'float viewCosZenith = max(viewDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscattering from 3D LUTs',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(viewDir, atmSunPosition);',
        'vec3 fogSun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun)',
                    '* (1.0 - extinction);',

        '//Moon inscattering from 3D LUTs',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(viewDir, atmMoonPosition);',
        'vec3 fogMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon)',
                     '* (1.0 - extinction);',

        'return color + fogSun + fogMoon;',
      '}',
    '#endif',

    '//(No PI of our own: the injected atmosphere functions declare one; a second is a link error.)',
    'const float INV_PI = 0.31830988618;',
    'const int MAX_STEPS = 64;',
    'const int MAX_LIGHT_STEPS = 8;',

    '//── Copied from waterfall-sheet.glsl (keep in step) ───────────────────────────',
    "//Applied to AP's output as the sheet does: the sheet and its mist then tone-map alike.",
    'vec4 linearTosRGB(vec4 value){',
      'return vec4(mix(pow(value.rgb, vec3(0.41666)) * 1.055 - vec3(0.055), value.rgb * 12.92, vec3(lessThanEqual(value.rgb, vec3(0.0031308)))), value.a);',
    '}',
    'vec3 aroAESFilmicToneMapping(vec3 color){',
      'return clamp((color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14), 0.0, 1.0);',
    '}',
    '//──────────────────────────────────────────────────────────────────────────────',

    "//── Noise: ocean-splash.glsl's hash3 / vnoise3 ────────────────────────────────",
    'float hash3(vec3 p){',
      'p = fract(p * 0.3183099 + 0.1);',
      'p *= 17.0;',
      'return fract(p.x * p.y * p.z * (p.x + p.y + p.z));',
    '}',
    'float vnoise3(vec3 x){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'return mix(mix(mix(hash3(i + vec3(0.0, 0.0, 0.0)), hash3(i + vec3(1.0, 0.0, 0.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 0.0)), hash3(i + vec3(1.0, 1.0, 0.0)), f.x), f.y),',
                 'mix(mix(hash3(i + vec3(0.0, 0.0, 1.0)), hash3(i + vec3(1.0, 0.0, 1.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 1.0)), hash3(i + vec3(1.0, 1.0, 1.0)), f.x), f.y), f.z);',
    '}',
    'float fbmOct(vec3 p, int octaves){',
      'float a = 0.5, s = 0.0, norm = 0.0;',
      'for(int i = 0; i < 4; i++){',
        'if(i >= octaves) break;',
        's += a * vnoise3(p);',
        'norm += a;',
        'p = p * 2.03 + vec3(1.7, 9.2, 3.1);',
        'a *= 0.5;',
      '}',
      'return s / norm;',
    '}',


    "//The cone's frame for the noise, set once per fragment in main(): the axis direction and two",
    '//directions across it. (Only the noise uses them; the density mask is the distance to the axis.)',
    'vec3 gT, gE1, gE2;',

    "//Where along the run a sample is: u at the fragment, moved by its axial offset over the run's length.",
    'float mistU(vec3 p, vec3 T){',
      'return clamp(vMistA.y + dot(p - vCenter, T) / max(vMistB.y, 1.0), 0.0, 2.0);',
    '}',

    '//Value noise PERIODIC along x with period `per` cells (a whole number): the time term is wrapped, and',
    '//noise that did not repeat at the wrap would jump every lump at once.',
    'float vnoise3p(vec3 x, float per){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'float x0 = mod(i.x, per), x1 = mod(i.x + 1.0, per);',
      'return mix(mix(mix(hash3(vec3(x0, i.y, i.z)),             hash3(vec3(x1, i.y, i.z)),             f.x),',
                     'mix(hash3(vec3(x0, i.y + 1.0, i.z)),       hash3(vec3(x1, i.y + 1.0, i.z)),       f.x), f.y),',
                 'mix(mix(hash3(vec3(x0, i.y, i.z + 1.0)),       hash3(vec3(x1, i.y, i.z + 1.0)),       f.x),',
                     'mix(hash3(vec3(x0, i.y + 1.0, i.z + 1.0)), hash3(vec3(x1, i.y + 1.0, i.z + 1.0)), f.x), f.y), f.z);',
    '}',
    'float fbmPer(vec3 p, int octaves, float per){',
      'float a = 0.5, s = 0.0, norm = 0.0;',
      'for(int i = 0; i < 4; i++){',
        'if(i >= octaves) break;',
        's += a * vnoise3p(p, per);',
        'norm += a;',
        'p = vec3(p.x * 2.0, p.y * 2.03 + 1.7, p.z * 2.03 + 3.1);   //x exactly x2 so the octave repeats too',
        'per *= 2.0;',
        'a *= 0.5;',
      '}',
      'return s / norm;',
    '}',

    "//The noise, laid out in the WATER'S OWN TIME OF FLIGHT along the flow and in metres across it. A",
    '//parcel that passed the lip at time t0 is at tau = t - t0, so (tau - t) is the same for it all its',
    "//life: the pattern RIDES THE WATER, at the water's real speed, and its cells stretch along the fall",
    '//as the jet accelerates (equal time steps cover more metres where the water is faster), exactly as',
    "//the sheet's grain does. No advection speed to pick, no cross-fade of two copies (which stalled and",
    '//ghosted the pattern at each swap). The along-flow coordinate is the TIME at this sample: the',
    "//fragment's tau, moved by its axial offset over the local speed.",
    'const float MIST_PERIOD = 32.0;   //cells; the time term repeats after this many',
    'float mistNoise(vec3 p, float rate, float scale, int octaves){',
      'vec3 q = p - vCenter;',
      'float tauP = vTau + dot(q, gT) / max(vMistB.z, 0.5);',
      'float xa = mod(tauP * rate - mod(t * rate, MIST_PERIOD) + vMistA.w * MIST_PERIOD, MIST_PERIOD);',
      'vec3 c = vec3(xa, dot(q, gE1) / scale + vMistA.w * 17.3, dot(q, gE2) / scale + vMistA.w * 9.1);',
      'return fbmPer(c, octaves, MIST_PERIOD);',
    '}',

    '//Foam and haze are two noises, each at its OWN CONSTANT rate, blended by height. (One noise whose rate',
    '//changed along the fall would not do: its phase is (tau - t) * rate, and a rate that varies with',
    '//position shears the pattern in proportion to the elapsed time t, which smears and freezes it.)',
    'float mistFoamHaze(vec3 p, float haze, int octaves){',
      "//Lump size follows the fall's size: a 3 m fall in 0.55 m lumps is ragged shreds, a 40 m one in 0.3 m lumps is fizz.",
      'float k = clamp(sqrt(vMistB.y / max(uScaleRef, 1.0)), 0.5, 1.6);',
      'if(haze < 0.02) return mistNoise(p, uFoamRate, uFoamScale * k, octaves);',
      'if(haze > 0.98) return mistNoise(p, uHazeRate, uHazeScale * k, octaves);',
      'return mix(mistNoise(p, uFoamRate, uFoamScale * k, octaves), mistNoise(p, uHazeRate, uHazeScale * k, octaves), haze);',
    '}',

    '//Density (1/m) at a world point for the cone this fragment belongs to.',
    'float mistDensity(vec3 p, int octaves){',
      'vec3 q = p - vCenter;',
      'vec3 perp = q - gT * dot(q, gT);',
      'float R = max(vMistA.z, 1e-3);',
      'float x = length(perp) / R;',
      'if(x >= 1.0) return 0.0;',
      'float radial = pow(1.0 - x * x, uRadialPow);',
      'float u = mistU(p, gT);',
      'float fadeIn = smoothstep(0.0, max(uFadeIn, 1e-3), u);',
      'float fadeOut = 1.0 - smoothstep(uFadeOutStart, max(uFadeOutEnd, uFadeOutStart + 0.01), u);',
      'float body = max(smoothstep(uAerationLo, uAerationHi, vMistB.x), uMinBody);',
      'float ground = smoothstep(0.0, max(uGroundFade, 1e-3), p.y - vEnd.y);',
      'float env = radial * fadeIn * fadeOut * body * ground;',
      'if(env <= 0.0) return 0.0;',
      'float haze = smoothstep(uHazeStart, 1.0, u);',
      'float n = mistFoamHaze(p, haze, octaves);',
      'float lo = mix(uErodeFoam, uErodeHaze, haze) + 0.3 * (1.0 - radial);',
      'float shape = smoothstep(lo, lo + max(uErodeSoft, 1e-3), n);',
      'return uMistDensity * mix(uFoamDensity, uHazeDensity, haze) * env * shape;',
    '}',

    '//Dual-lobe Henyey-Greenstein, normalised so that isotropic scattering is 1 (a Lambert surface is',
    "//INV_PI * E, so a sample's in-scatter reads in the sheet's units).",
    "//The sea spray's night gate (ocean-splash.glsl aeratedWater): white water over a dark sea glows under ANY",
    '//sky fill, so the fill falls to uNightAmbient of itself as the sun sets (a window wide enough that twilight',
    '//keeps some). The direct light is left alone: a present moon still lights it.',
    "//The land's skyline and sky visibility (field/land-light.js, spliced by the pass): landLightVisibility(p, L),",
    '//landSkyVisibility(xz). White water in a gorge is shadowed and sky-occluded like the rock beside it.',
    '//LAND_LIGHT_INJECTION_POINT',
    "//a-starry-sky's clouds (ARestlessOcean.spliceWorldLighting): starryCloudAt(p), 1 without the sky.",
    '//STARRY_WORLD_LIGHTING_INJECTION_POINT',

    'float nightDim(){',
      'return mix(uNightAmbient, 1.0, smoothstep(-0.08, 0.06, uSunElevation));',
    '}',

    'float hgIso(float cosT, float g){',
      'return (1.0 - g * g) / pow(max(1.0 + g * g - 2.0 * g * cosT, 1e-4), 1.5);',
    '}',
    'float mistPhase(float cosT){',
      'return mix(hgIso(cosT, uPhaseG), hgIso(cosT, -0.25), 0.25);',
    '}',

    "//MULTIPLE SCATTERING (step 4b, 2026-10-03): Wrenninge's octaves (Oz, 2013; Frostbite, Nubis; the sky clouds'",
    '//cloud-march.glsl and waterfall-cloud.glsl), in place of the old two-exponential stand-in. Octave i carries',
    '//half the energy, sees half the optical depth to the sun and half the anisotropy of the one before, so light',
    '//soaks into the shaded side of a dense clump instead of it going grey-black; a diffusion floor',
    "//(uDiffusion / (1 + 0.11 tau)) catches the deep interior. NORMALISED PER ANGLE: the octaves' sum is divided by",
    '//its own value at tau 0 for this view angle and multiplied by the single phase, so a thin wisp is lit EXACTLY as',
    '//before from every side (a plain /1.875 moved ~30% of the backlit halo into the sides) and only depth changes:',
    '//where the old form went to ~0, the softened octaves keep carrying light. uMultiScatter 0 = the old form.',
    '//waterfall-mist.glsl and waterfall-splash.glsl carry the same copy (keep in step).',
    'const int MIST_MS_OCTAVES = 4;',
    'void mistPhaseOctaves(float cosT, out float ph[MIST_MS_OCTAVES]){',
      'float att = 1.0;',
      'for(int i = 0; i < MIST_MS_OCTAVES; ++i){',
        'ph[i] = mix(hgIso(cosT, uPhaseG * att), hgIso(cosT, -0.25 * att), 0.25);',
        'att *= 0.5;',
      '}',
    '}',
    "//The sun's light scattered toward the eye at a sample whose optical depth to the sun is tau (replaces",
    '//phase x transmittance).',
    'float mistSunScatter(float tau, float phase0, float ph[MIST_MS_OCTAVES]){',
      'float old = phase0 * (exp(-tau) + 0.4 * exp(-0.2 * tau)) / 1.4;',
      'float ms = 0.0, ms0 = 0.0, a = 1.0, b = 1.0;',
      'for(int i = 0; i < MIST_MS_OCTAVES; ++i){ ms += a * exp(-tau * b) * ph[i]; ms0 += a * ph[i]; a *= 0.5; b *= 0.5; }',
      'ms = max(ms, uDiffusion / (1.0 + 0.11 * tau));',
      'return mix(old, phase0 * ms / max(ms0, 1e-6), uMultiScatter);',
    '}',

    "//The scene's sun shadow at a world point: four taps, no derivatives (this runs in a loop).",
    'float sunShadowMapAt(vec3 p){',
      'if(sunShadowEnabled == 0) return 1.0;',
      'vec4 sp = sunShadowMatrix * vec4(p, 1.0);',
      'vec3 sc = sp.xyz / sp.w;',
      'if(sc.z > 1.0 || sc.z < 0.0) return 1.0;',
      'vec2 edgeDist = min(sc.xy, vec2(1.0) - sc.xy);',
      'float edge = min(edgeDist.x, edgeDist.y);',
      'if(edge < 0.0) return 1.0;',
      'float refZ = sc.z + sunShadowBias;',
      'vec2 ts = (1.0 / sunShadowMapSize) * sunShadowRadius;',
      'float s = 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2(-0.5, -0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2( 0.5, -0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2(-0.5,  0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2( 0.5,  0.5) * ts).r ? 1.0 : 0.0;',
      'return mix(1.0, 0.25 * s, smoothstep(0.0, 0.05, edge));',
    '}',
    "//...times the clouds overhead, which shade the falls' foot like the pool round it.",
    'float sunShadowAt(vec3 p){',
      'return sunShadowMapAt(p) * starryCloudAt(p).x;',
    '}',

    'void main(){',
      'vec3 N = normalize(vN), T = normalize(vT), A = normalize(vA);',
      'vec3 camToX = vWorldPos - cameraPosition;',
      'float distX = length(camToX);',
      'vec3 rd = camToX / max(distX, 1e-4);',

      "//How far back from X to march: the ray's chord through this cone (exact for a cylinder about the",
      '//axis; X is on its wall or its cap), never past the camera.',
      'float R = max(vMistA.z, 1e-3);',
      'vec3 w = vWorldPos - vCenter;',
      'w -= T * dot(w, T);',
      'vec3 rp = rd - T * dot(rd, T);',
      'float a = max(dot(rp, rp), 1e-4);',
      'float wr = dot(w, rp);',
      'float disc = max(wr * wr - a * (dot(w, w) - R * R), 0.0);',
      'float chord = (wr + sqrt(disc)) / a;',
      'float L = clamp(min(chord, distX), 0.0, uMaxChord);',
      'if(L < 1e-3) discard;',
      'int nSteps = int(clamp(uSteps, 4.0, float(MAX_STEPS)));',
      'float dt = L / float(nSteps);',
      'float jitter = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));',
      'vec3 start = vWorldPos - rd * L;',

      '//What the ground behind says: view depth of the nearest opaque thing along this pixel.',
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',
      'float gRaw = texture2D(refractionDepthTexture, screenUV).r;',
      'float sceneDepth = 1e6;',
      'if(gRaw < 1.0){',
        'vec4 gv = inverseProjectionMatrix * vec4(screenUV * 2.0 - 1.0, gRaw * 2.0 - 1.0, 1.0);',
        'sceneDepth = -gv.z / gv.w;',
      '}',

      'vec3 Lsun = -normalize(brightestDirectionalLightDirection);   //toward the sun',
      'float cosT = dot(rd, Lsun);',
      'float phase = mistPhase(cosT);',
      'float phOct[MIST_MS_OCTAVES];',
      'mistPhaseOctaves(cosT, phOct);',
      'vec3 sunCol = INV_PI * brightestDirectionalLight * uSunGain * landLightVisibilityOpen(vWorldPos, Lsun);',
      '//UNITS: irradiance -> radiance, the 1/PI the sun term has (INV_PI) (ambientPiFix, 2026-10-02).',
      'vec3 ambient = skyAmbientColor * uAmbient * nightDim() * landSkyVisibilityOpen(vWorldPos.xz) * mix(1.0, INV_PI, ambientPiFix);',

      'gT = T;',
      'vec3 across = A - T * dot(A, T);',
      'if(dot(across, across) < 1e-4) across = cross(T, abs(T.x) < 0.9 ? vec3(1.0, 0.0, 0.0) : vec3(0.0, 0.0, 1.0));',
      'gE1 = normalize(across);',
      'gE2 = cross(T, gE1);',

      'float camSide = sign(dot(cameraPosition - vCenter, N));',
      'if(camSide == 0.0) camSide = 1.0;',
      'float hw = max(vMistB.w, 0.1);',

      'float Tr = 1.0;',
      'vec3 acc = vec3(0.0);',
      'float lightStep = uLightLength / max(uLightSteps, 1.0);',
      'int nLight = int(clamp(uLightSteps, 1.0, float(MAX_LIGHT_STEPS)));',
      'float depthLen = 0.0;',

      'for(int i = 0; i < MAX_STEPS; i++){',
        'if(i >= nSteps) break;',
        'float back = L - dt * (float(i) + jitter);   //metres back from X',
        'vec3 p = start + rd * (dt * (float(i) + jitter));',
        'float dens = mistDensity(p, 3);',
        'if(dens <= 0.002) continue;',

        '//Occlusion: the ground behind (view depth along the ray is linear in distance), then the curtain.',
        'float viewDepth = vViewDepth * (1.0 - back / max(distX, 1e-4));',
        'float vis = clamp((sceneDepth - viewDepth) / max(uSoftRange, 1e-3), 0.0, 1.0);',
        'vec3 dp = p - vCenter;',
        'float sideOK = smoothstep(-0.15, 0.15, dot(dp, N) * camSide);',
        'float acrossP = vMistA.x + dot(dp, A);',
        'float insideSheet = (1.0 - smoothstep(0.9 * hw, 1.05 * hw, abs(acrossP))) * (1.0 - smoothstep(1.0, 1.1, mistU(p, T)));',
        'vis *= mix(1.0, sideOK, uSheetOcclusion * insideSheet);',
        'float sigma = dens * vis;',
        'if(sigma <= 1e-4) continue;',

        '//Self-shadowing: march toward the sun through the same cone (two octaves, one noise copy).',
        'float tauL = 0.0;',
        'for(int k = 0; k < MAX_LIGHT_STEPS; k++){',
          'if(k >= nLight) break;',
          'vec3 q = p + Lsun * lightStep * (float(k) + 0.5 + 0.5 * jitter);',
          'tauL += mistDensity(q, 2) * lightStep;',
        '}',
        'tauL *= uAbsorption;',
        '//The direct light and the light scattered round the clump (mistSunScatter: the octaves, step 4b).',
        'float sunS = mistSunScatter(tauL, phase, phOct);',
        'vec3 albedo = mix(uAlbedoFoam, uAlbedoHaze, smoothstep(uHazeStart, 1.0, mistU(p, T)));',
        'vec3 scatter = albedo * (sunCol * sunS * sunShadowAt(p) * fallShadowAt(p) + ambient);',

        'float stepT = exp(-sigma * dt);',
        'acc += Tr * (1.0 - stepT) * scatter;',
        'Tr *= stepT;',
        'depthLen += dt;',
        'if(Tr < 0.01) break;',
      '}',

      'float alpha = (1.0 - Tr) * uMistOpacity;',
      'if(uDebugMode == 0 && alpha < 0.003) discard;',
      'vec3 color = acc / max(1.0 - Tr, 1e-4);',
      '#if($atmospheric_perspective_enabled)',
        'if(underwaterFactor < 0.5) color = applyAtmosphericPerspective(color, vWorldPos - rd * 0.5 * L);',
      '#endif',
      'gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(color), alpha));',

      '//$DEBUG_START$',
      'if(uDebugMode == 1) gl_FragColor = vec4(vec3(1.0 - Tr), 1.0);                                   //opacity',
      'else if(uDebugMode == 2) gl_FragColor = vec4(vec3(clamp(vMistA.y * 0.5, 0.0, 1.0)), 1.0);       //u at the exit point: 0 lip, .5 landing, 1 run-out end',
      'else if(uDebugMode == 3) gl_FragColor = vec4(vec3(clamp(L / uMaxChord, 0.0, 1.0)), 1.0);        //chord',
      'else if(uDebugMode == 4) gl_FragColor = vec4(0.9, 0.2, 0.9, 0.35);                              //the cones',
      'else if(uDebugMode == 5) gl_FragColor = vec4(vec3(clamp(depthLen / 4.0, 0.0, 1.0)), 1.0);       //path through mist',
      'else if(uDebugMode == 6){                                                                       //at mid-chord: foam weight (r), haze weight (g), ground (b)',
        'vec3 pm = vWorldPos - rd * 0.5 * L;',
        'float um = mistU(pm, T);',
        'float hz = smoothstep(uHazeStart, 1.0, um);',
        'gl_FragColor = vec4(1.0 - hz, hz, smoothstep(0.0, max(uGroundFade, 1e-3), pm.y - vEnd.y), 1.0);',
      '}',
      'else if(uDebugMode == 8){                                                                       //the raw noise at mid-chord, full contrast (to see / measure how the pattern moves)',
        'vec3 pm = vWorldPos - rd * 0.5 * L;',
        'float hz = smoothstep(uHazeStart, 1.0, mistU(pm, T));',
        'gl_FragColor = vec4(vec3(mistFoamHaze(pm, hz, 3)), 1.0);',
      '}',
      'else if(uDebugMode == 7) gl_FragColor = vec4(vec3(clamp(mistDensity(vWorldPos, 3) * 10.0, 0.0, 1.0)), 1.0);   //density AT the wall: must be 0 everywhere (bright = a leak)',
      '//$DEBUG_END$',

      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',
    ];
    const updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedCode = originalGLSL[i];
      updatedCode = updatedCode.replace(/\$atmospheric_perspective_enabled/g, atmosphericPerspectiveEnabled ? '1' : '0');
      if(atmosphericPerspectiveEnabled && atmosphereFunctionsGLSL && updatedCode.indexOf('//ATMOSPHERE_FUNCTIONS_INJECTION_POINT') !== -1){
        updatedCode = atmosphereFunctionsGLSL;
      }
      updatedLines.push(updatedCode);
    }
    return updatedLines.join('\n');
  },

  vertexShader: [
    'precision highp float;',

    '//Waterfall mist vertex stage. The mesh is the set of CONES ARestlessOcean.WaterfallMistHull builds',
    "//along the water's paths: closed, round, wound outward. Nothing is displaced here; the stage hands",
    "//the fragment stage each cone's axis point and direction (the density is a function of the",
    "//distance to the axis, so it is zero on the wall by construction) and the curtain's own normal and",
    '//across direction (used only to tell which side of the sheet a sample is on).',

    "attribute vec3 aCenter;      //the cone's axis point at this ring",
    "attribute vec3 aFlowTangent; //the cone's axis direction (down the flow, unit)",
    "attribute vec3 aFlowAcross;  //the curtain's across direction (unit)",
    "attribute vec4 aMistA;       //across (m from the curtain's middle), u (0 lip, 1 landing, 1..2 run-out), radius (m), seed",
    "attribute vec4 aMistB;       //aeration, run length (m), the water's speed here (m/s), curtain half-width (m)",
    "attribute vec4 aMistC;       //the run's landing point (xyz) and the water's time of flight at this ring (s)",

    'varying vec3 vWorldPos;',
    'varying vec3 vCenter;',
    'varying vec3 vN;',
    'varying vec3 vT;',
    'varying vec3 vA;',
    'varying vec4 vMistA;',
    'varying vec4 vMistB;',
    'varying vec3 vEnd;',
    'varying float vTau;',
    'varying float vViewDepth;',

    '#include <fog_pars_vertex>',

    'void main(){',
      'vec4 worldPos = modelMatrix * vec4(position, 1.0);',
      'vWorldPos = worldPos.xyz;',
      'vCenter = (modelMatrix * vec4(aCenter, 1.0)).xyz;',
      'vN = normal;',
      'vT = aFlowTangent;',
      'vA = aFlowAcross;',
      'vMistA = aMistA;',
      'vMistB = aMistB;',
      'vEnd = (modelMatrix * vec4(aMistC.xyz, 1.0)).xyz;',
      'vTau = aMistC.w;',
      'vec4 mvPosition = viewMatrix * worldPos;',
      'vViewDepth = -mvPosition.z;',
      '//The fog chunk reads `mvPosition` and `transformed` by those names (see waterfall-sheet-vertex.glsl).',
      '#ifdef USE_FOG',
        'vec3 transformed = position;',
      '#endif',
      '#include <fog_vertex>',
      'gl_Position = projectionMatrix * mvPosition;',
    '}',
  ].join('\n'),
};
