//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
//
//Waterfall splash bursts (volumetric). The SHARED block is replaced at init by the flowing-water
//material's own uniform objects (WaterfallSplashPass.init aliases them, as the mist does), so the
//splash is lit by exactly the sun, sky, shadow and atmosphere the fall and the creek are. The
//defaults here only matter if the splash is ever drawn without a flowing surface.
ARestlessOcean.Materials.Ocean.waterfallSplashMaterial = {
  uniforms: {
    //SHARED with the flowing-water material
    brightestDirectionalLight: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    brightestDirectionalLightDirection: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    skyAmbientColor: {value: new THREE.Vector3(0.3, 0.4, 0.5)},
    t: {value: 0.0},
    //The land's skyline and sky visibility (field/land-light.js LandLight.update, every frame): SHARED, aliased from the flowing material.
    landHorizonTex: {value: null},
    landHorizonAtlas: {value: new THREE.Vector4(1, 1, 1, 1)},
    landHorizonFrame: {value: new THREE.Vector4(0, 0, 1, 1)},
    landHorizonParams: {value: new THREE.Vector2(24, 0.03)},
    landGroundTex: {value: null},
    landGroundFrame: {value: new THREE.Vector4(0, 0, 1, 1)},
    landLightOn: {value: new THREE.Vector2(0, 0)},
    //SHARED: 1 = the sky irradiance gets the Lambert 1/PI (physical); 0 = the old PI x fill (oceanGrid.ambientPiFix).
    ambientPiFix: {value: 1.0},
    //The falls' shadow (passes/waterfall-shadow-pass.js writeUniforms): SHARED.
    fallShadowMap: {value: null},
    fallShadowMatrix: {value: new THREE.Matrix4()},
    fallShadowParams: {value: new THREE.Vector2(0, 0.005)},
    sunShadowMap: {value: null},
    sunShadowMatrix: {value: new THREE.Matrix4()},
    sunShadowMapSize: {value: new THREE.Vector2(2048.0, 2048.0)},
    sunShadowRadius: {value: 1.0},
    sunShadowBias: {value: 0.0},
    sunShadowEnabled: {value: 0},
    refractionDepthTexture: {value: null},
    inverseProjectionMatrix: {value: new THREE.Matrix4()},
    screenResolution: {value: new THREE.Vector2(1920.0, 1080.0)},
    underwaterFactor: {value: 0.0},
    atmosphereTransmittance: {value: null},
    atmosphereMieInscattering: {value: null},
    atmosphereRayleighInscattering: {value: null},
    atmSunPosition: {value: new THREE.Vector3(0.0, 1.0, 0.0)},
    atmMoonPosition: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    atmSunHorizonFade: {value: 1.0},
    atmMoonHorizonFade: {value: 0.0},
    atmScatteringSunIntensity: {value: 1.0},
    atmScatteringMoonIntensity: {value: 0.0},
    atmMoonLightColor: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    atmCameraHeight: {value: 0.0},
    atmDistanceScale: {value: 1.0},

    //Scene fog (see waterfall-sheet-template.txt: the material is fog:true)
    fogNear: {value: 1.0},
    fogFar: {value: 1000.0},
    fogDensity: {value: 0.00025},
    fogColor: {value: new THREE.Color()},
    uwSunDir: {value: new THREE.Vector3(0.0, -1.0, 0.0)},

    //The splash's own (lengths x6, density /6 and time rates /2 on 2026-10-02: the same look, six times the size, half the speed). FUDGE: look choices on top of the model in waterfall-splash-hull.js (the
    //launch, flight and pulse are the hull's options; these shape and light what is drawn).
    uSplashDensity: {value: 0.83},
    uSplashScale: {value: 0.6},
    uErode: {value: 0.28},
    uErodeAge: {value: 0.22},
    uErodeSoft: {value: 0.2},
    uStretch: {value: 4.0},
    uRiseRate: {value: 5.0},
    uFill: {value: 0.7},
    uTopSoft: {value: 0.6},
    uPulseRate: {value: 2.5},
    uPulseMin: {value: 0.45},
    uPulseScatter: {value: 1.0},
    uHeightNoise: {value: 0.55},
    uHeightScale: {value: 0.8},
    uHeightDrift: {value: 0.75},
    uFallDensity: {value: 1.5},
    uFallHeight: {value: 0.75},
    uFallDelay: {value: 0.5},
    uFallFloor: {value: 0.5},
    uFallSpeed: {value: 1.5},
    uFallErode: {value: 0.0},
    //The foam fog (see waterfall-splash.glsl "the fog"): low, wide and calm, driven by the same impact.
    uFogDensity: {value: 0.3},
    uFogHeight: {value: 0.85},
    uFogWidth: {value: 1.1},
    uFogSpread: {value: 0.8},
    uFogFade: {value: 1.8},
    uFogScale: {value: 1.2},
    uFogErode: {value: 0.3},
    uFogSoft: {value: 0.4},
    uFogRise: {value: 0.5},
    uFogPulse: {value: 0.4},
    uFogLag: {value: 0.6},
    uFogWander: {value: 0.5},
    uFogDrift: {value: 0.15},
    uFogPulseDepth: {value: 0.0},   //0.7 -> 0 on 2026-10-02: the pulses now live in the surface mist (uSM*), low on the water
    uFogPulseSlow: {value: 0.8},
    //Copied from DynamicWaves.FALL_RINGS every frame by WaterfallSplashPass (k for a 4 m wave, its deep-water omega).
    uRingWave: {value: new THREE.Vector2(1.5708, 3.9244)},
    //The surface mist (see waterfall-splash.glsl "THE SURFACE MIST"): the pass's second mesh sets uSurfaceMist 1.
    uSurfaceMist: {value: 0.0},
    //Density, height, decay and pulse speed set by Dante in the browser on 2026-10-02 (were 2.0, 0.12, 14, 0.8).
    uSMDensity: {value: 10.0},
    uSMHeight: {value: 0.5},
    uSMDecay: {value: 1.0},     //2.5 -> 1 (Dante, 2026-10-02)
    uSMReach: {value: 10.0},    //30 -> 10 (Dante, 2026-10-02)
    uSMPulseDepth: {value: 0.85},
    uSMPulseSlow: {value: 3.0},
    uSMScale: {value: 1.5},
    uSMDrift: {value: 0.2},
    uSMErode: {value: 0.1},     //0.35 -> 0.1 (Dante, 2026-10-02: a high carve broke the mist at the same spots every time)
    uSMWispSoft: {value: 0.3},
    uSMWispStretch: {value: 3.0},
    uSMWispSpeed: {value: 0.6},
    uSMWarp: {value: 1.2},
    uSMBase: {value: 0.4},      //0.15 -> 0.4 (Dante, 2026-10-02)
    uSMBaseDecay: {value: 4.0},
    uSMSteps: {value: 12.0},
    uGroundFade: {value: 0.05},
    uSteps: {value: 28.0},
    uLightSteps: {value: 2.0},
    uLightLength: {value: 3.6},
    uAbsorption: {value: 1.0},
    uPhaseG: {value: 0.7},
    //Step 4b: Wrenninge multiple scattering (1) or the old stand-in (0); the diffusion floor's weight.
    uMultiScatter: {value: 1.0},
    uDiffusion: {value: 0.5},
    uAmbient: {value: 1.0},
    //The night gate (the sea spray's): the sky fill falls to uNightAmbient of itself as the sun sets, so white
    //water over a dark sea does not glow. uSunElevation (sin of the TRUE solar elevation) is set every frame.
    uSunElevation: {value: 1.0},
    uNightAmbient: {value: 0.07},
    uSunGain: {value: 1.0},
    uAlbedo: {value: new THREE.Vector3(0.97, 0.98, 1.0)},
    uSoftRange: {value: 0.3},
    uSplashOpacity: {value: 1.0},
    uDebugMode: {value: 0},
  },

  //Built like the sheet's (waterfall-sheet-template.txt): $atmospheric_perspective_enabled is
  //substituted, and with it on the atmosphere functions replace the injection marker line.
  //WaterfallSplashPass rebuilds it when atmospheric perspective becomes ready.
  fragmentShader: function(atmosphericPerspectiveEnabled, atmosphereFunctionsGLSL){
    const originalGLSL = [
    'precision highp float;',

    '//Waterfall splash fragment stage: the bursts of spray thrown up where a fall lands, raymarched',
    '//inside the BLOBS ARestlessOcean.WaterfallSplashHull builds (a sphere at each landing, drawn as an',
    '//icosahedron round it). The first of the foot particles; the mist above it is waterfall-mist.glsl.',
    '//',
    '//WHAT IT DRAWS. The material culls FRONT faces, so each fragment is a point where a view ray leaves',
    "//the proxy. The ray is intersected with the blob's exact sphere, clipped at the camera (which may be",
    '//inside), and the volume is integrated front to back over that chord.',
    '//',
    "//THE DENSITY is the model in waterfall-splash-hull.js (read its header). In the blob's frame, z up",
    '//its axis and (x, y) across it:',
    "//  launch ring a sample's (x, y) is where its drops left the water: xi from the middle. They leave",
    '//              at v0(xi) = v0 exp(-xi^2 / 2 b^2) and there are exp(-xi^2 / b^2) of them: the middle',
    '//              is the heaviest and the fastest.',
    '//  the pulse   at several bursts a second the drops of one burst are still in the air when the next',
    '//              fires, so the splash never clears: it is a standing fountain whose LAUNCH SPEED',
    '//              pulses. The pulse is a sum of three sines (uPulseRate and two harmonics that do not',
    '//              divide it, so it does not repeat by eye), between uPulseMin and 1, and its phase is',
    '//              scattered over the footprint by 2D noise, so neighbouring spurts peak at different',
    '//              times instead of the whole foot bobbing as one.',
    '//  height noise the launch speed is also scaled by its own slowly drifting 2D noise over the',
    '//              footprint (uHeightNoise, uHeightScale): a ragged line of tops, not a smooth bell.',
    '//  the top     Z = the apex of a drop launched at that speed (drag flattens the tall ones).',
    '//  radial      the drops fly out as well as up, along rays from a focus under the water, so the',
    "//              splash opens 1 + k wide by its top (k: the hull's fan) and its streaks run out along",
    '//              the rays: a little spherical symmetry.',
    '//  the fall    what goes up comes down: the water that leaves the top of the column lands further out',
    "//              (the hull's fallReach, vSplashC.w: the falling skirt is the column's bell stretched",
    "//              1 + fallReach wide and uFallHeight as tall), LATE (its pulse is the column's from",
    "//              uFallDelay x the middle's fall time ago, so a spurt goes up and a moment later rains",
    '//              down round it), drawn where the column is thin, with streaks that run DOWN at',
    '//              uFallSpeed x uRiseRate and break into flecks sooner (uFallErode). The bounce.',
    '//  the fog     FOAM FOG round the foot: the finest of the spray, hanging. The same impact drives it:',
    "//              its density goes with the blob's strength and its top with the column's apex",
    '//              (uFogHeight of it), and it breathes with the same pulse, but only uFogPulse of it and',
    '//              uFogLag late, so it is the calm, lingering part of the splash. It is wider than the',
    '//              column (uFogWidth x b, opening by uFogSpread toward its top) and FADES OUT with height',
    '//              (exp(-uFogFade z / top)), rising slowly (uFogRise m/s) as soft, barely carved billows.',
    "//              Its middle is not the landing's: it wanders round it by Perlin noise (uFogWander x b,",
    '//              uFogDrift), so the fog drifts and leans like the real thing instead of sitting still.',
    '//              It rolls OUT in pulses with the waves the fall sends across the pool (DynamicWaves',
    '//              Fall rings): bands of thicker fog at the wavelength of the rings (uRingWave, set by the',
    '//              pass from DynamicWaves.FALL_RINGS) travelling outward from the middle at uFogPulseSlow',
    '//              of their speed, uFogPulseDepth deep (0: an even fog).',
    '//  the column  from the water to the top the volume is FILLED (uFill at the foot, 1 at the top),',
    '//              with a soft edge above (uTopSoft).',
    '//  noise       3D value noise in metres, its cells stretched uStretch times ALONG the axis and',
    '//              running up it at uRiseRate cells a second (periodic in that direction, so it loops',
    '//              without a seam): vertical streaks of spray, like the grain of the foam coming down.',
    '//              The carve threshold rises toward the top, so the body breaks into streaks and flecks.',
    "//  bounds      nothing below the water's level, and a window that is zero on the sphere, so the",
    "//              density is zero on the blob's wall by construction.",
    '//',
    "//THE SURFACE MIST (uSurfaceMist = 1: the pass's second mesh, a box per landing line, sharing every",
    '//uniform). A thin layer of foam mist lying on the pool: its height is measured above the still',
    '//water level (it does NOT ride the waves: a cloud drifting out over the pool does not bob with the',
    '//swell under it; riding was tried first and read worse), and it thins with an e-fold of uSMHeight.',
    '//Across the pool it reaches further than the waves (uSMDecay against their decay) and rolls out in',
    '//bands at the wavelength of the waves (DynamicWaves "Fall rings", spliced in at the FALL_RINGS',
    '//injection point below, which also gives it the landing lines), uSMPulseSlow of their speed,',
    '//uSMPulseDepth deep. Two falloffs across the pool: a dense CORE dying at uSMDecay, and a lighter',
    '//HAZE (uSMBase of the density) dying at its own uSMBaseDecay, so the core can be short and the haze',
    '//linger without one fighting the other; the gaps between bands are no thinner than the haze;',
    '//uSMReach is only where it is cut off (softly, from 0.7 of it). All three distances are scaled by',
    "//the line's SIZE (its fall's drop over 10 m, 0.2..1.5): a short step's mist stays near its foot",
    '//instead of drifting out over the next ledge. WISPS: noise stretched',
    '//uSMWispStretch times along the outward direction and carried outward at uSMWispSpeed, its across',
    '//coordinate bent by a slow domain warp (uSMWarp), three octaves carved softly (uSMErode, uSMWispSoft):',
    '//streaks streaming off the foot, not round puffs. Downstream of the line only, as the waves.',
    '//',
    "//THE LIGHT, OCCLUSION, ATMOSPHERE AND FOG are the mist's (see waterfall-mist.glsl): a short sun march",
    "//for self-shadowing, a dual-lobe Henyey-Greenstein phase, the scene's sun shadow map, the sky's",
    '//ambient; no depth test, the refraction G-buffer clips the march softly.',

    'uniform vec3 brightestDirectionalLight;',
    'uniform vec3 brightestDirectionalLightDirection;   //from the sun TOWARD the scene',
    'uniform vec3 skyAmbientColor;',
    'uniform float t;',

    'uniform sampler2D sunShadowMap;',
    'uniform mat4 sunShadowMatrix;',
    'uniform vec2 sunShadowMapSize;',
    'uniform float sunShadowRadius;',
    'uniform float sunShadowBias;',
    'uniform int sunShadowEnabled;',

    'uniform sampler2D refractionDepthTexture;',
    'uniform mat4 inverseProjectionMatrix;',
    'uniform vec2 screenResolution;',
    'uniform float underwaterFactor;',

    'uniform float uSplashDensity;    //1/m extinction at the middle of a full-strength burst',
    'uniform float uSplashScale;      //m per noise cell',
    'uniform float uErode;            //0..1: noise level below which the foot of the column is carved away',
    'uniform float uErodeAge;         //... and how much more at its top (it breaks into streaks and flecks)',
    'uniform float uErodeSoft;        //width of the carve edge',
    'uniform float uStretch;          //how many times longer than wide a noise cell is, along the axis',
    'uniform float uRiseRate;         //noise cells per second the pattern runs up the axis',
    'uniform float uFill;             //0..1: density at the foot of the column, against 1 at its top',
    'uniform float uTopSoft;          //m of soft edge above the top',
    'uniform float uPulseRate;        //pulses per second',
    'uniform float uPulseMin;         //the launch speed between pulses, as a fraction of the peak (never 0: it does not clear)',
    'uniform float uPulseScatter;     //how far (in pulses) the 2D noise scatters the pulse phase over the footprint',
    'uniform float uHeightNoise;      //0..1: how much of the launch speed the 2D height noise takes away at its lowest',
    'uniform float uHeightScale;      //m per cell of the height noise',
    'uniform float uHeightDrift;      //cells per second the height noise changes by',
    "uniform float uFallDensity;      //the falling skirt's density, as a fraction of the column's",
    "uniform float uFallHeight;       //its top, as a fraction of the column's",
    "uniform float uFallDelay;        //how late it is, as a fraction of the middle's time to fall from its apex",
    'uniform float uFallFloor;        //0..1: its density at the water, against 1 at its top (the rain thins as it falls)',
    'uniform float uFallSpeed;        //its streaks run down at this times uRiseRate',
    'uniform float uFallErode;        //how much more it is carved than the column (it is flecks and drops)',
    "uniform float uFogDensity;       //the foam fog's density at its middle, at the water, as a fraction of the column's",
    "uniform float uFogHeight;        //its top, as a fraction of the column's apex",
    'uniform float uFogWidth;         //its Gaussian width at the water, x b',
    'uniform float uFogSpread;        //how much wider it opens by its top (1 + this)',
    'uniform float uFogFade;          //how fast it thins with height: exp(-uFogFade z / top)',
    'uniform float uFogScale;         //m per noise cell of its billows',
    'uniform float uFogErode;         //0..1: noise level below which it is carved (low: it is fog, not flecks)',
    "uniform float uFogSoft;          //width of that carve's edge (wide: soft)",
    'uniform float uFogRise;          //m per second the billows rise',
    "uniform float uFogPulse;         //0..1: how much of the column's pulse moves its top",
    'uniform float uFogLag;           //s: how late it follows the pulse',
    'uniform float uFogWander;        //how far (x b) its middle wanders round the landing',
    'uniform float uFogDrift;         //Perlin noise units per second of that wander',
    'uniform float uFogPulseDepth;    //0..1: how much the outward pulses thin the fog between them',
    "uniform float uFogPulseSlow;     //their speed as a fraction of the pool waves' (1: with the waves)",
    "uniform vec2 uRingWave;          //the pool waves' wavenumber (rad/m) and frequency (rad/s): WaterfallSplashPass copies them",
    'uniform float uSurfaceMist;      //1: this mesh is the surface mist (see the header), 0: the splash bursts',
    'uniform float uSMDensity;        //1/m: the surface mist at the water, by the line, for a 10 m fall',
    'uniform float uSMHeight;         //m: its e-fold height above the moving surface',
    'uniform float uSMDecay;          //m: its e-fold distance from the line',
    'uniform float uSMReach;          //m: where it has faded to nothing (the boxes are built this far out)',
    'uniform float uSMPulseDepth;     //0..1: how much the bands thin it between them',
    "uniform float uSMPulseSlow;      //the bands' speed as a fraction of the pool waves'",
    'uniform float uSMScale;          //m per cell of its wisps',
    'uniform float uSMDrift;          //wisp cells per second',
    'uniform float uSMErode;          //0..1: noise level below which it is thinned to nothing',
    'uniform float uSMWispSoft;       //width of that carve (wide: soft wisps)',
    'uniform float uSMWispStretch;    //how many times longer than wide a wisp is, along the outward direction',
    'uniform float uSMWispSpeed;      //m/s the wisps stream outward',
    'uniform float uSMWarp;           //m the slow domain warp bends them across',
    "uniform float uSMBase;           //0..1: the haze's share of the density (and the floor of the gaps between bands)",
    "uniform float uSMBaseDecay;      //m: the haze's e-fold distance from the line (the core's is uSMDecay)",
    'uniform float uSMSteps;          //view-ray steps through the layer',
    "uniform float uGroundFade;       //m above the water's level over which the splash fades in",
    'uniform float uSteps;            //view-ray steps',
    'uniform float uLightSteps;       //sun-ray steps',
    'uniform float uLightLength;      //m the sun ray reaches',
    "uniform float uAbsorption;       //sun-ray extinction as a multiple of the view's",
    'uniform float uPhaseG;           //forward lobe of the phase function',
    'uniform float uMultiScatter;     //1: Wrenninge octaves + diffusion floor (step 4b); 0: the old two-exponential stand-in',
    "uniform float uDiffusion;        //the multiple-scatter diffusion floor's weight (isotropic units)",
    'uniform float uAmbient;          //sky fill',
    'uniform float ambientPiFix;   //1: the sky irradiance gets the Lambert 1/PI a-land and three apply (physical); 0: the old, PI x too bright sky fill. A/B, 2026-10-02',
    'uniform float uSunElevation;     //sin of the TRUE solar elevation (the moon is the brightest light at night)',
    "uniform float uNightAmbient;     //the sky fill's floor at night, as a share of itself (OceanSplash nightAmbient)",
    'uniform float uSunGain;          //sun scatter gain',
    'uniform vec3 uAlbedo;            //single-scatter albedo',
    'uniform float uSoftRange;        //m of depth over which the splash fades into the ground',
    'uniform float uSplashOpacity;',
    'uniform int uDebugMode;',

    'varying vec3 vWorldPos;',
    "varying vec4 vCenter;    //the blob's origin and radius",
    "varying vec4 vSplashA;   //launch speed at the middle (m/s), ballistic period (s, unused here), the impact's width b (m), seed",
    'varying vec4 vSplashB;   //up axis, strength',
    'varying vec4 vSplashC;   //level, terminal speed (m/s), radial spread k, fall reach',
    'varying float vViewDepth;',

    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_fragment>',
    '#endif',
    '#if($atmospheric_perspective_enabled)',
      'precision highp sampler3D;',
      'uniform sampler2D atmosphereTransmittance;',
      'uniform sampler3D atmosphereMieInscattering;',
      'uniform sampler3D atmosphereRayleighInscattering;',
      'uniform vec3 atmSunPosition;',
      'uniform vec3 atmMoonPosition;',
      'uniform float atmSunHorizonFade;',
      'uniform float atmMoonHorizonFade;',
      'uniform float atmScatteringSunIntensity;',
      'uniform float atmScatteringMoonIntensity;',
      'uniform vec3 atmMoonLightColor;',
      'uniform float atmCameraHeight;',
      'uniform float atmDistanceScale;',

      '//ATMOSPHERE_FUNCTIONS_INJECTION_POINT',

      '//Lifted verbatim from waterfall-sheet.glsl (keep in step). The injected functions are the LUT',
      '//helpers only; the sheet and the creek each define their own applyAtmosphericPerspective on top.',
      '//Atmospheric perspective for ground-level surfaces.',
      '//Uses distance-based extinction with LUT-sampled multi-scattered inscattering.',
      '//At the same height: S(A->B) = S(A->inf) * (1 - T(A->B))',
      'vec3 applyAtmosphericPerspective(vec3 color, vec3 worldPos){',
        'vec3 worldViewDir = normalize(worldPos - cameraPosition);',
        "//Convert view direction from THREE.js world space to a-starry-sky's coordinate",
        '//system. Sun world direction = (-sp.z, sp.y, -sp.x) from quadOffset, so the',
        '//inverse transform from world to sky coords is: skyDir = (-world.z, world.y, -world.x)',
        'vec3 viewDir = vec3(-worldViewDir.z, worldViewDir.y, -worldViewDir.x);',
        'float dist = length(worldPos - cameraPosition) * METERS_TO_KM * atmDistanceScale;',

        '//Distance-based extinction along the camera-to-surface path',
        'vec3 extinction = exp(-(RAYLEIGH_BETA + EARTH_MIE_BETA_EXTINCTION) * dist);',

        '//Attenuate surface color',
        'color *= extinction;',

        '//LUT coordinates for inscattering lookup',
        'float viewCosZenith = max(viewDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscattering from 3D LUTs',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(viewDir, atmSunPosition);',
        'vec3 fogSun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun)',
                    '* (1.0 - extinction);',

        '//Moon inscattering from 3D LUTs',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(viewDir, atmMoonPosition);',
        'vec3 fogMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon)',
                     '* (1.0 - extinction);',

        'return color + fogSun + fogMoon;',
      '}',
    '#endif',

    '//(No PI of our own: the injected atmosphere functions declare one; a second is a link error.)',
    'const float INV_PI = 0.31830988618;',
    'const int MAX_STEPS = 64;',
    'const int MAX_LIGHT_STEPS = 8;',

    '//── Copied from waterfall-sheet.glsl (keep in step) ───────────────────────────',
    "//Applied to AP's output as the sheet does: the sheet and its mist then tone-map alike.",
    'vec4 linearTosRGB(vec4 value){',
      'return vec4(mix(pow(value.rgb, vec3(0.41666)) * 1.055 - vec3(0.055), value.rgb * 12.92, vec3(lessThanEqual(value.rgb, vec3(0.0031308)))), value.a);',
    '}',
    'vec3 aroAESFilmicToneMapping(vec3 color){',
      'return clamp((color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14), 0.0, 1.0);',
    '}',
    '//──────────────────────────────────────────────────────────────────────────────',

    "//── Noise: ocean-splash.glsl's hash3 / vnoise3 ────────────────────────────────",
    'float hash3(vec3 p){',
      'p = fract(p * 0.3183099 + 0.1);',
      'p *= 17.0;',
      'return fract(p.x * p.y * p.z * (p.x + p.y + p.z));',
    '}',
    'float vnoise3(vec3 x){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'return mix(mix(mix(hash3(i + vec3(0.0, 0.0, 0.0)), hash3(i + vec3(1.0, 0.0, 0.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 0.0)), hash3(i + vec3(1.0, 1.0, 0.0)), f.x), f.y),',
                 'mix(mix(hash3(i + vec3(0.0, 0.0, 1.0)), hash3(i + vec3(1.0, 0.0, 1.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 1.0)), hash3(i + vec3(1.0, 1.0, 1.0)), f.x), f.y), f.z);',
    '}',
    'float fbmOct(vec3 p, int octaves){',
      'float a = 0.5, s = 0.0, norm = 0.0;',
      'for(int i = 0; i < 4; i++){',
        'if(i >= octaves) break;',
        's += a * vnoise3(p);',
        'norm += a;',
        'p = p * 2.03 + vec3(1.7, 9.2, 3.1);',
        'a *= 0.5;',
      '}',
      'return s / norm;',
    '}',

    '//FALL_RINGS_INJECTION_POINT',

    '//Dual-lobe Henyey-Greenstein, normalised so that isotropic scattering is 1 (a Lambert surface is',
    "//INV_PI * E, so a sample's in-scatter reads in the sheet's units).",
    "//The sea spray's night gate (ocean-splash.glsl aeratedWater): white water over a dark sea glows under ANY",
    '//sky fill, so the fill falls to uNightAmbient of itself as the sun sets (a window wide enough that twilight',
    '//keeps some). The direct light is left alone: a present moon still lights it.',
    "//The land's skyline and sky visibility (field/land-light.js, spliced by the pass): landLightVisibility(p, L),",
    '//landSkyVisibility(xz). White water in a gorge is shadowed and sky-occluded like the rock beside it.',
    '//LAND_LIGHT_INJECTION_POINT',
    "//a-starry-sky's clouds (ARestlessOcean.spliceWorldLighting): starryCloudAt(p), 1 without the sky.",
    '//STARRY_WORLD_LIGHTING_INJECTION_POINT',

    'float nightDim(){',
      'return mix(uNightAmbient, 1.0, smoothstep(-0.08, 0.06, uSunElevation));',
    '}',

    'float hgIso(float cosT, float g){',
      'return (1.0 - g * g) / pow(max(1.0 + g * g - 2.0 * g * cosT, 1e-4), 1.5);',
    '}',
    'float mistPhase(float cosT){',
      'return mix(hgIso(cosT, uPhaseG), hgIso(cosT, -0.25), 0.25);',
    '}',

    "//MULTIPLE SCATTERING (step 4b, 2026-10-03): Wrenninge's octaves (Oz, 2013; Frostbite, Nubis; the sky clouds'",
    '//cloud-march.glsl and waterfall-cloud.glsl), in place of the old two-exponential stand-in. Octave i carries',
    '//half the energy, sees half the optical depth to the sun and half the anisotropy of the one before, so light',
    '//soaks into the shaded side of a dense clump instead of it going grey-black; a diffusion floor',
    "//(uDiffusion / (1 + 0.11 tau)) catches the deep interior. NORMALISED PER ANGLE: the octaves' sum is divided by",
    '//its own value at tau 0 for this view angle and multiplied by the single phase, so a thin wisp is lit EXACTLY as',
    '//before from every side (a plain /1.875 moved ~30% of the backlit halo into the sides) and only depth changes:',
    '//where the old form went to ~0, the softened octaves keep carrying light. uMultiScatter 0 = the old form.',
    '//waterfall-mist.glsl and waterfall-splash.glsl carry the same copy (keep in step).',
    'const int MIST_MS_OCTAVES = 4;',
    'void mistPhaseOctaves(float cosT, out float ph[MIST_MS_OCTAVES]){',
      'float att = 1.0;',
      'for(int i = 0; i < MIST_MS_OCTAVES; ++i){',
        'ph[i] = mix(hgIso(cosT, uPhaseG * att), hgIso(cosT, -0.25 * att), 0.25);',
        'att *= 0.5;',
      '}',
    '}',
    "//The sun's light scattered toward the eye at a sample whose optical depth to the sun is tau (replaces",
    '//phase x transmittance).',
    'float mistSunScatter(float tau, float phase0, float ph[MIST_MS_OCTAVES]){',
      'float old = phase0 * (exp(-tau) + 0.4 * exp(-0.2 * tau)) / 1.4;',
      'float ms = 0.0, ms0 = 0.0, a = 1.0, b = 1.0;',
      'for(int i = 0; i < MIST_MS_OCTAVES; ++i){ ms += a * exp(-tau * b) * ph[i]; ms0 += a * ph[i]; a *= 0.5; b *= 0.5; }',
      'ms = max(ms, uDiffusion / (1.0 + 0.11 * tau));',
      'return mix(old, phase0 * ms / max(ms0, 1e-6), uMultiScatter);',
    '}',

    "//The scene's sun shadow at a world point: four taps, no derivatives (this runs in a loop).",
    'float sunShadowMapAt(vec3 p){',
      'if(sunShadowEnabled == 0) return 1.0;',
      'vec4 sp = sunShadowMatrix * vec4(p, 1.0);',
      'vec3 sc = sp.xyz / sp.w;',
      'if(sc.z > 1.0 || sc.z < 0.0) return 1.0;',
      'vec2 edgeDist = min(sc.xy, vec2(1.0) - sc.xy);',
      'float edge = min(edgeDist.x, edgeDist.y);',
      'if(edge < 0.0) return 1.0;',
      'float refZ = sc.z + sunShadowBias;',
      'vec2 ts = (1.0 / sunShadowMapSize) * sunShadowRadius;',
      'float s = 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2(-0.5, -0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2( 0.5, -0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2(-0.5,  0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2( 0.5,  0.5) * ts).r ? 1.0 : 0.0;',
      'return mix(1.0, 0.25 * s, smoothstep(0.0, 0.05, edge));',
    '}',
    "//...times the clouds overhead, which shade the falls' foot like the pool round it.",
    'float sunShadowAt(vec3 p){',
      'return sunShadowMapAt(p) * starryCloudAt(p).x;',
    '}',

    '//Value noise PERIODIC along x with period `per` cells (a whole number): the time term is wrapped, and',
    '//noise that did not repeat at the wrap would jump every lump at once.',
    'float vnoise3p(vec3 x, float per){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'float x0 = mod(i.x, per), x1 = mod(i.x + 1.0, per);',
      'return mix(mix(mix(hash3(vec3(x0, i.y, i.z)),             hash3(vec3(x1, i.y, i.z)),             f.x),',
                     'mix(hash3(vec3(x0, i.y + 1.0, i.z)),       hash3(vec3(x1, i.y + 1.0, i.z)),       f.x), f.y),',
                 'mix(mix(hash3(vec3(x0, i.y, i.z + 1.0)),       hash3(vec3(x1, i.y, i.z + 1.0)),       f.x),',
                     'mix(hash3(vec3(x0, i.y + 1.0, i.z + 1.0)), hash3(vec3(x1, i.y + 1.0, i.z + 1.0)), f.x), f.y), f.z);',
    '}',
    'float fbmPer(vec3 p, int octaves, float per){',
      'float a = 0.5, s = 0.0, norm = 0.0;',
      'for(int i = 0; i < 4; i++){',
        'if(i >= octaves) break;',
        's += a * vnoise3p(p, per);',
        'norm += a;',
        'p = vec3(p.x * 2.0, p.y * 2.03 + 1.7, p.z * 2.03 + 3.1);   //x exactly x2 so the octave repeats too',
        'per *= 2.0;',
        'a *= 0.5;',
      '}',
      'return s / norm;',
    '}',

    '//The apex of a drop launched upward at v0 under gravity and quadratic drag, terminal speed vt:',
    '//waterfall-splash-hull.js apex (keep in step).',
    'const float GRAV = 9.81;',
    'const float TAU = 6.28318530718;',
    'const float SPLASH_PERIOD = 32.0;   //cells; the rising term of the noise repeats after this many',
    'float splashApex(float v0, float vt){',
      'return vt * vt / (2.0 * GRAV) * log(1.0 + v0 * v0 / (vt * vt));',
    '}',

    "//Perlin gradient noise (about -1..1), hashed gradients: for the fog's wander, once per fragment.",
    'vec3 perlinGrad(vec3 i){',
      'return vec3(hash3(i), hash3(i + 19.19), hash3(i + 47.11)) * 2.0 - 1.0;',
    '}',
    'float perlin3(vec3 x){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);',
      'return mix(mix(mix(dot(perlinGrad(i + vec3(0.0, 0.0, 0.0)), f - vec3(0.0, 0.0, 0.0)), dot(perlinGrad(i + vec3(1.0, 0.0, 0.0)), f - vec3(1.0, 0.0, 0.0)), u.x),',
                     'mix(dot(perlinGrad(i + vec3(0.0, 1.0, 0.0)), f - vec3(0.0, 1.0, 0.0)), dot(perlinGrad(i + vec3(1.0, 1.0, 0.0)), f - vec3(1.0, 1.0, 0.0)), u.x), u.y),',
                 'mix(mix(dot(perlinGrad(i + vec3(0.0, 0.0, 1.0)), f - vec3(0.0, 0.0, 1.0)), dot(perlinGrad(i + vec3(1.0, 0.0, 1.0)), f - vec3(1.0, 0.0, 1.0)), u.x),',
                     'mix(dot(perlinGrad(i + vec3(0.0, 1.0, 1.0)), f - vec3(0.0, 1.0, 1.0)), dot(perlinGrad(i + vec3(1.0, 1.0, 1.0)), f - vec3(1.0, 1.0, 1.0)), u.x), u.y), u.z);',
    '}',

    "//This fragment's blob, set once in main(): its frame, and how late the falling water is (s).",
    'vec3 gAxis, gE1, gE2;',
    'float gFallLag;',
    "//...and the foam fog's: its top (m) and where its middle has wandered to (in the blob's frame, m).",
    'float gFogTop;',
    'vec2 gFogWander;',
    "//The last splashDensity's shares from the falling skirt and the fog (debug).",
    'float gFallShare, gFogShare;',

    "//The launch speed at a point of the footprint, as a fraction of the blob's peak at its middle: the",
    '//pulse (three sines, phase scattered by 2D noise) times the height noise. Between 0 and 1, never 0.',
    'float splashPulse(vec2 lp, float t){',
      'float seed = vSplashA.w;',
      'float n = vnoise3(vec3(lp / max(uHeightScale, 1e-3) + seed * 41.3, t * uHeightDrift + seed * 13.0));',
      'float m = vnoise3(vec3(lp / max(uHeightScale, 1e-3) * 0.6 + seed * 73.1 + 11.5, t * uHeightDrift * 0.7 + 5.0));',
      'float ph = TAU * (fract(t * uPulseRate) + seed + uPulseScatter * m);',
      'float ph2 = TAU * (fract(t * uPulseRate * 1.618) + seed * 3.0 + uPulseScatter * m * 1.3);',
      'float ph3 = TAU * (fract(t * uPulseRate * 2.414) + seed * 7.0 + uPulseScatter * m * 0.7);',
      'float p = 0.5 + 0.25 * sin(ph) + 0.15 * sin(ph2) + 0.10 * sin(ph3);',
      'return mix(uPulseMin, 1.0, p) * mix(1.0 - uHeightNoise, 1.0, n);',
    '}',

    '//Density (1/m) at a world point for the blob this fragment belongs to: the column plus the',
    "//falling skirt round it. top (out): the height of the column there, as a fraction of the blob's highest.",
    'float splashDensity(vec3 p, int octaves, out float top){',
      'top = 0.0;',
      'vec3 q = p - vCenter.xyz;',
      'float z = dot(q, gAxis);',
      'if(z <= 0.0) return 0.0;',
      'vec3 perp = q - gAxis * z;',
      '//RADIAL: the drops fly out as well as up, along rays from a focus below the water (H / k under the',
      "//origin, k = vSplashC.z), so the splash opens 1 + k wide by the blob's highest top: a little",
      "//spherical symmetry. lp is the launch ring a sample's ray came from; rr the distance along the ray",
      '//(z on the axis), which the streaks run along.',
      'float Hmax = max(splashApex(vSplashA.x, vSplashC.y), 1e-3);',
      'float k = vSplashC.z;',
      'float spread = 1.0 + k * z / Hmax;',
      'vec2 lp = vec2(dot(perp, gE1), dot(perp, gE2)) / spread;',
      'float rr = k > 1e-3 ? length(q + gAxis * (Hmax / k)) - Hmax / k : z;',
      'float b = max(vSplashA.z, 1e-3);',
      'float dd = length(q) / vCenter.w;',
      'float window = clamp(1.0 - dd * dd, 0.0, 1.0);',
      'float ground = smoothstep(0.0, max(uGroundFade, 1e-3), p.y - vSplashC.x);',
      'float base = window * ground / (spread * spread);   //the same drops over a wider area',
      'float cell = max(uSplashScale, 1e-3);',
      'float stretchCell = cell * max(uStretch, 1.0);',
      'vec2 noiseXY = lp / cell + vSplashA.w * vec2(17.3, 9.1);',
      'float e = exp(-dot(lp, lp) / (2.0 * b * b));',
      'float mass = e * e;',

      '//The column: going up.',
      'float dCol = 0.0;',
      'float Z = splashApex(vSplashA.x * e * splashPulse(lp, t), vSplashC.y);',
      'top = Z / Hmax;',
      'if(Z > 1e-3){',
        'float hh = z / Z;',
        'float over = (z - Z) / max(uTopSoft, 1e-3);',
        'float col = hh <= 1.0 ? mix(uFill, 1.0, hh * hh) : exp(-over * over);',
        'float env = mass * col * base;',
        'if(env > 1e-3){',
          'float up = mod(rr / stretchCell - mod(t * uRiseRate, SPLASH_PERIOD) + vSplashA.w * SPLASH_PERIOD, SPLASH_PERIOD);',
          'float n = fbmPer(vec3(up, noiseXY), octaves, SPLASH_PERIOD);',
          'float lo = uErode + uErodeAge * min(hh, 1.0) + 0.25 * (1.0 - mass);',
          'dCol = env * smoothstep(lo, lo + max(uErodeSoft, 1e-3), n);',
        '}',
      '}',

      '//The falling skirt: coming down round it, late.',
      'float dFall = 0.0;',
      'float reach = 1.0 + max(vSplashC.w, 0.0);',
      'vec2 lpF = lp / reach;',
      'float eF = exp(-dot(lpF, lpF) / (2.0 * b * b));',
      'float ZF = uFallHeight * splashApex(vSplashA.x * eF * splashPulse(lpF, t - gFallLag), vSplashC.y);',
      'if(uFallDensity > 0.0 && ZF > 1e-3 && vSplashC.w > 0.0){',
        'float hf = z / ZF;',
        'float overF = (z - ZF) / max(uTopSoft, 1e-3);',
        'float colF = hf <= 1.0 ? mix(uFallFloor, 1.0, hf * hf) : exp(-overF * overF);',
        'float envF = uFallDensity * eF * eF / (reach * reach) * colF * (1.0 - mass) * base;',
        'if(envF > 1e-3){',
          'float down = mod(rr / stretchCell + mod(t * uRiseRate * uFallSpeed, SPLASH_PERIOD) + 13.0, SPLASH_PERIOD);',
          'float n = fbmPer(vec3(down, noiseXY * 1.3 + 5.7), max(octaves - 1, 1), SPLASH_PERIOD);',
          'float lo = uErode + uErodeAge + uFallErode;',
          'dFall = envF * smoothstep(lo, lo + max(uErodeSoft, 1e-3), n);',
        '}',
      '}',
      '//The foam fog: low, wide, calm, thinning with height.',
      'float dFog = 0.0;',
      'if(uFogDensity > 0.0 && gFogTop > 1e-3){',
        'vec2 lpG = vec2(dot(perp, gE1), dot(perp, gE2)) - gFogWander;',
        'float hz = z / gFogTop;',
        'float open = 1.0 + uFogSpread * min(hz, 1.5);',
        'float wG = b * max(uFogWidth, 1e-3) * open;',
        'float eG = exp(-dot(lpG, lpG) / (2.0 * wG * wG));',
        'float overG = max(z - gFogTop, 0.0) / max(2.0 * uTopSoft, 1e-3);',
        'float vert = exp(-uFogFade * min(hz, 1.0)) * exp(-overG * overG);',
        'float envG = uFogDensity * eG * vert / (open * open) * window * ground;',
        "//Pulses rolling out with the pool's waves (squared: puffs with thin gaps, not a ripple).",
        'float pulse = 0.5 + 0.5 * sin(uRingWave.x * length(lpG) - uRingWave.y * uFogPulseSlow * t + vSplashA.w * TAU);',
        'envG *= mix(1.0, pulse * pulse * 1.6, uFogPulseDepth);',
        'if(envG > 1e-3){',
          'float cellG = max(uFogScale, 1e-3);',
          'float upG = mod(z / cellG - mod(t * uFogRise / cellG, SPLASH_PERIOD) + vSplashA.w * SPLASH_PERIOD, SPLASH_PERIOD);',
          'float n = fbmPer(vec3(upG, lpG / cellG + vSplashA.w * vec2(5.3, 23.9)), max(octaves - 1, 1), SPLASH_PERIOD);',
          'dFog = envG * smoothstep(uFogErode, uFogErode + max(uFogSoft, 1e-3), n);',
        '}',
      '}',
      'float d = dCol + dFall + dFog;',
      'gFallShare = d > 0.0 ? dFall / d : 0.0;',
      'gFogShare = d > 0.0 ? dFog / d : 0.0;',
      'return uSplashDensity * vSplashB.w * d;',
    '}',

    '//── The surface mist ────────────────────────────────────────────────────────',
    '//2D value noise and an fbm whose octaves are each ROTATED (so a stretched pattern shows no grid):',
    '//the layer is a few inches thick, it needs no third axis, and this is half the work of vnoise3.',
    'float hash2(vec2 p){',
      'p = fract(p * vec2(0.3183099, 0.3678794) + 0.1);',
      'p *= 17.0;',
      'return fract(p.x * p.y * (p.x + p.y));',
    '}',
    'float vnoise2(vec2 x){',
      'vec2 i = floor(x);',
      'vec2 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'return mix(mix(hash2(i), hash2(i + vec2(1.0, 0.0)), f.x), mix(hash2(i + vec2(0.0, 1.0)), hash2(i + vec2(1.0, 1.0)), f.x), f.y);',
    '}',
    'float fbm2Rot(vec2 p){',
      'const mat2 ROT = mat2(0.8, 0.6, -0.6, 0.8);',
      'float a = 0.5, s = 0.0, norm = 0.0;',
      'for(int i = 0; i < 3; i++){',
        's += a * vnoise2(p);',
        'norm += a;',
        'p = ROT * p * 2.03 + vec2(1.7, 9.2);',
        'a *= 0.5;',
      '}',
      'return s / norm;',
    '}',

    '//The nearest drawn landing segment ON THIS POOL (its level within a metre or so of `level`; the step',
    "//above or below is not this mist's): distance (m), the downstream weight, its parameters.",
    'float smLine(vec2 xz, float level, out float side, out vec4 prm){',
      'float best = 1.0e12;',
      'vec2 bdv = vec2(0.0);',
      'prm = vec4(0.0);',
      'for(int i = 0; i < FALL_RINGS_N; ++i){',
        'if(float(i) >= fallRingCount) break;',
        'if(abs(fallRingExtra[i].x - level) > 1.0) continue;',
        'vec4 s = fallRingSeg[i];',
        'vec2 ab = s.zw - s.xy;',
        'vec2 dv = xz - (s.xy + ab * clamp(dot(xz - s.xy, ab) / max(dot(ab, ab), 1.0e-6), 0.0, 1.0));',
        'float d2 = dot(dv, dv);',
        'if(d2 < best){ best = d2; bdv = dv; prm = fallRingParam[i]; }',
      '}',
      'float d = sqrt(best);',
      'side = dot(prm.yz, prm.yz) < 0.01 ? 1.0 : smoothstep(-0.35, 0.45, dot(bdv, prm.yz) / max(d, 0.5));',
      'return d;',
    '}',

    '//Density (1/m) of the surface mist at p, over water at `level` (m), for a line of this strength and size.',
    'float surfaceMistDensity(vec3 p, float level, float strength, float size){',
      'float side;',
      'vec4 prm;',
      'float d = smLine(p.xz, level, side, prm);',
      'float sz = max(size, 0.05);',
      'float R = max(uSMReach * sz, 0.1);',
      'if(side <= 0.0 || d >= R || prm.x <= 0.0) return 0.0;',
      '//Above the still level (not riding the waves, see the header).',
      'float y = p.y - level;',
      'if(y < -0.02) return 0.0;',
      'float vert = exp(-max(y, 0.0) / max(uSMHeight, 0.01)) * smoothstep(-0.02, 0.04, y);',
      'float base = clamp(uSMBase, 0.0, 1.0);',
      'float falloff = (1.0 - base) * exp(-d / max(uSMDecay * sz, 0.05)) + base * exp(-d / max(uSMBaseDecay * sz, 0.05));',
      'float horiz = side * (1.0 - exp(-d / 0.6)) * falloff * (1.0 - smoothstep(0.7 * R, R, d));',
      '//Bands rolling out with the waves (squared: puffs with thin gaps), the gaps no thinner than the base.',
      'float pulse = 0.5 + 0.5 * sin(fallRingWave.x * d - fallRingWave.y * uSMPulseSlow * t + prm.w * TAU);',
      'float bands = max(mix(1.0, 1.6 * pulse * pulse, uSMPulseDepth), base);',
      "//Wisps: in the line's frame (across, outward), stretched and streaming outward, warped across.",
      'vec2 nrm = dot(prm.yz, prm.yz) > 0.01 ? prm.yz : vec2(0.0, 1.0);',
      'float across = dot(p.xz, vec2(-nrm.y, nrm.x));',
      'float outward = dot(p.xz, nrm);',
      'float cell = max(uSMScale, 0.05);',
      '//The warp drifts (its pattern slides along the line), so the streaks writhe as they stream out.',
      'float warp = (vnoise2(p.xz / (4.0 * cell) + vec2(t * uSMDrift, 3.7 + prm.w * 11.0)) - 0.5) * 2.0 * uSMWarp;',
      'vec2 q = vec2((across + warp) / cell, (outward - t * uSMWispSpeed) / (cell * max(uSMWispStretch, 1.0)) + prm.w * 11.0);',
      'float n = fbm2Rot(q);',
      'float wisp = smoothstep(uSMErode, uSMErode + max(uSMWispSoft, 0.01), n);',
      'return uSMDensity * strength * vert * horiz * bands * wisp;',
    '}',

    "//The surface mist's fragment: march the view ray through the box's thin layer.",
    "//vCenter.xyz the box's middle; vSplashA.xyz its half extents, w a seed; vSplashB.x the water's level, .y the strength, .z the size.",
    'void surfaceMistMain(){',
      'vec3 C = vCenter.xyz;',
      'vec3 hE = vSplashA.xyz;',
      'float level = vSplashB.x;',
      'float strength = vSplashB.y;',
      'vec3 camToX = vWorldPos - cameraPosition;',
      'float distX = length(camToX);',
      'vec3 rd = camToX / max(distX, 1e-4);',
      '//The layer: the box across, from the level to a few e-folds over it.',
      'vec3 bmin = vec3(C.x - hE.x, level - 0.05, C.z - hE.z);',
      'vec3 bmax = vec3(C.x + hE.x, level + 5.0 * uSMHeight, C.z + hE.z);',
      'vec3 r = mix(rd, vec3(1e-6), lessThan(abs(rd), vec3(1e-6)));',
      'vec3 ta = (bmin - cameraPosition) / r, tb = (bmax - cameraPosition) / r;',
      'vec3 tmn = min(ta, tb), tmx = max(ta, tb);',
      'float t0 = max(max(max(tmn.x, tmn.y), tmn.z), 0.0);',
      'float t1 = min(min(tmx.x, tmx.y), tmx.z);',
      'if(t1 <= t0 + 1e-3) discard;',
      'float L = t1 - t0;',
      'int nSteps = int(clamp(uSMSteps, 4.0, float(MAX_STEPS)));',
      'float dt = L / float(nSteps);',
      'float jitter = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));',
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',
      'float gRaw = texture2D(refractionDepthTexture, screenUV).r;',
      'float sceneDepth = 1e6;',
      'if(gRaw < 1.0){',
        'vec4 gv = inverseProjectionMatrix * vec4(screenUV * 2.0 - 1.0, gRaw * 2.0 - 1.0, 1.0);',
        'sceneDepth = -gv.z / gv.w;',
      '}',
      'vec3 Lsun = -normalize(brightestDirectionalLightDirection);',
      'float phase = mistPhase(dot(rd, Lsun));',
      'vec3 sunCol = INV_PI * brightestDirectionalLight * uSunGain * landLightVisibilityOpen(vWorldPos, Lsun);',
      '//UNITS: irradiance -> radiance, the 1/PI the sun term has (INV_PI) (ambientPiFix, 2026-10-02).',
      'vec3 ambient = skyAmbientColor * uAmbient * nightDim() * landSkyVisibilityOpen(vWorldPos.xz) * mix(1.0, INV_PI, ambientPiFix);',
      "//Thin: one light for the whole chord (the scene's shadow at its middle, no sun march of its own).",
      'vec3 scatter = uAlbedo * (sunCol * phase * sunShadowAt(cameraPosition + rd * (t0 + 0.5 * L)) * fallShadowAt(cameraPosition + rd * (t0 + 0.5 * L)) + ambient);',
      'float Tr = 1.0;',
      'for(int i = 0; i < MAX_STEPS; i++){',
        'if(i >= nSteps) break;',
        'float along = t0 + dt * (float(i) + jitter);',
        'vec3 p = cameraPosition + rd * along;',
        'float dens = surfaceMistDensity(p, level, strength, vSplashB.z);',
        'if(dens <= 1e-4) continue;',
        'float viewDepth = vViewDepth * along / max(distX, 1e-4);',
        'float sigma = dens * clamp((sceneDepth - viewDepth) / max(uSoftRange, 1e-3), 0.0, 1.0);',
        'if(sigma <= 1e-5) continue;',
        'Tr *= exp(-sigma * dt);',
        'if(Tr < 0.01) break;',
      '}',
      'float alpha = (1.0 - Tr) * uSplashOpacity;',
      'if(uDebugMode == 0 && alpha < 0.003) discard;',
      'vec3 color = scatter;',
      '#if($atmospheric_perspective_enabled)',
        'if(underwaterFactor < 0.5) color = applyAtmosphericPerspective(color, cameraPosition + rd * (t0 + 0.5 * L));',
      '#endif',
      'gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(color), alpha));',
      '//$DEBUG_START$',
      'if(uDebugMode == 4) gl_FragColor = vec4(0.9, 0.5, 0.1, 0.25);                                   //the surface mist boxes (orange)',
      'else if(uDebugMode == 1) gl_FragColor = vec4(vec3(1.0 - Tr), 1.0);',
      '//$DEBUG_END$',
      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',

    'void main(){',
      'if(uSurfaceMist > 0.5){ surfaceMistMain(); return; }',
      'vec3 C = vCenter.xyz;',
      'float R = max(vCenter.w, 1e-3);',
      'vec3 camToX = vWorldPos - cameraPosition;',
      'float distX = length(camToX);',
      'vec3 rd = camToX / max(distX, 1e-4);',

      "//The chord of the view ray through the blob's sphere, never behind the camera.",
      'vec3 oc = cameraPosition - C;',
      'float bq = dot(oc, rd);',
      'float disc = bq * bq - (dot(oc, oc) - R * R);',
      '//$DEBUG_START$',
      'if(uDebugMode == 4){ gl_FragColor = vec4(0.2, 0.9, 0.9, disc > 0.0 ? 0.35 : 0.08); return; }   //the blobs: sphere (bright), proxy (faint)',
      '//$DEBUG_END$',
      'if(disc <= 0.0) discard;',
      'float sq = sqrt(disc);',
      'float t0 = max(-bq - sq, 0.0);',
      'float L = (-bq + sq) - t0;',
      'if(L < 1e-3) discard;',

      'gAxis = normalize(vSplashB.xyz);',
      'gE1 = normalize(cross(gAxis, abs(gAxis.x) < 0.9 ? vec3(1.0, 0.0, 0.0) : vec3(0.0, 0.0, 1.0)));',
      'gE2 = cross(gAxis, gE1);',
      "//The falling water left the top this long ago: uFallDelay x the middle drop's fall from its apex.",
      'float vr = vSplashA.x / max(vSplashC.y, 0.1);',
      'gFallLag = uFallDelay * vSplashC.y / GRAV * log(sqrt(1.0 + vr * vr) + vr);',
      "//The foam fog: its top follows a damped, late share of the column's pulse at the middle; its middle",
      '//wanders round the landing by Perlin noise.',
      'gFogTop = uFogHeight * splashApex(vSplashA.x * mix(1.0, splashPulse(vec2(0.0), t - uFogLag), uFogPulse), vSplashC.y);',
      'float tw = t * uFogDrift + vSplashA.w * 61.0;',
      'gFogWander = vSplashA.z * uFogWander * 1.6 * vec2(perlin3(vec3(tw, vSplashA.w * 37.0, 0.5)), perlin3(vec3(tw, vSplashA.w * 37.0, 9.5)));',

      '//The splash is a low body in a wide sphere: clip the chord to the slab between the water and the',
      '//highest the blob ever throws, so the steps are spent where there is spray.',
      'float topMax = splashApex(vSplashA.x, vSplashC.y) + 3.0 * uTopSoft;',
      'float zc = dot(cameraPosition - C, gAxis);',
      'float zr = dot(rd, gAxis);',
      'float t1 = t0 + L;',
      'if(abs(zr) > 1e-4){',
        'float ta = -zc / zr, tb = (topMax - zc) / zr;',
        't0 = max(t0, min(ta, tb));',
        't1 = min(t1, max(ta, tb));',
      '}',
      'else if(zc < 0.0 || zc > topMax) discard;',
      'L = t1 - t0;',
      'if(L < 1e-3) discard;',

      'int nSteps = int(clamp(uSteps, 4.0, float(MAX_STEPS)));',
      'float dt = L / float(nSteps);',
      'float jitter = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));',

      '//What the ground behind says: view depth of the nearest opaque thing along this pixel.',
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',
      'float gRaw = texture2D(refractionDepthTexture, screenUV).r;',
      'float sceneDepth = 1e6;',
      'if(gRaw < 1.0){',
        'vec4 gv = inverseProjectionMatrix * vec4(screenUV * 2.0 - 1.0, gRaw * 2.0 - 1.0, 1.0);',
        'sceneDepth = -gv.z / gv.w;',
      '}',

      'vec3 Lsun = -normalize(brightestDirectionalLightDirection);   //toward the sun',
      'float phase = mistPhase(dot(rd, Lsun));',
      'float phOct[MIST_MS_OCTAVES];',
      'mistPhaseOctaves(dot(rd, Lsun), phOct);',
      'vec3 sunCol = INV_PI * brightestDirectionalLight * uSunGain * landLightVisibilityOpen(vWorldPos, Lsun);',
      '//UNITS: irradiance -> radiance, the 1/PI the sun term has (INV_PI) (ambientPiFix, 2026-10-02).',
      'vec3 ambient = skyAmbientColor * uAmbient * nightDim() * landSkyVisibilityOpen(vWorldPos.xz) * mix(1.0, INV_PI, ambientPiFix);',

      'float Tr = 1.0;',
      'vec3 acc = vec3(0.0);',
      'float lightStep = uLightLength / max(uLightSteps, 1.0);',
      'int nLight = int(clamp(uLightSteps, 1.0, float(MAX_LIGHT_STEPS)));',
      'float topF;',

      'for(int i = 0; i < MAX_STEPS; i++){',
        'if(i >= nSteps) break;',
        'float along = t0 + dt * (float(i) + jitter);   //metres from the camera',
        'vec3 p = cameraPosition + rd * along;',
        'float dens = splashDensity(p, 3, topF);',
        'if(dens <= 0.002) continue;',

        '//Occlusion: the ground behind (view depth along the ray is linear in distance).',
        'float viewDepth = vViewDepth * along / max(distX, 1e-4);',
        'float sigma = dens * clamp((sceneDepth - viewDepth) / max(uSoftRange, 1e-3), 0.0, 1.0);',
        'if(sigma <= 1e-4) continue;',

        '//Self-shadowing: march toward the sun through the same burst (two octaves).',
        'float tauL = 0.0;',
        'for(int k = 0; k < MAX_LIGHT_STEPS; k++){',
          'if(k >= nLight) break;',
          'vec3 q = p + Lsun * lightStep * (float(k) + 0.5 + 0.5 * jitter);',
          'tauL += splashDensity(q, 2, topF) * lightStep;',
        '}',
        'tauL *= uAbsorption;',
        '//The direct light and the light scattered round the burst (mistSunScatter: the octaves, step 4b).',
        'vec3 scatter = uAlbedo * (sunCol * mistSunScatter(tauL, phase, phOct) * sunShadowAt(p) * fallShadowAt(p) + ambient);',

        'float stepT = exp(-sigma * dt);',
        'acc += Tr * (1.0 - stepT) * scatter;',
        'Tr *= stepT;',
        'if(Tr < 0.01) break;',
      '}',

      'float alpha = (1.0 - Tr) * uSplashOpacity;',
      'if(uDebugMode == 0 && alpha < 0.003) discard;',
      'vec3 color = acc / max(1.0 - Tr, 1e-4);',
      'vec3 mid = cameraPosition + rd * (t0 + 0.5 * L);',
      '#if($atmospheric_perspective_enabled)',
        'if(underwaterFactor < 0.5) color = applyAtmosphericPerspective(color, mid);',
      '#endif',
      'gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(color), alpha));',

      '//$DEBUG_START$',
      'if(uDebugMode == 1) gl_FragColor = vec4(vec3(1.0 - Tr), 1.0);                                   //opacity',
      'else if(uDebugMode == 3) gl_FragColor = vec4(vec3(clamp(vSplashB.w / 3.0, 0.0, 1.0)), 1.0);     //strength (white at 3)',
      'else if(uDebugMode == 6){                                                                       //at mid-chord: the column (red), the falling skirt (green), the foam fog (blue)',
        'float dm = splashDensity(mid, 1, topF);',
        'gl_FragColor = vec4(dm > 0.0 ? vec3(1.0 - gFallShare - gFogShare, gFallShare, gFogShare) : vec3(0.0), 1.0);',
      '}',
      "else if(uDebugMode == 2 || uDebugMode == 5){                                                    //the column height at mid-chord, as a fraction of the blob's highest (watch it pulse)",
        'splashDensity(mid, 1, topF);',
        'gl_FragColor = vec4(vec3(topF), 1.0);',
      '}',
      '//$DEBUG_END$',

      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',
    ];
    const updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedCode = originalGLSL[i];
      updatedCode = updatedCode.replace(/\$atmospheric_perspective_enabled/g, atmosphericPerspectiveEnabled ? '1' : '0');
      if(atmosphericPerspectiveEnabled && atmosphereFunctionsGLSL && updatedCode.indexOf('//ATMOSPHERE_FUNCTIONS_INJECTION_POINT') !== -1){
        updatedCode = atmosphereFunctionsGLSL;
      }
      updatedLines.push(updatedCode);
    }
    return updatedLines.join('\n');
  },

  vertexShader: [
    'precision highp float;',

    '//Waterfall splash vertex stage. The mesh is the set of BLOBS ARestlessOcean.WaterfallSplashHull',
    "//builds at the falls' landings: an icosahedron round each blob's sphere. Nothing is displaced here;",
    "//the stage hands the fragment stage the blob's sphere and its burst (the same values at every",
    '//vertex of a blob, so they arrive unchanged).',

    "attribute vec4 aCenter;    //the blob's origin (the landing, on the water's surface) and its radius (m)",
    "attribute vec4 aSplashA;   //launch speed at the middle (m/s), the pulse's period (s), the impact's width b (m), seed",
    "attribute vec4 aSplashB;   //the burst's up axis (unit), strength",
    "attribute vec4 aSplashC;   //level (nothing below this height), terminal speed (m/s), radial spread k (the hull's fan), fall reach (the hull's fallReach)",

    'varying vec3 vWorldPos;',
    'varying vec4 vCenter;',
    'varying vec4 vSplashA;',
    'varying vec4 vSplashB;',
    'varying vec4 vSplashC;',
    'varying float vViewDepth;',

    '#include <fog_pars_vertex>',

    'void main(){',
      'vec4 worldPos = modelMatrix * vec4(position, 1.0);',
      'vWorldPos = worldPos.xyz;',
      'vCenter = vec4((modelMatrix * vec4(aCenter.xyz, 1.0)).xyz, aCenter.w);',
      'vSplashA = aSplashA;',
      'vSplashB = aSplashB;',
      'vSplashC = aSplashC;',
      'vec4 mvPosition = viewMatrix * worldPos;',
      'vViewDepth = -mvPosition.z;',
      '//The fog chunk reads `mvPosition` and `transformed` by those names (see waterfall-sheet-vertex.glsl).',
      '#ifdef USE_FOG',
        'vec3 transformed = position;',
      '#endif',
      '#include <fog_vertex>',
      'gl_Position = projectionMatrix * mvPosition;',
    '}',
  ].join('\n'),
};
