//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
//
//Waterfall mist (volumetric). The SHARED block is replaced at init by the flowing-water
//material's own uniform objects (WaterfallMistPass.init aliases them, as the sheet does), so the
//mist is lit by exactly the sun, sky, shadow and atmosphere the fall and the creek are. The
//defaults here only matter if the mist is ever drawn without a flowing surface.
ARestlessOcean.Materials.Ocean.waterfallMistMaterial = {
  uniforms: {
    //SHARED with the flowing-water material
    brightestDirectionalLight: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    brightestDirectionalLightDirection: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    skyAmbientColor: {value: new THREE.Vector3(0.3, 0.4, 0.5)},
    t: {value: 0.0},
    sunShadowMap: {value: null},
    sunShadowMatrix: {value: new THREE.Matrix4()},
    sunShadowMapSize: {value: new THREE.Vector2(2048.0, 2048.0)},
    sunShadowRadius: {value: 1.0},
    sunShadowBias: {value: 0.0},
    sunShadowEnabled: {value: 0},
    refractionDepthTexture: {value: null},
    inverseProjectionMatrix: {value: new THREE.Matrix4()},
    screenResolution: {value: new THREE.Vector2(1920.0, 1080.0)},
    underwaterFactor: {value: 0.0},
    atmosphereTransmittance: {value: null},
    atmosphereMieInscattering: {value: null},
    atmosphereRayleighInscattering: {value: null},
    atmSunPosition: {value: new THREE.Vector3(0.0, 1.0, 0.0)},
    atmMoonPosition: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    atmSunHorizonFade: {value: 1.0},
    atmMoonHorizonFade: {value: 0.0},
    atmScatteringSunIntensity: {value: 1.0},
    atmScatteringMoonIntensity: {value: 0.0},
    atmMoonLightColor: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    atmCameraHeight: {value: 0.0},
    atmDistanceScale: {value: 1.0},

    //Scene fog (see waterfall-sheet-template.txt: the material is fog:true)
    fogNear: {value: 1.0},
    fogFar: {value: 1000.0},
    fogDensity: {value: 0.00025},
    fogColor: {value: new THREE.Color()},
    uwSunDir: {value: new THREE.Vector3(0.0, -1.0, 0.0)},

    //The mist's own. FUDGE: all look choices, none a plume model.
    uMistDensity: {value: 1.1},
    uMistScale: {value: 0.7},
    uMistStretch: {value: 6.0},
    uMistSpeed: {value: 7.0},
    uMistLoop: {value: 3.0},
    uErode: {value: 0.42},
    uMistPlumeHeight: {value: 3.0},
    uMistPlumeStretch: {value: 1.5},
    uAerationLo: {value: 0.15},
    uAerationHi: {value: 0.7},
    uSteps: {value: 24.0},
    uLightSteps: {value: 3.0},
    uLightLength: {value: 1.5},
    uAbsorption: {value: 1.0},
    uPhaseG: {value: 0.7},
    uAmbient: {value: 1.0},
    uSunGain: {value: 1.0},
    uAlbedo: {value: new THREE.Vector3(0.95, 0.97, 1.0)},
    uMaxChord: {value: 8.0},
    uSoftRange: {value: 0.6},
    uSheetOcclusion: {value: 0.85},
    uMistOpacity: {value: 1.0},
    uDebugMode: {value: 0},
  },

  //Built like the sheet's (waterfall-sheet-template.txt): $atmospheric_perspective_enabled is
  //substituted, and with it on the atmosphere functions replace the injection marker line.
  //WaterfallMistPass rebuilds it when atmospheric perspective becomes ready.
  fragmentShader: function(atmosphericPerspectiveEnabled, atmosphereFunctionsGLSL){
    const originalGLSL = [
    'precision highp float;',

    '//Waterfall mist fragment stage: a raymarched volume in the hull ARestlessOcean.WaterfallMistHull',
    '//builds round the curtain (a curved cone that widens as the water falls and opens out at the foot).',
    '//',
    '//WHAT IT DRAWS. The hull is closed and wound outward; the material culls its FRONT faces, so',
    '//each fragment is the point X where a view ray LEAVES the hull. From X the stage marches back',
    '//toward the camera (never past it: the camera may be inside the cone) over the length of the',
    '//chord, and integrates the volume front to back. Nothing is drawn where the density is nil, so',
    "//the hull's walls are never seen: the density falls to zero at every wall by construction.",
    '//',
    "//THE DENSITY, in the curtain's own frame (metres from the row's centre point along its normal,",
    '//across and down the flow, so the noise is continuous over the hull however the curtain bends):',
    "//  envelope  radial (1 - x^2)^2 across the cone's half-thickness, lateral fade past the curtain's",
    "//            edges, a smooth fade over the hull's foot (distance run on past the landing), and an intensity that",
    "//            rises with the nappe's AERATION: the mist comes up as the sheet turns to air and",
    '//            spray, which is also where the sheet fades out.',
    '//  noise     looping 3D value noise, STRETCHED along the flow (uMistStretch) and advected down it',
    '//            at uMistSpeed, so the lumps are streaks rushing down. It loops by cross-fading two',
    "//            copies half a period apart (the creek's ripple trick), no seam, no texture.",
    "//  The erosion carves it into clumps where the envelope is thin, the way a cloud's edge is.",
    '//',
    '//THE LIGHT. Each sample marches a few steps toward the sun for its own SELF-SHADOWING (Beer-',
    '//Lambert, with a cheap multiple-scatter floor so the shaded side is not black), takes a dual-lobe',
    "//Henyey-Greenstein phase (forward-scattering: a backlit fall glows), the scene's sun shadow map",
    "//(a cliff in front of the sun shades the mist), and the sky's ambient. Units are the sheet's:",
    '//a white Lambert surface under the sun is INV_PI * brightestDirectionalLight.',
    '//',
    "//OCCLUSION. The material does not depth-test: the hull straddles the curtain, and the curtain's",
    '//own depth would hide the half of the mist in front of it. Instead (1) the terrain and everything',
    '//else in the refraction G-buffer clip the march (soft, uSoftRange), (2) the curtain is treated as',
    '//the opaque plane it nearly is: samples on the far side of it from the camera are dropped inside',
    "//the curtain's width (uSheetOcclusion), and (3) the hull is held above the water it lands in.",
    '//',
    '//ATMOSPHERE and fog exactly as the sheet does them (see waterfall-sheet.glsl).',

    'uniform vec3 brightestDirectionalLight;',
    'uniform vec3 brightestDirectionalLightDirection;   //from the sun TOWARD the scene',
    'uniform vec3 skyAmbientColor;',
    'uniform float t;',

    'uniform sampler2D sunShadowMap;',
    'uniform mat4 sunShadowMatrix;',
    'uniform vec2 sunShadowMapSize;',
    'uniform float sunShadowRadius;',
    'uniform float sunShadowBias;',
    'uniform int sunShadowEnabled;',

    'uniform sampler2D refractionDepthTexture;',
    'uniform mat4 inverseProjectionMatrix;',
    'uniform vec2 screenResolution;',
    'uniform float underwaterFactor;',

    'uniform float uMistDensity;      //1/m extinction at full density',
    'uniform float uMistScale;        //m per noise cell across the flow',
    'uniform float uMistStretch;      //noise cells stretched this much along the flow',
    'uniform float uMistSpeed;        //m/s the lumps rush down the flow',
    'uniform float uMistLoop;         //s per cross-fade period of the loop',
    'uniform float uErode;            //0..1: how deep the noise carves into the envelope',
    'uniform float uMistPlumeHeight;  //m above the landing over which the curtain gives way to the plume',
    'uniform float uMistPlumeStretch; //noise stretch in the plume (1: round puffs)',
    'uniform float uAerationLo;       //aeration where the mist starts to appear',
    'uniform float uAerationHi;       //aeration where it is full',
    'uniform float uSteps;            //view-ray steps',
    'uniform float uLightSteps;       //sun-ray steps',
    'uniform float uLightLength;      //m the sun ray reaches',
    "uniform float uAbsorption;       //sun-ray extinction as a multiple of the view's",
    'uniform float uPhaseG;           //forward lobe of the phase function',
    'uniform float uAmbient;          //sky fill',
    'uniform float uSunGain;          //sun scatter gain',
    "uniform vec3 uAlbedo;            //single-scatter albedo (the mist's tint)",
    'uniform float uMaxChord;         //m, longest run marched through the cone',
    'uniform float uSoftRange;        //m of depth over which the mist fades into the ground',
    'uniform float uSheetOcclusion;   //0..1: how opaque the curtain is to the mist behind it',
    'uniform float uMistOpacity;',
    'uniform int uDebugMode;',

    'varying vec3 vWorldPos;',
    'varying vec3 vCenter;',
    'varying vec3 vN;',
    'varying vec3 vT;',
    'varying vec3 vA;',
    'varying vec4 vMistA;   //s, across (m), layer, radius',
    'varying vec4 vMistB;   //aeration, foot fade length (m), free-fall flag, half-width',
    "varying vec3 vEnd;     //the strand's landing point",
    'varying vec2 vEndDir;  //the horizontal direction the water runs at the landing',
    'varying float vViewDepth;',

    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_fragment>',
    '#endif',
    '#if($atmospheric_perspective_enabled)',
      'precision highp sampler3D;',
      'uniform sampler2D atmosphereTransmittance;',
      'uniform sampler3D atmosphereMieInscattering;',
      'uniform sampler3D atmosphereRayleighInscattering;',
      'uniform vec3 atmSunPosition;',
      'uniform vec3 atmMoonPosition;',
      'uniform float atmSunHorizonFade;',
      'uniform float atmMoonHorizonFade;',
      'uniform float atmScatteringSunIntensity;',
      'uniform float atmScatteringMoonIntensity;',
      'uniform vec3 atmMoonLightColor;',
      'uniform float atmCameraHeight;',
      'uniform float atmDistanceScale;',

      '//ATMOSPHERE_FUNCTIONS_INJECTION_POINT',

      '//Lifted verbatim from waterfall-sheet.glsl (keep in step). The injected functions are the LUT',
      '//helpers only; the sheet and the creek each define their own applyAtmosphericPerspective on top.',
      '//Atmospheric perspective for ground-level surfaces.',
      '//Uses distance-based extinction with LUT-sampled multi-scattered inscattering.',
      '//At the same height: S(A->B) = S(A->inf) * (1 - T(A->B))',
      'vec3 applyAtmosphericPerspective(vec3 color, vec3 worldPos){',
        'vec3 worldViewDir = normalize(worldPos - cameraPosition);',
        "//Convert view direction from THREE.js world space to a-starry-sky's coordinate",
        '//system. Sun world direction = (-sp.z, sp.y, -sp.x) from quadOffset, so the',
        '//inverse transform from world to sky coords is: skyDir = (-world.z, world.y, -world.x)',
        'vec3 viewDir = vec3(-worldViewDir.z, worldViewDir.y, -worldViewDir.x);',
        'float dist = length(worldPos - cameraPosition) * METERS_TO_KM * atmDistanceScale;',

        '//Distance-based extinction along the camera-to-surface path',
        'vec3 extinction = exp(-(RAYLEIGH_BETA + EARTH_MIE_BETA_EXTINCTION) * dist);',

        '//Attenuate surface color',
        'color *= extinction;',

        '//LUT coordinates for inscattering lookup',
        'float viewCosZenith = max(viewDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscattering from 3D LUTs',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(viewDir, atmSunPosition);',
        'vec3 fogSun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun)',
                    '* (1.0 - extinction);',

        '//Moon inscattering from 3D LUTs',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(viewDir, atmMoonPosition);',
        'vec3 fogMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon)',
                     '* (1.0 - extinction);',

        'return color + fogSun + fogMoon;',
      '}',
    '#endif',

    '//(No PI of our own: the injected atmosphere functions declare one; a second is a link error.)',
    'const float INV_PI = 0.31830988618;',
    'const int MAX_STEPS = 64;',
    'const int MAX_LIGHT_STEPS = 8;',

    '//── Copied from waterfall-sheet.glsl (keep in step) ───────────────────────────',
    "//Applied to AP's output as the sheet does: the sheet and its mist then tone-map alike.",
    'vec4 linearTosRGB(vec4 value){',
      'return vec4(mix(pow(value.rgb, vec3(0.41666)) * 1.055 - vec3(0.055), value.rgb * 12.92, vec3(lessThanEqual(value.rgb, vec3(0.0031308)))), value.a);',
    '}',
    'vec3 aroAESFilmicToneMapping(vec3 color){',
      'return clamp((color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14), 0.0, 1.0);',
    '}',
    '//──────────────────────────────────────────────────────────────────────────────',

    "//── Noise: ocean-splash.glsl's hash3 / vnoise3 ────────────────────────────────",
    'float hash3(vec3 p){',
      'p = fract(p * 0.3183099 + 0.1);',
      'p *= 17.0;',
      'return fract(p.x * p.y * p.z * (p.x + p.y + p.z));',
    '}',
    'float vnoise3(vec3 x){',
      'vec3 i = floor(x);',
      'vec3 f = fract(x);',
      'f = f * f * (3.0 - 2.0 * f);',
      'return mix(mix(mix(hash3(i + vec3(0.0, 0.0, 0.0)), hash3(i + vec3(1.0, 0.0, 0.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 0.0)), hash3(i + vec3(1.0, 1.0, 0.0)), f.x), f.y),',
                 'mix(mix(hash3(i + vec3(0.0, 0.0, 1.0)), hash3(i + vec3(1.0, 0.0, 1.0)), f.x),',
                     'mix(hash3(i + vec3(0.0, 1.0, 1.0)), hash3(i + vec3(1.0, 1.0, 1.0)), f.x), f.y), f.z);',
    '}',
    'float fbmOct(vec3 p, int octaves){',
      'float a = 0.5, s = 0.0, norm = 0.0;',
      'for(int i = 0; i < 4; i++){',
        'if(i >= octaves) break;',
        's += a * vnoise3(p);',
        'norm += a;',
        'p = p * 2.03 + vec3(1.7, 9.2, 3.1);',
        'a *= 0.5;',
      '}',
      'return s / norm;',
    '}',

    "//The curtain's frame at this fragment, metres from the row's centre.",
    'struct MistCoord { float u; float w; float h; };',
    'MistCoord mistCoord(vec3 p, vec3 N, vec3 T, vec3 A){',
      'vec3 d = p - vCenter;',
      'MistCoord c;',
      'c.h = dot(d, N);',
      'c.u = vMistA.x + dot(d, T);',
      'c.w = vMistA.y + dot(d, A);',
      'return c;',
    '}',

    '//How much this point is in the PLUME at the foot rather than in the falling curtain: 1 at the',
    '//landing, 0 uMistPlumeHeight metres above it. The plume is billowy where the curtain is streaky:',
    '//less stretch, gentler erosion, a fuller envelope.',
    'float mistPlume(vec3 p){',
      'return 1.0 - smoothstep(0.0, max(uMistPlumeHeight, 1e-3), p.y - vEnd.y);',
    '}',

    "//Looping advected noise: two copies half a period apart, cross-faded (creekRippleSlope's trick).",
    'float mistNoise(MistCoord c, float plume, int octaves){',
      'float ra = fract(t / uMistLoop);',
      'float rb = fract(ra + 0.5);',
      'float rmix = abs(1.0 - 2.0 * ra);',
      'float cellAlong = uMistScale * mix(uMistStretch, uMistPlumeStretch, plume);',
      'vec3 qa = vec3((c.u - uMistSpeed * ra * uMistLoop) / cellAlong, c.w / uMistScale, c.h / uMistScale);',
      'vec3 qb = vec3((c.u - uMistSpeed * rb * uMistLoop) / cellAlong + 5.7, c.w / uMistScale + 3.1, c.h / uMistScale + 8.3);',
      'return mix(fbmOct(qa, octaves), fbmOct(qb, octaves), rmix);',
    '}',

    "//The cone's envelope at a point of the curtain's frame: 0 at the hull, up to 1 on the curtain.",
    'float mistEnvelope(vec3 p, MistCoord c, float intensity){',
      'float r = max(vMistA.w, 1e-3);',
      'float x = abs(c.h) / r;',
      'float radial = x < 1.0 ? (1.0 - x * x) * (1.0 - x * x) : 0.0;',
      'radial = pow(radial, mix(1.0, 0.45, mistPlume(p)));   //a fuller body in the plume',
      'float e = max(abs(c.w) - vMistB.w, 0.0) / (0.6 * r + 1e-3);',
      'float lateral = 1.0 - smoothstep(0.0, 1.0, e);',
      "//Past the landing the mist thins out with the distance run on downstream of it (the hull's",
      '//foot is a smooth fade, not a cut at the last row, so strands that land at slightly different',
      '//rows leave no teeth).',
      'float beyond = dot(p.xz - vEnd.xz, vEndDir);',
      'float foot = 1.0 - smoothstep(0.05 * vMistB.y, max(vMistB.y, 1e-3), beyond);',
      'return radial * lateral * foot * intensity;',
    '}',

    '//d = envelope carved by the noise: thin edges break into clumps, the core stays solid.',
    'float mistDensity(vec3 p, MistCoord c, float intensity, int octaves){',
      'float env = mistEnvelope(p, c, intensity);',
      'if(env <= 0.0) return 0.0;',
      'float plume = mistPlume(p);',
      'float n = mistNoise(c, plume, octaves);',
      'float lo = (uErode + 0.35 * (1.0 - env)) * mix(1.0, 0.6, plume);',
      'return env * smoothstep(lo, lo + 0.3, n);',
    '}',

    '//Dual-lobe Henyey-Greenstein, normalised so that isotropic scattering is 1 (a Lambert surface is',
    "//INV_PI * E, so a sample's in-scatter reads in the sheet's units).",
    'float hgIso(float cosT, float g){',
      'return (1.0 - g * g) / pow(max(1.0 + g * g - 2.0 * g * cosT, 1e-4), 1.5);',
    '}',
    'float mistPhase(float cosT){',
      'return mix(hgIso(cosT, uPhaseG), hgIso(cosT, -0.25), 0.25);',
    '}',

    "//The scene's sun shadow at a world point: four taps, no derivatives (this runs in a loop).",
    'float sunShadowAt(vec3 p){',
      'if(sunShadowEnabled == 0) return 1.0;',
      'vec4 sp = sunShadowMatrix * vec4(p, 1.0);',
      'vec3 sc = sp.xyz / sp.w;',
      'if(sc.z > 1.0 || sc.z < 0.0) return 1.0;',
      'vec2 edgeDist = min(sc.xy, vec2(1.0) - sc.xy);',
      'float edge = min(edgeDist.x, edgeDist.y);',
      'if(edge < 0.0) return 1.0;',
      'float refZ = sc.z + sunShadowBias;',
      'vec2 ts = (1.0 / sunShadowMapSize) * sunShadowRadius;',
      'float s = 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2(-0.5, -0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2( 0.5, -0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2(-0.5,  0.5) * ts).r ? 1.0 : 0.0;',
      's += refZ < texture2D(sunShadowMap, sc.xy + vec2( 0.5,  0.5) * ts).r ? 1.0 : 0.0;',
      'return mix(1.0, 0.25 * s, smoothstep(0.0, 0.05, edge));',
    '}',

    'void main(){',
      'vec3 N = normalize(vN), T = normalize(vT), A = normalize(vA);',
      'vec3 camToX = vWorldPos - cameraPosition;',
      'float distX = length(camToX);',
      'vec3 rd = camToX / max(distX, 1e-4);',

      '//How far back from X to march: the chord of the cone along this ray (2r / |cos| across the',
      '//slab, capped), and never past the camera.',
      'float r = max(vMistA.w, 1e-3);',
      'float chord = min(2.0 * r / max(abs(dot(rd, N)), 0.2) * 1.25, uMaxChord);',
      'float L = min(chord, distX);',
      'int nSteps = int(clamp(uSteps, 4.0, float(MAX_STEPS)));',
      'float dt = L / float(nSteps);',
      'float jitter = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));',
      'vec3 start = vWorldPos - rd * L;',

      '//What the ground behind says: view depth of the nearest opaque thing along this pixel.',
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',
      'float gRaw = texture2D(refractionDepthTexture, screenUV).r;',
      'float sceneDepth = 1e6;',
      'if(gRaw < 1.0){',
        'vec4 gv = inverseProjectionMatrix * vec4(screenUV * 2.0 - 1.0, gRaw * 2.0 - 1.0, 1.0);',
        'sceneDepth = -gv.z / gv.w;',
      '}',

      'vec3 Lsun = -normalize(brightestDirectionalLightDirection);   //toward the sun',
      'float cosT = dot(rd, Lsun);',
      'float phase = mistPhase(cosT);',
      'vec3 sunCol = INV_PI * brightestDirectionalLight * uSunGain;',
      'vec3 ambient = skyAmbientColor * uAmbient;',

      'float intensity = smoothstep(uAerationLo, uAerationHi, vMistB.x);',
      'float camSide = sign(dot(cameraPosition - vCenter, N));',
      'if(camSide == 0.0) camSide = 1.0;',
      '//The curtain is opaque inside its own width, fading out over its last tenth.',
      'float insideSheet = 1.0 - smoothstep(0.9 * vMistB.w, 1.05 * vMistB.w, abs(vMistA.y));',

      'float Tr = 1.0;',
      'vec3 acc = vec3(0.0);',
      'float lightStep = uLightLength / max(uLightSteps, 1.0);',
      'int nLight = int(clamp(uLightSteps, 1.0, float(MAX_LIGHT_STEPS)));',
      'float depthLen = 0.0;',

      'for(int i = 0; i < MAX_STEPS; i++){',
        'if(i >= nSteps) break;',
        'float back = L - dt * (float(i) + jitter);   //metres back from X',
        'vec3 p = start + rd * (dt * (float(i) + jitter));',
        'MistCoord c = mistCoord(p, N, T, A);',
        'float dens = mistDensity(p, c, intensity, 3);',
        'if(dens <= 0.002) continue;',

        '//Occlusion: the ground behind (view depth along the ray is linear in distance), then the',
        "//curtain's far side.",
        'float viewDepth = vViewDepth * (1.0 - back / max(distX, 1e-4));',
        'float vis = clamp((sceneDepth - viewDepth) / max(uSoftRange, 1e-3), 0.0, 1.0);',
        'float sideOK = smoothstep(-0.1 * r, 0.1 * r, c.h * camSide);',
        'vis *= mix(1.0, sideOK, uSheetOcclusion * insideSheet);',
        'float sigma = uMistDensity * dens * vis;',
        'if(sigma <= 1e-4) continue;',

        '//Self-shadowing: march toward the sun through the same field (two octaves, cheaper).',
        'float tauL = 0.0;',
        'for(int k = 0; k < MAX_LIGHT_STEPS; k++){',
          'if(k >= nLight) break;',
          'vec3 q = p + Lsun * lightStep * (float(k) + 0.5 + 0.5 * jitter);',
          'tauL += uMistDensity * mistDensity(q, mistCoord(q, N, T, A), intensity, 2) * lightStep;',
        '}',
        'tauL *= uAbsorption;',
        '//Direct term plus a wider, weaker one standing in for the light that scatters round the clump',
        '//(the shaded side is not black).',
        'float sunT = (exp(-tauL) + 0.4 * exp(-0.2 * tauL)) / 1.4;',
        'vec3 scatter = uAlbedo * (sunCol * phase * sunT * sunShadowAt(p) + ambient);',

        'float stepT = exp(-sigma * dt);',
        'acc += Tr * (1.0 - stepT) * scatter;',
        'Tr *= stepT;',
        'depthLen += dt;',
        'if(Tr < 0.01) break;',
      '}',

      'float alpha = (1.0 - Tr) * uMistOpacity;',
      'if(uDebugMode == 0 && alpha < 0.003) discard;',
      'vec3 color = acc / max(1.0 - Tr, 1e-4);',
      '#if($atmospheric_perspective_enabled)',
        'if(underwaterFactor < 0.5) color = applyAtmosphericPerspective(color, vWorldPos - rd * 0.5 * L);',
      '#endif',
      'gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(color), alpha));',

      '//$DEBUG_START$',
      'if(uDebugMode == 1) gl_FragColor = vec4(vec3(1.0 - Tr), 1.0);                                   //opacity',
      'else if(uDebugMode == 2) gl_FragColor = vec4(vec3(intensity), 1.0);                             //aeration intensity',
      'else if(uDebugMode == 3) gl_FragColor = vec4(vec3(clamp(L / uMaxChord, 0.0, 1.0)), 1.0);        //chord',
      'else if(uDebugMode == 4) gl_FragColor = vec4(0.9, 0.2, 0.9, 0.35);                              //the hull',
      'else if(uDebugMode == 5) gl_FragColor = vec4(vec3(clamp(depthLen / 4.0, 0.0, 1.0)), 1.0);       //path through mist',
      'else if(uDebugMode == 7){                                                                       //the envelope AT the hull wall: must be 0 everywhere (bright = a leak)',
        'MistCoord cx = mistCoord(vWorldPos, N, T, A);',
        'gl_FragColor = vec4(vec3(mistEnvelope(vWorldPos, cx, 1.0)), 1.0);',
      '}',
      'else if(uDebugMode == 6){                                                                       //envelope factors at mid-chord: radial, lateral, foot',
        'MistCoord cm = mistCoord(vWorldPos - rd * 0.5 * L, N, T, A);',
        'float xr = abs(cm.h) / r;',
        'float er = max(abs(cm.w) - vMistB.w, 0.0) / (0.6 * r + 1e-3);',
        'float bm = dot(vWorldPos.xz - 0.5 * rd.xz * L - vEnd.xz, vEndDir);',
        'gl_FragColor = vec4(xr < 1.0 ? (1.0 - xr * xr) * (1.0 - xr * xr) : 0.0, 1.0 - smoothstep(0.0, 1.0, er), 1.0 - smoothstep(0.05 * vMistB.y, max(vMistB.y, 1e-3), bm), 1.0);',
      '}',
      '//$DEBUG_END$',

      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',
    ];
    const updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedCode = originalGLSL[i];
      updatedCode = updatedCode.replace(/\$atmospheric_perspective_enabled/g, atmosphericPerspectiveEnabled ? '1' : '0');
      if(atmosphericPerspectiveEnabled && atmosphereFunctionsGLSL && updatedCode.indexOf('//ATMOSPHERE_FUNCTIONS_INJECTION_POINT') !== -1){
        updatedCode = atmosphereFunctionsGLSL;
      }
      updatedLines.push(updatedCode);
    }
    return updatedLines.join('\n');
  },

  vertexShader: [
    'precision highp float;',

    '//Waterfall mist vertex stage. The mesh is the HULL ARestlessOcean.WaterfallMistHull builds',
    '//round the curtain: a closed, curved cone whose far side the fragment stage draws and marches',
    "//back from. Nothing is displaced here; the stage only hands the fragment stage the curtain's",
    '//own frame at this row, so every sample is measured in metres from the curtain however it',
    '//bends.',

    "attribute vec3 aCenter;      //the curtain's centre point at this row",
    'attribute vec3 aFlowTangent; //down the flow (unit)',
    'attribute vec3 aFlowAcross;  //toward +across (unit)',
    'attribute vec4 aMistA;       //s (m of path), across (m from the middle), layer (+1 / -1), radius (m)',
    'attribute vec4 aMistB;       //aeration, foot fade length (m), free-fall flag, half-width (m)',
    "attribute vec3 aMistC;       //the strand's landing point",
    'attribute vec2 aMistD;       //the horizontal direction the water runs at the landing (unit)',

    'varying vec3 vWorldPos;',
    'varying vec3 vCenter;',
    'varying vec3 vN;',
    'varying vec3 vT;',
    'varying vec3 vA;',
    'varying vec4 vMistA;',
    'varying vec4 vMistB;',
    'varying vec3 vEnd;',
    'varying vec2 vEndDir;',
    'varying float vViewDepth;',

    '#include <fog_pars_vertex>',

    'void main(){',
      'vec4 worldPos = modelMatrix * vec4(position, 1.0);',
      'vWorldPos = worldPos.xyz;',
      'vCenter = (modelMatrix * vec4(aCenter, 1.0)).xyz;',
      'vN = normal;',
      'vT = aFlowTangent;',
      'vA = aFlowAcross;',
      'vMistA = aMistA;',
      'vMistB = aMistB;',
      'vEnd = (modelMatrix * vec4(aMistC, 1.0)).xyz;',
      'vEndDir = aMistD;',
      'vec4 mvPosition = viewMatrix * worldPos;',
      'vViewDepth = -mvPosition.z;',
      '//The fog chunk reads `mvPosition` and `transformed` by those names (see waterfall-sheet-vertex.glsl).',
      '#ifdef USE_FOG',
        'vec3 transformed = position;',
      '#endif',
      '#include <fog_vertex>',
      'gl_Position = projectionMatrix * mvPosition;',
    '}',
  ].join('\n'),
};
