//This helps
//--------------------------v
//https://github.com/mrdoob/three.js/wiki/Uniforms-types
//
//Phase 6 waterfall sheet. Every uniform in the SHARED block is replaced at init by
//the flowing-water material's own uniform object (WaterfallSheetPass.init aliases
//them), so the fall is lit and coloured by exactly what the creek is. The defaults
//here only matter if the sheet is ever drawn without a flowing surface.
ARestlessOcean.Materials.Ocean.waterfallSheetMaterial = {
  uniforms: {
    //SHARED with the flowing-water material
    brightestDirectionalLight: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    brightestDirectionalLightDirection: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    skyAmbientColor: {value: new THREE.Vector3(0.3, 0.4, 0.5)},
    waterAbsorption: {value: new THREE.Vector3(0.45, 0.07, 0.02)},
    waterScattering: {value: new THREE.Vector3(0.002, 0.004, 0.009)},
    waterSurfaceY: {value: 0.0},
    specBoost: {value: 7.0},
    t: {value: 0.0},
    sunShadowMap: {value: null},
    sunShadowMatrix: {value: new THREE.Matrix4()},
    sunShadowMapSize: {value: new THREE.Vector2(2048.0, 2048.0)},
    sunShadowRadius: {value: 1.0},
    sunShadowBias: {value: 0.0},
    sunShadowEnabled: {value: 0},
    refractionLinearDepth: {value: null},
    causticMap: {value: null},
    causticIntensityMultiplier: {value: 1.0},
    waterFieldCascade0: {value: null},
    waterFieldCascadeCenter: {value: [new THREE.Vector2(), new THREE.Vector2(), new THREE.Vector2()]},
    waterFieldCascadeHalfWidth: {value: [256.0, 1024.0, 4096.0]},
    fallCorridorA: {value: Array.from({length: 24}, function(){ return new THREE.Vector4(); })},
    fallCorridorB: {value: Array.from({length: 24}, function(){ return new THREE.Vector4(); })},
    fallCorridorCount: {value: 0},
    cameraNearFar: {value: new THREE.Vector2(0.1, 7000.0)},
    ssrViewMatrix: {value: new THREE.Matrix4()},
    ssrProjectionMatrix: {value: new THREE.Matrix4()},
    ssrMaxSteps: {value: 48.0},
    blueNoiseTexture: {value: null},
    meteringSurveyTexture: {value: null},
    meteringSurveyValid: {value: 0.0},
    underwaterFactor: {value: 0.0},
    atmosphereTransmittance: {value: null},
    atmosphereMieInscattering: {value: null},
    atmosphereRayleighInscattering: {value: null},
    atmSunPosition: {value: new THREE.Vector3(0.0, 1.0, 0.0)},
    atmMoonPosition: {value: new THREE.Vector3(0.0, -1.0, 0.0)},
    atmSunHorizonFade: {value: 1.0},
    atmMoonHorizonFade: {value: 0.0},
    atmScatteringSunIntensity: {value: 1.0},
    atmScatteringMoonIntensity: {value: 0.0},
    atmMoonLightColor: {value: new THREE.Vector3(1.0, 1.0, 1.0)},
    atmCameraHeight: {value: 0.0},
    atmDistanceScale: {value: 1.0},
    refractionColorTexture: {value: null},
    gBufferNormal: {value: null},
    refractionDepthTexture: {value: null},
    inverseProjectionMatrix: {value: new THREE.Matrix4()},
    inverseViewMatrix: {value: new THREE.Matrix4()},
    screenResolution: {value: new THREE.Vector2(1920.0, 1080.0)},
    foamOpacityMap: {value: null},
    flowWaveProfile: {value: null},
    flowRippleScale: {value: 1.0},
    foamNormalMap: {value: null},

    //Scene fog. The material is fog:true, so three's refreshFogUniforms writes these
    //every frame there is a scene.fog (a-starry-sky always sets one) and throws on
    //uniforms.fogColor if they are missing. The fog chunks (a-starry-sky's, and
    //UnderwaterFogChunk's) read nothing else but uwSunDir, which broadcastSunDir fills.
    fogNear: {value: 1.0},
    fogFar: {value: 1000.0},
    fogDensity: {value: 0.00025},
    fogColor: {value: new THREE.Color()},
    uwSunDir: {value: new THREE.Vector3(0.0, -1.0, 0.0)},

    //The sheet's own
    uLumpAmp: {value: 0.3},
    uLumpScale: {value: 1.2},
    uLumpRate: {value: 3.0},
    uEdgeWobble: {value: 0.4},
    uGrainScale: {value: 2.0},
    uGrainRate: {value: 1.0},
    uVoidMax: {value: 0.5},
    uBubbleRadius: {value: 0.0015},
    uSurfaceRough: {value: 0.35},
    uSpecFalloff: {value: 120.0},
    uEdgeFray: {value: 0.3},
    uBreakup: {value: 0.6},
    uRefraction: {value: 0.05},
    uSoftRange: {value: 0.08},
    uOpacity: {value: 1.0},
    uDebugMode: {value: 0},
  },

  //Built like the water's fragment shader (water-shader-template.txt): $atmospheric_perspective_enabled
  //and $caustics_enabled are substituted, and with it on the atmosphere functions replace the injection marker line.
  //WaterfallSheetPass rebuilds it when atmospheric perspective becomes ready.
  fragmentShader: function(atmosphericPerspectiveEnabled, atmosphereFunctionsGLSL, causticsEnabled){
    const originalGLSL = [
    'precision highp float;',

    '//Waterfall sheet fragment stage (Phase 6).',
    '//',
    '//ONE WATER, NOT TWO. The creek above a lip and the pool below it are drawn by the',
    "//flowing-water material; this sheet is drawn in between. Dante's brief was that the",
    '//fall must look like the same water, only foamier. So every input that sets the',
    "//colour of water here is the SAME uniform object as the flowing material's (the pass",
    '//aliases them, it does not copy them): the Jerlov absorption/scattering, the metered',
    '//sun, the sky ambient, the scene sun shadow, and the foam grain textures. The functions',
    "//that turn them into colour are copies of the water shader's (underwaterInscatterSurface,",
    '//the ambient-built sky, the Phong sun, getSunShadow, the ACES + sRGB tail), marked where',
    '//they live so they can be kept in step.',
    '//',
    '//WHAT IS NEW IS THE WHITE. A fall is white because of the air in it, so the whitewater',
    "//is an optical model of bubbly water (see AERATED WATER in main), not the creek's",
    "//painted-on foam: the nappe's aeration sets the void fraction, the creek's foam grain",
    "//streaks it, and the lighting is Lambert-like in the same units as the creek's foam.",
    '//',
    '//THE GRAIN RIDES THE WATER. The foam textures are sampled at',
    '//  (across metres, (tau - t) * grainRate)',
    "//where tau is the parcel's time of flight at this point of the path. A parcel launched",
    '//at time t0 sits where tau = t - t0, so (tau - t) is constant along its life: the grain',
    '//is carried with the water, and because equal time steps cover more metres where the',
    '//water is faster, the grain STRETCHES down the fall exactly as the jet accelerates.',
    '//No flow map, no advection pass.',
    '//',
    "//COMPOSITING: THE CREEK'S REFRACTION, NOT AN ALPHA LAYER. The creek draws clear water as",
    '//an opaque surface that relights the terrain behind it from the refraction G-buffer and',
    '//filters it through the water column (Beer-Lambert + inscatter). The sheet does the same,',
    '//so where one hands over to the other they read as one water: an alpha-blended film',
    '//looked like bare rock over the grey scarp where the creek had looked like 40 cm of tinted',
    '//water (hero-creek-sky, 2026-09-21). The background is sampled a little off-axis along the',
    '//lumpy normal (refraction), relit exactly as the creek relights terrain, and filtered',
    '//through the water the view actually crosses: on the lead-in over the bed, the whole',
    "//column down to it; on the free fall, only the sheet's thickness (air behind). The bubbles",
    '//let slabTdir of that through. Output is opaque; alpha is kept only for the fades',
    '//(presence, frayed edges, strands, the soft contact).',
    '//',
    "//ATMOSPHERE: exactly the creek's arrangement. With atmospheric perspective on, the atmosphere",
    "//functions are injected (at the water's injection marker, by the template's builder), the",
    "//sheet reflects a-starry-sky's sky and applies AP itself, and the scene fog chunk is left out;",
    '//with it off, the scene fog chunk runs at the end of main.',

    'uniform vec3 brightestDirectionalLight;',
    'uniform vec3 brightestDirectionalLightDirection;   //from the sun TOWARD the scene',
    'uniform vec3 skyAmbientColor;',
    'uniform vec3 waterAbsorption;',
    'uniform vec3 waterScattering;',
    'uniform float waterSurfaceY;',
    'uniform float specBoost;',
    'uniform float t;',

    'uniform sampler2D sunShadowMap;',
    'uniform vec2 sunShadowMapSize;',
    'uniform float sunShadowRadius;',
    'uniform float sunShadowBias;',
    'uniform int sunShadowEnabled;',

    'uniform sampler2D refractionLinearDepth;',
    'uniform sampler2D refractionColorTexture;   //G-buffer 0: linear albedo',
    'uniform sampler2D gBufferNormal;            //G-buffer 1: world normal',
    'uniform sampler2D refractionDepthTexture;   //raw NDC depth',
    'uniform mat4 sunShadowMatrix;',
    'uniform mat4 inverseProjectionMatrix;',
    'uniform mat4 inverseViewMatrix;',
    'uniform vec2 screenResolution;',
    "//The creek's screen-space reflection (lifted from water-shader.glsl, see below) and what it reads.",
    'uniform vec2 cameraNearFar;',
    'uniform mat4 ssrViewMatrix;',
    'uniform mat4 ssrProjectionMatrix;',
    'uniform float ssrMaxSteps;',
    'uniform sampler2D blueNoiseTexture;',
    'uniform sampler2D meteringSurveyTexture;',
    'uniform float meteringSurveyValid;',
    'uniform float underwaterFactor;',
    "//The creek's seabed caustics (aliased; compiled in with $caustics_enabled, as the creek's are).",
    '#if($caustics_enabled)',
      'uniform sampler2D causticMap;',
      'uniform float causticIntensityMultiplier;',
    '#endif',
    "//The creek's own visibility rules, evaluated here so the attached ends draw exactly where it",
    "//does not (aliased from the flowing material: its WaterField cascade 0 and ring 0's corridors).",
    'uniform sampler2D waterFieldCascade0;',
    'uniform vec2 waterFieldCascadeCenter[3];',
    'uniform float waterFieldCascadeHalfWidth[3];',
    'const int FALL_CORRIDOR_MAX = 24;',
    'uniform vec4 fallCorridorA[FALL_CORRIDOR_MAX];',
    'uniform vec4 fallCorridorB[FALL_CORRIDOR_MAX];',
    'uniform int fallCorridorCount;',

    'uniform sampler2D foamOpacityMap;',
    "//The creek's ripple profile buffer (FlowSurfacePass) and its live knob: the lead-in's surface",
    "//IS the creek's, so it carries the creek's ripples.",
    'uniform sampler2D flowWaveProfile;',
    'uniform float flowRippleScale;',
    'uniform sampler2D foamNormalMap;',

    'uniform float uGrainScale;       //metres per foam tile ACROSS the sheet (the creek uses 2 m)',
    'uniform float uGrainRate;        //foam tiles per second of flight ALONG it',
    'uniform float uVoidMax;          //air void fraction at full aeration (free-falling jets: 0.1-0.5)',
    'uniform float uBubbleRadius;     //m, mean bubble radius (white water: 1-2 mm)',
    "uniform float uSurfaceRough;     //how hard the grain's normals break the jet's surface",
    'uniform float uSpecFalloff;      //Phong exponent of the sun glint on the clear lip',
    'uniform float uEdgeFray;         //how far the grain eats into the side edges (0..1 of half-width)',
    'uniform float uBreakup;          //how far an airborne, aerated jet opens into strands (0..1)',
    'uniform float uRefraction;       //how far the lumpy normal bends the view of what is behind (UV per unit normal)',
    'uniform float uSoftRange;        //metres of depth over which the sheet fades into the ground',
    'uniform float uOpacity;',
    'uniform int uDebugMode;',

    'varying vec3 vWorldPos;',
    'varying vec3 vWorldNormal;',
    'varying vec4 vFlowA;',
    'varying vec4 vFlowB;',
    'varying vec4 vSunShadowCoord;',
    'varying float vViewDepth;',
    'varying vec2 vFlowVel;',
    "varying vec3 vFlowAcrossDir;  //the trace's across direction (horizontal, unit)",
    "varying vec3 vFlowDownDir;    //the trace's downstream tangent (unit)",

    '//Fog and atmosphere exactly as water-shader.glsl declares them: the scene fog chunk only',
    "//with atmospheric perspective OFF (a-starry-sky's fog branch tone-maps AGAIN, which washed",
    "//this already tone-mapped sheet toward the terrain's orange, round 5); with it ON, the",
    '//atmosphere functions are injected here and the sheet applies AP itself, like the creek.',
    '#if(!$atmospheric_perspective_enabled)',
      '#include <fog_pars_fragment>',
    '#endif',
    '#if($atmospheric_perspective_enabled)',
      'precision highp sampler3D;',
      'uniform sampler2D atmosphereTransmittance;',
      'uniform sampler3D atmosphereMieInscattering;',
      'uniform sampler3D atmosphereRayleighInscattering;',
      'uniform vec3 atmSunPosition;',
      'uniform vec3 atmMoonPosition;',
      'uniform float atmSunHorizonFade;',
      'uniform float atmMoonHorizonFade;',
      'uniform float atmScatteringSunIntensity;',
      'uniform float atmScatteringMoonIntensity;',
      'uniform vec3 atmMoonLightColor;',
      'uniform float atmCameraHeight;',
      'uniform float atmDistanceScale;',

      '//ATMOSPHERE_FUNCTIONS_INJECTION_POINT',
    '#endif',

    '#if(!$atmospheric_perspective_enabled)',
      '//When atmospheric perspective is enabled, sRGBToLinear is provided by the',
      '//injected atmosphere functions (inside the #if block above). Otherwise we',
      '//need our own — declared here, BEFORE the SSR raymarch function that calls',
      '//it, because GLSL requires forward declarations before use.',
      'vec4 sRGBToLinear( in vec4 value ) {',
      '	return vec4( mix( pow( value.rgb * 0.9478672986 + vec3( 0.0521327014 ), vec3( 2.4 ) ), value.rgb * 0.0773993808, vec3( lessThanEqual( value.rgb, vec3( 0.04045 ) ) ) ), value.a );',
      '}',
    '#endif',

    '//(No PI of our own: the injected atmosphere functions declare one; a second is a link error.)',
    'const float INV_PI = 0.31830988618;',
    '//── Copied from water-shader.glsl (keep in step) ──────────────────────────────',
    'const float r0 = 0.02;',
    'const float UW_PI = 3.14159265359;',
    'const float UW_HG_G = 0.5;',
    'const float UW_INV_4PI = 0.07957747154;',
    'const float UW_MURK_GAZE_WEIGHT = 0.0;',

    'float fresnelAirToWater(float cosTheta){',
      'return r0 + (1.0 - r0) * pow(1.0 - cosTheta, 5.0);',
    '}',

    'float henyeyGreenstein(float cosTheta, float g){',
      'float g2 = g * g;',
      'return (1.0 - g2) * UW_INV_4PI / pow(max(1.0 + g2 - 2.0 * g * cosTheta, 1e-4), 1.5);',
    '}',

    "//water-shader.glsl underwaterInscatterSurface: the medium's single + multiple scatter",
    '//equilibrium for a view direction (camera -> fragment).',
    'vec3 underwaterInscatterSurface(vec3 viewDirWorld){',
      'vec3 extinction = waterAbsorption + waterScattering;',
      'vec3 albedo = waterScattering / max(extinction, vec3(1e-4));',
      'float sunCosZenith = max(dot(-brightestDirectionalLightDirection, vec3(0.0, 1.0, 0.0)), 0.0);',
      'float sunTransmission = 1.0 - fresnelAirToWater(sunCosZenith);',
      'vec3 directDownwelling = brightestDirectionalLight * sunTransmission * sunCosZenith;',
      'vec3 ambientDownwelling = skyAmbientColor;',
      'float cosTheta = -dot(viewDirWorld, brightestDirectionalLightDirection);',
      'float pSun = mix(UW_INV_4PI, henyeyGreenstein(cosTheta, UW_HG_G), UW_MURK_GAZE_WEIGHT);',
      'float pSky = 1.0 / (2.0 * UW_PI);',
      'vec3 singleScatter = albedo * (directDownwelling * pSun + ambientDownwelling * pSky);',
      'vec3 totalDownwelling = directDownwelling + ambientDownwelling;',
      'vec3 sqrtOneMinusA = sqrt(max(vec3(1.0) - albedo, vec3(0.0)));',
      'vec3 rInf = (vec3(1.0) - sqrtOneMinusA) / (vec3(1.0) + sqrtOneMinusA);',
      'vec3 multiScatter = rInf * totalDownwelling * (1.0 / UW_PI);',
      'float camDepth = max(0.0, waterSurfaceY - cameraPosition.y);',
      'vec3 camDepthDarken = exp(-(waterAbsorption + waterScattering) * camDepth);',
      'return (singleScatter + multiScatter) * camDepthDarken;',
    '}',

    '//water-shader.glsl computeStandaloneSkyRadiance: the sky when no provider bound one.',
    'vec3 computeStandaloneSkyRadiance(vec3 worldDir){',
      'float up = pow(clamp(worldDir.y, 0.0, 1.0), 0.55);',
      'vec3 horizon = skyAmbientColor * 0.75;',
      'vec3 zenith  = skyAmbientColor * 1.35;',
      'vec3 sky = mix(horizon, zenith, up);',
      'sky = mix(horizon, sky, smoothstep(-0.15, 0.02, worldDir.y));',
      'return sky;',
    '}',

    "//── Lifted verbatim from water-shader.glsl (keep in step): the creek's sky and AP ──────",
    '#if($atmospheric_perspective_enabled)',
      '//Compute sky radiance in a given world-space direction using the same atmosphere LUTs',
      "//as applyAtmosphericPerspective. This matches a-starry-sky's own sky rendering, so",
      '//reflection colors are continuous with the visible sky at any view direction.',
      '//Returns LINEAR radiance (same convention as the rest of the SSR path).',
      'vec3 computeSkyRadiance(vec3 worldDir){',
        '//Convert from THREE.js world coords to a-starry-sky coords (same transform as applyAtmosphericPerspective)',
        'vec3 skyDir = vec3(-worldDir.z, worldDir.y, -worldDir.x);',

        '//Clamp to horizon so reflection rays pointing slightly below horizon (off wave faces',
        '//tilted toward the viewer) snap to horizon color rather than sampling invalid LUT coords.',
        'float viewCosZenith = max(skyDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscatter. horizonFade is squared (NOT cubed) here to match the sky',
        '//dome exactly — a-starry-sky multiplies intensityFader twice in',
        '//linearAtmosphericPass. This function must track the VISIBLE sky so the',
        '//SSR sky fallback and skirt stay continuous with the dome at twilight;',
        '//fade cubed left them darker than the dome by a factor of fade.',
        '//applyAtmosphericPerspective keeps fade cubed (the fog convention).',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(skyDir, atmSunPosition);',
        'vec3 skySun = (atmSunHorizonFade * atmSunHorizonFade) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun);',

        '//Moon inscatter',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(skyDir, atmMoonPosition);',
        'vec3 skyMoon = (atmMoonHorizonFade * atmMoonHorizonFade) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon);',

        "//Base sky ambient — matches a-starry-sky's own atmosphere pass main() (not linearAtmosphericPass).",
        '//Small bluish floor that fades with altitude/horizon via the 2D transmittance LUT.',
        'vec3 transmittanceFade = texture(atmosphereTransmittance, vec2(xParam, yHeight)).rgb;',
        'vec3 baseSkyLighting = 0.25 * vec3(2E-3, 3.5E-3, 9E-3) * transmittanceFade;',

        'return skySun + skyMoon + baseSkyLighting;',
      '}',

      '//Atmospheric perspective for ground-level surfaces.',
      '//Uses distance-based extinction with LUT-sampled multi-scattered inscattering.',
      '//At the same height: S(A->B) = S(A->inf) * (1 - T(A->B))',
      'vec3 applyAtmosphericPerspective(vec3 color, vec3 worldPos){',
        'vec3 worldViewDir = normalize(worldPos - cameraPosition);',
        "//Convert view direction from THREE.js world space to a-starry-sky's coordinate",
        '//system. Sun world direction = (-sp.z, sp.y, -sp.x) from quadOffset, so the',
        '//inverse transform from world to sky coords is: skyDir = (-world.z, world.y, -world.x)',
        'vec3 viewDir = vec3(-worldViewDir.z, worldViewDir.y, -worldViewDir.x);',
        'float dist = length(worldPos - cameraPosition) * METERS_TO_KM * atmDistanceScale;',

        '//Distance-based extinction along the camera-to-surface path',
        'vec3 extinction = exp(-(RAYLEIGH_BETA + EARTH_MIE_BETA_EXTINCTION) * dist);',

        '//Attenuate surface color',
        'color *= extinction;',

        '//LUT coordinates for inscattering lookup',
        'float viewCosZenith = max(viewDir.y, 0.0);',
        'float xParam = parameterizationOfCosOfViewZenithToX(viewCosZenith);',
        'float yHeight = parameterizationOfHeightToY(RADIUS_OF_EARTH + atmCameraHeight);',

        '//Sun inscattering from 3D LUTs',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(max(atmSunPosition.y, 0.0));',
        'vec3 uv3Sun = vec3(xParam, yHeight, zSun);',
        'vec3 mieSun = texture(atmosphereMieInscattering, uv3Sun).rgb;',
        'vec3 raySun = texture(atmosphereRayleighInscattering, uv3Sun).rgb;',
        'float cosViewSun = dot(viewDir, atmSunPosition);',
        'vec3 fogSun = pow(atmSunHorizonFade, 3.0) * atmScatteringSunIntensity',
                    '* (miePhaseFunction(cosViewSun) * mieSun + rayleighPhaseFunction(cosViewSun) * raySun)',
                    '* (1.0 - extinction);',

        '//Moon inscattering from 3D LUTs',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(max(atmMoonPosition.y, 0.0));',
        'vec3 uv3Moon = vec3(xParam, yHeight, zMoon);',
        'vec3 mieMoon = texture(atmosphereMieInscattering, uv3Moon).rgb;',
        'vec3 rayMoon = texture(atmosphereRayleighInscattering, uv3Moon).rgb;',
        'float cosViewMoon = dot(viewDir, atmMoonPosition);',
        'vec3 fogMoon = pow(atmMoonHorizonFade, 3.0) * atmScatteringMoonIntensity * atmMoonLightColor',
                     '* (miePhaseFunction(cosViewMoon) * mieMoon + rayleighPhaseFunction(cosViewMoon) * rayMoon)',
                     '* (1.0 - extinction);',

        'return color + fogSun + fogMoon;',
      '}',
    '#endif',

    '//What the sheet sees of the sky where nothing is behind it (and what the SSR below falls',
    "//back to through its own lookup): the creek's sky. With atmospheric perspective ON that is",
    "//a-starry-sky's own sky through its LUTs (computeSkyRadiance). With it OFF, the water's",
    '//ambient-built sky rather than the metering-survey fisheye: that fisheye read back all zeros',
    '//on hero-creek-sky and the sheet reflected black (round 2). Rays below the horizon would see',
    '//terrain, not sky, and fade to a dim ground bounce (FUDGE 0.25) in both cases.',
    'vec3 skyRadiance(vec3 dir){',
      'vec3 upDir = vec3(dir.x, max(dir.y, 0.0), dir.z);',
      'upDir = dot(upDir, upDir) > 1e-8 ? normalize(upDir) : vec3(0.0, 1.0, 0.0);   //straight down: weight 0 below',
      '#if($atmospheric_perspective_enabled)',
        'vec3 sky = computeSkyRadiance(upDir);',
      '#else',
        'vec3 sky = computeStandaloneSkyRadiance(upDir);',
      '#endif',
      'return mix(skyAmbientColor * 0.25, sky, smoothstep(-0.3, 0.05, dir.y));',
    '}',

    "//── Lifted verbatim from water-shader.glsl (keep in step): the creek's caustic pattern ──",
    '#if($caustics_enabled)',
      'float causticShader(vec2 uv, float t){',
        '//Animation speed: t/8 — gentle ocean shimmer rather than rapids. Original',
        '//was t/20 (glacial); t/4 read as frantic. Two scrolling UVs with non-',
        '//parallel velocities create the interlock look.',
        'float tModified = (t / 8.0);',
        'vec2 uv1 = uv + vec2(0.8, 0.1) * tModified;',
        'vec2 uv2 = uv - vec2(0.2, 0.7) * tModified;',
        'float aSample1 = texture(causticMap, uv1).r;',
        'float aSample2 = texture(causticMap, uv2).g;',
        'return min(aSample1, aSample2);',
      '}',

      '//The caustic octave blend at a surface point (the loop that used to sit inline in main).',
      'vec3 causticOctaves(vec2 pxz, float downPath, float level0, float levelT, float baseUV, float dispersion){',
        'vec3 raw = vec3(0.0);',
        'for(int k = 0; k < 2; k++){',
          'float causticScale = baseUV * exp2(level0 + float(k));',
          'vec2 causticUV = causticScale * pxz;',
          'float causticSplit = causticScale * dispersion * downPath;',
          'vec3 causticOctave = vec3(causticShader(causticUV + causticSplit, t),',
                                    'causticShader(causticUV, t),',
                                    'causticShader(causticUV - causticSplit, t));',
          'raw += (k == 0 ? 1.0 - levelT : levelT) * causticOctave;',
        '}',
        'return raw;',
      '}',
    '#endif',

    "//── Lifted verbatim from water-shader.glsl (keep in step): the creek's SSR ─────────────",
    "//The lip and the lead-in are the creek's surface carried on, so they reflect the banks and",
    '//the sky the way the creek does (Dante, round 6: the top looked duller than the creek).',
    '//Screen-space reflection using the refraction color+depth buffer (already rendered',
    '//from the main camera with water hidden — zero extra render passes).',
    '//Exponential stepping covers nearby geometry detail AND distant sky.',
    '//Sky fallback: LUT-based atmosphere (when enabled) or metering survey fisheye.',
    '//Returns LINEAR radiance — caller must NOT apply sRGBToLinear to the result.',
    '//Geometry hits come from the sRGB refraction buffer and are converted here.',
    '//TWO DIRECTIONS, NOT ONE.',
    '//  marchDir — the ray the depth-buffer raymarch follows. Wants the SMOOTH normal:',
    '//             per-pixel normal jitter makes neighbouring fragments march into',
    '//             different depth footprints and the geometry reflection breaks into',
    '//             noise. This is why the SSR ray was put on macroNormal originally,',
    '//             and that reasoning still holds.',
    '//  skyDir   — the direction the sky is sampled along on a MISS. Wants the exact',
    '//             opposite: sub-metre ripple detail is the entire reason a real sea',
    '//             surface glitters rather than mirroring. Sharing one direction meant',
    '//             the sky reflection only ever tracked the long swell, which reads as',
    '//             a reflection that barely moves while the water under it ripples.',
    '//Callers that want the old single-direction behaviour pass the same vector twice.',
    'vec3 screenSpaceReflection(vec3 worldPos, vec3 marchDir, vec3 skyDir){',
      'vec3 reflectDir  = skyDir;      //every sky lookup below reads this',
      'vec3 viewPos     = (ssrViewMatrix * vec4(worldPos,    1.0)).xyz;',
      'vec3 viewReflect = normalize(mat3(ssrViewMatrix) * marchDir);',

      '//Sky fallback: use LUT-based sky radiance when atmosphere is enabled for correct horizon',
      '//colors; fall back to metering survey fisheye for the no-atmosphere build path.',
      '#if($atmospheric_perspective_enabled)',
        'vec3 skyColor = computeSkyRadiance(reflectDir);',
      '#else',
        '//A sky provider can still be present with atmospheric perspective switched',
        '//off, in which case its metering survey is the better source — it is a real',
        '//render of the real sky. Only fall back when nothing bound one.',
        'vec2 skyUV = clamp(reflectDir.xz * 0.5 + 0.5, 0.01, 0.99);',
        'vec3 skyColor = (meteringSurveyValid > 0.5)',
                      '? texture2D(meteringSurveyTexture, skyUV).rgb',
                      ': computeStandaloneSkyRadiance(reflectDir);',
      '#endif',

      '//Note: a procedural sun-disk/halo addition was attempted here to fill the',
      '//"dark hole" in computeSkyRadiance at the sun direction at sunset (the',
      '//Mie forward-scattering peak gets crushed by the horizon fade — softened',
      '//since computeSkyRadiance moved from fade^3 to the dome-matching fade^2). It',
      "//produced wrong colors when combined with the LUT's dim plum baseline.",
      "//The proper fix is to either (a) sample a-starry-sky's actual sun render",
      '//target in the SSR fallback, or (b) hide the sun mesh during the G-buffer',
      '//refraction pass and have the sky LUT include a proper sun peak.',
      '//Deferred to a follow-up session.',

      '//Reflected ray pointing behind the camera — skip march, return sky directly.',
      'if(viewReflect.z > 0.0){',
        'return skyColor;',
      '}',

      '//Exponential step: starts at 0.25m, grows 1.15x each step. Was 0.5m / 1.3x,',
      '//then 1.2x; the slower growth pulls the step size at mid-distance hits down',
      '//(at iter ~15: ~30 m/step at 1.3x → ~3.8 m at 1.2x → ~2.0 m at 1.15x), so',
      '//binary refinement starts from a tighter bracket and converges to ~cm-level',
      '//residual. The 1.15x tightening also halves the stride stripes lean on the',
      '//jitter for (see below), trading reach — full 48-step span drops from ~7.9 km',
      '//to ~1.2 km, still far past where the edge-fade kills SSR.',
      '//Per-pixel blue-noise jitter of the march phase. The exponential step',
      '//boundaries are otherwise coherent across neighboring fragments, so whether',
      '//a sample lands inside a reflected object depth footprint flips in visible',
      '//stripes — worst on flat water (wind 0), where wave normals no longer dither',
      '//the ray directions for free. Scaling the initial step by [0.75, 1.25]',
      '//decorrelates the whole exponential ladder per pixel, turning the stripes',
      '//into fine stable grain. STATIC noise (no temporalOffset): there is no TAA',
      '//pass to resolve temporal shimmer, so the pattern must not change per frame.',
      'float ssrJitter = texelFetch(blueNoiseTexture, ivec2(mod(gl_FragCoord.xy, 128.0)), 0).r;',
      'float stepLen = 0.25 * (0.75 + 0.5 * ssrJitter);',
      'vec3 curPos = viewPos;',
      'vec3 prevPos = viewPos;',

      '//48 is the hard loop ceiling (GLSL ES requires a constant bound); ssrMaxSteps',
      '//caps the live count below it. Hitting the cap with no crossing falls through',
      '//to the sky return below — identical to running out of steps naturally.',
      'for(int i = 0; i < 48; i++){',
        'if(float(i) >= ssrMaxSteps){ break; }',
        'prevPos = curPos;',
        'curPos  += viewReflect * stepLen;',
        'stepLen *= 1.15;',

        'vec4 clip = ssrProjectionMatrix * vec4(curPos, 1.0);',
        'if(clip.w <= 0.0) break;',
        'vec2 uv = clip.xy / clip.w * 0.5 + 0.5;',

        '//Ray exited screen — return sky.',
        'if(uv.x < 0.01 || uv.x > 0.99 || uv.y < 0.01 || uv.y > 0.99){',
          'return skyColor;',
        '}',

        'float sceneDepth = texture2D(refractionLinearDepth, uv).r;',
        'float rayDepth   = -curPos.z;',
        'float depthDelta = rayDepth - sceneDepth;',
        'float farThreshold = cameraNearFar.y * 0.95;',
        '//Loose crossing gate — every accepted hit gets binary-search refinement',
        '//and a silhouette check below, so thickness can be generous here.',
        'float maxThickness = stepLen + 1.0;',

        '//Note: previously gated `uv.y > 0.5`, rejecting any hit whose projected',
        '//screen position lands in the lower half. That truncated reflections of',
        '//tall geometry (like the lighthouse) to whatever bit happened to project',
        '//into the upper half — usually just the very top of the base. Removed:',
        '//the depth + silhouette checks already do the work, and "lower-half hit"',
        "//is not a meaningful rejection criterion in itself (the bounced ray's",
        '//hit position has no necessary relationship to camera screen-space halves).',
        'if(depthDelta > 0.0 && depthDelta < maxThickness &&',
           'sceneDepth > 2.0 && sceneDepth < farThreshold){',

          '//Binary-search refinement: the actual crossing lies between prevPos and',
          '//curPos. 8 iterations narrows it to ~1/256 of the last step length, so',
          '//real hits converge to sub-cm residual even when the outer step has',
          '//grown to tens of metres at the horizon. Was 5 iterations (1/32);',
          '//3 extra iterations cost 3 depth taps per accepted hit and visibly',
          '//sharpen where the reflection of an object meets the waterline.',
          '//Thickness-bug rays (ray passes behind thin geometry whose back face is',
          "//not in the depth buffer) still converge, but only to the thin object's",
          '//front face — which the silhouette check below then rejects.',
          'vec3 lo = prevPos;',
          'vec3 hi = curPos;',
          'vec2  hitUV         = uv;',
          'float hitSceneDepth = sceneDepth;',
          'float hitDelta      = depthDelta;',
          'for(int j = 0; j < 8; j++){',
            'vec3 mid = 0.5 * (lo + hi);',
            'vec4 midClip = ssrProjectionMatrix * vec4(mid, 1.0);',
            'vec2 midUV   = midClip.xy / midClip.w * 0.5 + 0.5;',
            'float midDepth = texture2D(refractionLinearDepth, midUV).r;',
            'float midDelta = -mid.z - midDepth;',
            'if(midDelta > 0.0){',
              'hi            = mid;',
              'hitUV         = midUV;',
              'hitSceneDepth = midDepth;',
              'hitDelta      = midDelta;',
            '} else {',
              'lo = mid;',
            '}',
          '}',

          '//Silhouette check: sample 4 neighbors. A thick surface — even on its',
          '//edge — has at most ONE neighbor reading far background (the side',
          '//pointing away from the object). A thin object (tree, railing, wire)',
          '//has TWO opposing neighbors reading background. Using the 2nd-largest',
          '//delta instead of the max distinguishes the two cases and stops us',
          '//from rejecting the outline of every solid object.',
          'vec2 px = vec2(0.002);',
          'float dN = abs(texture2D(refractionLinearDepth, hitUV + vec2( 0.0,  px.y)).r - hitSceneDepth);',
          'float dS = abs(texture2D(refractionLinearDepth, hitUV + vec2( 0.0, -px.y)).r - hitSceneDepth);',
          'float dE = abs(texture2D(refractionLinearDepth, hitUV + vec2( px.x, 0.0)).r - hitSceneDepth);',
          'float dW = abs(texture2D(refractionLinearDepth, hitUV + vec2(-px.x, 0.0)).r - hitSceneDepth);',
          '//Second-largest of four: max of (min-of-each-pair, min-of-the-two-maxes).',
          'float secondMax = max(max(min(dN, dS), min(dE, dW)),',
                                'min(max(dN, dS), max(dE, dW)));',
          'float silhouetteThreshold = hitSceneDepth * 0.05 + 1.0;',

          '//Soft rejection: smoothstep out as the silhouette measure grows, instead',
          '//of a hard cutoff. Hard cutoffs produce moire/striping when the refined',
          '//hitUV jitters sub-pixel across adjacent fragments.',
          'float silhouetteConfidence =',
            '1.0 - smoothstep(silhouetteThreshold * 0.6, silhouetteThreshold, secondMax);',

          '//Convergence threshold scales with step size: 5 binary halvings of a',
          '//step of length L leaves at most L/32 of residual on a real crossing,',
          '//so 0.1*stepLen + 0.5 is generous margin. A constant 0.5 rejected every',
          '//far hit because exponential stepping reaches ~100m-per-step by iter 20.',
          'float convergenceThreshold = stepLen * 0.1 + 0.5;',
          '//Soft acceptance, same reasoning as silhouetteConfidence above: a hard',
          '//hitDelta cutoff flips between accept and reject across adjacent',
          '//fragments whose refined residuals straddle the threshold, striping the',
          '//reflection. Fade out over the top half of the threshold instead.',
          'float convergenceConfidence =',
            '1.0 - smoothstep(convergenceThreshold * 0.5, convergenceThreshold, hitDelta);',
          'if(convergenceConfidence > 0.0 && silhouetteConfidence > 0.0){',
            'vec2  edgeDist = abs(hitUV * 2.0 - 1.0);',
            'float edgeFade = 1.0 - smoothstep(0.80, 1.0, max(edgeDist.x, edgeDist.y));',
            '//G-buffer attachment 0 is already LINEAR (the G-buffer fragment shader',
            '//sRGB-decodes source albedo before writing). The refraction sampling',
            '//below at the equivalent line correctly samples without a second decode',
            '//— this one used to do sRGBToLinear() here, which gamma-darkened the',
            '//reflection so lighthouse bricks read as near-black silhouettes.',
            'vec3  hitAlbedo = texture2D(refractionColorTexture, hitUV).rgb;',
            '//Apply approximate lighting at the hit point so the reflection matches',
            '//the lit appearance of the reflected geometry, not just raw albedo.',
            '//Lambertian sun diffuse (using gBufferNormal as the surface normal) +',
            "//skyAmbientColor as hemispheric fill. We don't have shadow info for",
            '//the hit point, so reflected-into-shadow regions will read slightly',
            '//overlit — acceptable trade for a cheap approximation.',
            'vec3  hitNormal = normalize(texture2D(gBufferNormal, hitUV).rgb);',
            'float hitNdotL  = max(0.0, dot(hitNormal, -brightestDirectionalLightDirection));',
            'vec3  hitLight  = brightestDirectionalLight * hitNdotL + skyAmbientColor;',
            'vec3  hitColor  = hitAlbedo * hitLight;',
            'return mix(skyColor, hitColor, edgeFade * silhouetteConfidence * convergenceConfidence);',
          '}',
          '//Rejected — keep marching; a thicker surface may lie further along the ray.',
        '}',
      '}',

      '//Max steps without hit — sky.',
      'return skyColor;',
    '}',

    '//── How visible the creek is here (water-shader.glsl, $flowing_water; keep in step) ──',
    '//The same two rules that decide where the flowing surface draws: its thin-water fade',
    '//(FLOW_FADE_MIN_M 3 cm → FLOW_FADE_FULL_M 10 cm of its level over the G-buffer ground under',
    "//the pixel) and, inside a fall's corridor, stepping aside where its level is steep",
    '//(flowFallOwn). Not mirrored: the still/flowing hand-off weight and the bank taper, which',
    "//are ~1 and ~0 in a creek at a fall. Outside the flowing surface's window: 0 (no creek).",
    '//water-shader.glsl fallCorridorWeights (keep in step): x inside a box, y the lead ramp.',
    'vec2 creekCorridorWeights(vec2 p){',
      'vec2 w = vec2(0.0);',
      'for(int i = 0; i < FALL_CORRIDOR_MAX; ++i){',
        'if(i >= fallCorridorCount) break;',
        'vec2 a = fallCorridorA[i].xy;',
        'vec2 d = fallCorridorA[i].zw - a;',
        'float len = length(d);',
        'if(len < 1e-3) continue;',
        'd /= len;',
        'vec2 q = p - a;',
        'float along = dot(q, d);',
        'float across = abs(q.x * d.y - q.y * d.x);',
        'float r = fallCorridorB[i].x;',
        'float lead = fallCorridorB[i].y;',
        'float startEdge = lead > 0.0 ? step(0.0, along) : smoothstep(-0.5, 0.0, along);',
        'float inside = startEdge * smoothstep(-0.5, 0.0, len - along)',
                     '* (1.0 - smoothstep(r - 0.5, r, across));',
        'float ramp = lead > 0.0 ? smoothstep(0.0, lead, along) : 0.0;',
        'w = max(w, vec2(inside, inside * ramp));',
      '}',
      'return w;',
    '}',
    'bool creekInWindow(vec2 xz){',
      'vec2 d = abs(xz - waterFieldCascadeCenter[0]);',
      'return max(d.x, d.y) <= 0.89 * waterFieldCascadeHalfWidth[0];',
    '}',
    'float creekLevel0(vec2 xz){',
      'vec2 uv = (xz - waterFieldCascadeCenter[0]) / (2.0 * waterFieldCascadeHalfWidth[0]) + 0.5;',
      'return texture2D(waterFieldCascade0, uv).r;',
    '}',
    "//Wet (1) or known dry (0) by the field's own flag, softened across the texel edge. RT0.a",
    "//carries the flow weight: wet texels store −w, dry texels 1 + w, still water 0. A dry texel's",
    "//LEVEL is its nearest wet texel's, which beside a fall is often the creek 3 m up: read as water,",
    '//it drew the lead-in out over the dry bank and yanked the ribbon into slivers (round 9).',
    '//Outside the flowing window there is no flag: treated as wet.',
    'float creekWetAt(vec2 xz){',
      'vec2 d = abs(xz - waterFieldCascadeCenter[0]);',
      'if(max(d.x, d.y) > 0.89 * waterFieldCascadeHalfWidth[0]) return 1.0;',
      'vec2 uv = (xz - waterFieldCascadeCenter[0]) / (2.0 * waterFieldCascadeHalfWidth[0]) + 0.5;',
      'return 1.0 - smoothstep(0.3, 0.7, texture2D(waterFieldCascade0, uv).a);',
    '}',
    'float creekVisibleAt(vec2 xz, float groundY, bool haveGround){',
      'vec2 d = abs(xz - waterFieldCascadeCenter[0]);',
      'if(max(d.x, d.y) > 0.89 * waterFieldCascadeHalfWidth[0]) return 0.0;',
      'if(creekWetAt(xz) < 0.5) return 0.0;   //the creek discards known-dry texels',
      'float level = creekLevel0(xz);',
      'float vis = haveGround ? smoothstep(0.03, 0.10, level - groundY) : 1.0;',
      'vec2 cw = creekCorridorWeights(xz);',
      'float corr = cw.x;',
      'float own = cw.y;',
      'if(corr > 0.0){',
        'const float FALL_EPS = 0.75;',
        'float fxm = creekLevel0(xz - vec2(FALL_EPS, 0.0)), fxp = creekLevel0(xz + vec2(FALL_EPS, 0.0));',
        'float fzm = creekLevel0(xz - vec2(0.0, FALL_EPS)), fzp = creekLevel0(xz + vec2(0.0, FALL_EPS));',
        'float slope = length(vec2(fxp - fxm, fzp - fzm)) / (2.0 * FALL_EPS);',
        'own = max(own, corr * smoothstep(0.176, 0.364, slope));',
      '}',
      'return vis * (1.0 - own);',
    '}',

    "//── The creek's ripples (water-shader.glsl, Phase 4 step 4), for the lead-in ─────────",
    '//Same sixteen directions of the same profile buffer, advected with the current by the same',
    '//two-phase trick. Differences, flagged: the energy is a mid value (the creek reads it from',
    '//FlowFoamPass, which this pass does not sample), and FLOW_WAVE_PERIOD is written in here',
    '//(the creek gets it substituted from FlowSurfacePass.WAVE_PERIOD; keep the two equal).',
    'const float SHEET_FLOW_WAVE_PERIOD = 8.0;',
    'float sheetHash(vec2 q){ return fract(sin(dot(q, vec2(127.1, 311.7))) * 43758.5453); }',
    'float sheetValueNoise(vec2 q){',
      'vec2 i = floor(q);',
      'vec2 f = q - i;',
      'f = f * f * (3.0 - 2.0 * f);',
      'return mix(mix(sheetHash(i), sheetHash(i + vec2(1.0, 0.0)), f.x),',
                 'mix(sheetHash(i + vec2(0.0, 1.0)), sheetHash(i + vec2(1.0, 1.0)), f.x), f.y);',
    '}',
    'vec2 creekRippleSlope(vec2 xz, vec2 vel){',
      'float speed = length(vel);',
      'float rippleSlope = max(0.05, (0.035 + 0.13 * 0.5) * smoothstep(0.05, 0.6, speed)) * flowRippleScale;',
      'const float RIPPLE_ADVECT_PERIOD = 2.0;',
      'float ra = fract(t / RIPPLE_ADVECT_PERIOD);',
      'float rb = fract(ra + 0.5);',
      'float rmix = abs(1.0 - 2.0 * ra);',
      'vec2 xa = xz - vel * ra * RIPPLE_ADVECT_PERIOD;',
      'vec2 xb = xz - vel * rb * RIPPLE_ADVECT_PERIOD + vec2(3.7, 1.9);',
      'vec2 sv = vec2(0.0);',
      'float scaleSq = 0.0;',
      'for(int d = 0; d < 16; d++){',
        'float fd = float(d);',
        'float ang = (fd + 0.5) * 0.19634954 + 0.09 * sin(fd * 2.39);',
        'vec2 dir = vec2(cos(ang), sin(ang));',
        'float stretch = 1.0 + 0.071 * fd;',
        'float off = fract(sin(fd * 12.9898) * 43758.5453);',
        'float amp = 0.3 + 0.7 * sheetValueNoise(xa * 0.21 + vec2(fd * 7.13, fd * 3.37));',
        'float sa = texture2D(flowWaveProfile, vec2(dot(xa, dir) * stretch / SHEET_FLOW_WAVE_PERIOD + off, 0.5)).g;',
        'float sb = texture2D(flowWaveProfile, vec2(dot(xb, dir) * stretch / SHEET_FLOW_WAVE_PERIOD + off, 0.5)).g;',
        'sv += dir * mix(sa, sb, rmix) * stretch * amp;',
        'scaleSq += stretch * stretch;',
      '}',
      'return sv * rippleSlope * inversesqrt(0.5 * 0.55 * scaleSq);',
    '}',

    '//water-shader.glsl getSunShadow (3x3 PCF + receiver-plane slope bias + edge fade).',
    'float getSunShadow(vec4 shadowCoord){',
      'if(sunShadowEnabled == 0) return 1.0;',
      'vec3 sc = shadowCoord.xyz / shadowCoord.w;',
      'if(sc.z > 1.0 || sc.z < 0.0) return 1.0;',
      'vec2 edgeDist = min(sc.xy, vec2(1.0) - sc.xy);',
      'float edge = min(edgeDist.x, edgeDist.y);',
      'if(edge < 0.0) return 1.0;',
      'float slopeBias = clamp(length(vec2(dFdx(sc.z), dFdy(sc.z))), 0.0, 0.01);',
      'float refZ = sc.z + sunShadowBias - slopeBias;',
      'vec2 texelSize = (1.0 / sunShadowMapSize) * sunShadowRadius;',
      'float shadow = 0.0;',
      'for(int x = -1; x <= 1; x++){',
        'for(int y = -1; y <= 1; y++){',
          'float d = texture2D(sunShadowMap, sc.xy + vec2(float(x), float(y)) * texelSize).r;',
          'shadow += refZ < d ? 1.0 : 0.0;',
        '}',
      '}',
      'shadow *= (1.0 / 9.0);',
      'return mix(1.0, shadow, smoothstep(0.0, 0.05, edge));',
    '}',

    'vec4 linearTosRGB(vec4 value){',
      'return vec4(mix(pow(value.rgb, vec3(0.41666)) * 1.055 - vec3(0.055), value.rgb * 12.92, vec3(lessThanEqual(value.rgb, vec3(0.0031308)))), value.a);',
    '}',

    '//Private name on purpose: see the ⚠ note on aroAESFilmicToneMapping in water-shader.glsl.',
    'vec3 aroAESFilmicToneMapping(vec3 color){',
      'return clamp((color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14), 0.0, 1.0);',
    '}',
    '//──────────────────────────────────────────────────────────────────────────────',

    'void main(){',
      'float tau       = vFlowA.x;',
      'float across    = vFlowA.y;',
      'float thickness = vFlowA.z;',
      'float aeration  = vFlowB.x;',
      'float presence  = vFlowB.y;',
      'float airborne  = vFlowB.z;   //the free-fall flag (WaterfallNappe.resample)',
      'float halfWidth = vFlowB.w;',
      'if(presence * uOpacity < 0.003) discard;',

      'vec3 V = normalize(cameraPosition - vWorldPos);',
      '//Double-sided: shade the face the camera sees. Turned toward the VIEWER, not by',
      "//gl_FrontFacing: the ribbon's winding is not tied to which way the nappe's normal points,",
      '//and a back-facing normal made N·V < 0, Fresnel 1, and the whole film an opaque mirror.',
      '//Both faces of a thin film are water surfaces, so either is right.',
      'vec3 N0 = normalize(vWorldNormal);',
      'float side = dot(N0, V) < 0.0 ? -1.0 : 1.0;',
      'vec3 N = side * N0;',
      'vec3 L = -brightestDirectionalLightDirection;',

      '//── Grain, carried with the water (see the header) ─────────────────────────',
      '//The time term is wrapped for float precision, and the wrap must land on a whole number of',
      '//tiles in EVERY layer or the texture jumps once per wrap. The old mod(t, 256) was whole only',
      "//for layer 1 at uGrainRate 1; layer 2's ×0.73 slid it 186.88 tiles every 256 s. A wrap of",
      '//N·100 tiles (N·73 in layer 2) is whole in both at any rate.',
      'float grainTiles = max(100.0 * floor(2.56 * uGrainRate + 0.5), 100.0);',
      'float grainPhase = mod(t * uGrainRate, grainTiles);',
      'vec2 grainUV  = vec2(across * halfWidth / uGrainScale, tau * uGrainRate - grainPhase);',
      "//Second layer rotated and rescaled, like the creek's foamTextureUV2, to break the tile.",
      'vec2 grainUV2 = vec2(grainUV.y * 0.73 + 0.31, -grainUV.x * 0.73 + 0.57);',
      'float foamMask   = 0.5 * (texture2D(foamOpacityMap, grainUV).r   + texture2D(foamOpacityMap, grainUV2).r);',
      'vec2  foamNMXZ   = 2.0 * (0.5 * (texture2D(foamNormalMap, grainUV).xy + texture2D(foamNormalMap, grainUV2).xy)) - 1.0;',

      "//The ribbon's own frame (the trace's across and downstream directions), laid into the lumpy",
      '//surface. It used to be rebuilt from the viewer-facing normal: cross(N, up) flipped with the',
      "//side the sheet was seen from, and cross(across, N) pointed UPSTREAM, so the grain's normals",
      "//and the fall's ripples mirrored as the camera crossed the sheet. Perturbations are built on",
      '//the UNflipped normal N0 and turned with it (side), as a surface seen from behind is.',
      'vec3 acrossDir = vFlowAcrossDir - N0 * dot(vFlowAcrossDir, N0);',
      'acrossDir = dot(acrossDir, acrossDir) > 1e-6 ? normalize(acrossDir) : vec3(1.0, 0.0, 0.0);',
      'vec3 flowDir = vFlowDownDir - N0 * dot(vFlowDownDir, N0) - acrossDir * dot(vFlowDownDir, acrossDir);',
      'flowDir = dot(flowDir, flowDir) > 1e-6 ? normalize(flowDir) : normalize(cross(acrossDir, N0));',

      'float sunShadow = getSunShadow(vSunShadowCoord);',

      '//TWO LAYERS, as Dante put it (round 12): WATER underneath, with its reflection, and FOAM on',
      '//top of it. They have different surfaces:',
      "//  Nw  the WATER's surface: the sheet's lumps (N) plus the creek's own ripples, on the",
      "//      lead-in in the ground frame and on the fall in the sheet's frame. Fresnel,",
      '//      reflection and the sun glint use this, and only this.',
      "//  Nf  the FOAM's surface: the grain's normal map. Only the matte foam is lit with it.",
      '//Mixing the two (the foam normals standing in for ripples) made the foam texture a field of',
      '//sharp sky glints: the scaly face.',
      "//On the FALL the ripples are keyed to the water's own space, (across m, time of flight) —",
      "//the space the lumps and the grain ride in. Sampled in world xz they were the creek's field",
      '//seen edge-on: it barely changes down a near-vertical sheet and does not travel down with the',
      '//water while the lumps under it do, so the glints read as climbing (Dante, round 12). Here',
      '//the along coordinate is τ·RIPPLE_ALONG_SPEED and the ripples are advected at that speed, so',
      "//each one rides a parcel and stretches as the jet accelerates. The lead-in keeps the creek's.",
      "const float RIPPLE_ALONG_SPEED = 3.0;   //m/s: ripple lengths are the creek's at this speed",
      'vec2 rsGround = creekRippleSlope(vWorldPos.xz, vFlowVel);',
      'vec2 rsSheet  = creekRippleSlope(vec2(across * halfWidth, tau * RIPPLE_ALONG_SPEED), vec2(0.0, RIPPLE_ALONG_SPEED));',
      'vec3 NwGround = side * normalize(N0 - vec3(rsGround.x, 0.0, rsGround.y));',
      'vec3 NwSheet  = side * normalize(N0 - acrossDir * rsSheet.x - flowDir * rsSheet.y);',
      'vec3 Nw = normalize(mix(NwGround, NwSheet, airborne));',
      'vec3 Nf = side * normalize(N0 + (acrossDir * foamNMXZ.x + flowDir * foamNMXZ.y) * uSurfaceRough);',
      'vec3 Ns = Nw;',
      'float NdotV = clamp(dot(Ns, V), 0.0, 1.0);',
      'float path = thickness / max(NdotV, 0.2);',

      '//── AERATED WATER: a slab of bubbly water ───────────────────────────────',
      '//A waterfall is white because of AIR, and very little air does it. Bubbles of radius r',
      '//at void fraction α scatter with σ = 1.5·α/r per metre (geometric cross-section πr² per',
      '//bubble, extinction efficiency 2, α/(4/3·πr³) bubbles per m³): at α = 5 % and r = 1.5 mm',
      '//that is 50 per metre, an optical depth of 5 through a 10 cm sheet. So the white is',
      "//computed, not painted on: α comes from the nappe's aeration, streaked by the creek's own",
      "//foam grain; the slab's diffuse reflectance and transmittance come from a two-stream",
      "//estimate with the bubbles' forward-peaked phase (g = 0.85, the usual value for bubbles",
      '//of this size); what is not scattered or reflected shows the scene behind.',
      "//Air only in the free fall: the attached ends are the creek carried on, and the creek's",
      '//own foam (FlowFoamPass, fed by the traced impacts) is the foam of the pool. The tail used',
      "//to carry the trace's post-impact aeration, a dense white sheet that did not match the",
      "//creek's foam and showed through it (round 8).",
      '//Squared: aeration is how far the jet is toward break-up, and a nappe stays a glassy tongue',
      '//for its first stretch (air works in from the surfaces). Linear, 10 % aeration already made',
      '//the tongue opaque white right at the lip (round 9); uVoidMax went 0.25 → 0.5 with it so',
      '//the foot is as white as before.',
      'float voidFrac = uVoidMax * aeration * aeration * airborne * mix(0.25, 1.75, foamMask);',
      'float tauB = 1.5 * voidFrac / uBubbleRadius * path;',
      'const float BUBBLE_G = 0.85;',
      'float tauR = (1.0 - BUBBLE_G) * tauB;',
      "float slabR = tauR / (2.0 + tauR);                    //diffusely reflected (toward the light's side)",
      'float slabTdir = exp(-tauB);                          //straight through, unscattered',
      'float slabTdif = max(1.0 - slabR - slabTdir, 0.0);    //diffusely transmitted',
      "//Irradiance on the camera's face and on the far face. The far face's light reaches the",
      '//camera by diffuse TRANSMISSION: a back-lit fall glows.',
      'float NdotL = dot(Nf, L);',
      'vec3 sunE = INV_PI * brightestDirectionalLight * sunShadow;',
      'vec3 frontE = sunE * max(NdotL, 0.0) + skyAmbientColor * (0.5 + 0.5 * Nf.y);',
      'vec3 backE  = sunE * max(-NdotL, 0.0) + skyAmbientColor * (0.5 - 0.5 * Nf.y);',
      '//Water absorption along the view path through the sheet; half of it applied to the',
      '//scattered light, which on average travels about half-way in before it turns round.',
      'vec3 Twater = exp(-(waterAbsorption + waterScattering) * path);',
      "//No foam-texture ALBEDO here: the creek's foam diffuse map is dark between its bubbles by",
      "//design (its opacity map hides those pixels), and multiplying a slab's light by it drew",
      '//the gaps as dark navy water. Bubbles scatter almost without loss; the grain already',
      "//modulates how much air there is (voidFrac), and the water's absorption tints it.",
      'vec3 bubbleLit = (slabR * frontE + slabTdif * backE) * mix(vec3(1.0), Twater, 0.5);',

      "//── The film's surface and its medium ─────────────────────────────────────",
      'float F = fresnelAirToWater(NdotV);',
      "//The WATER layer's reflection and glint, off the water's own surface (Nw); the march on the",
      "//smooth sheet (N), the sky on the rippled one, the creek's split (screenSpaceReflection).",
      'vec3 reflected = screenSpaceReflection(vWorldPos, reflect(-V, N), reflect(-V, Nw));',
      'vec3 R = reflect(-L, Nw);',
      'vec3 glint = brightestDirectionalLight * pow(max(0.0, dot(R, V)), uSpecFalloff) * specBoost * sunShadow;',
      'vec3 inscatter = underwaterInscatterSurface(-V);',

      "//── What is behind: the creek's refraction model (see COMPOSITING) ─────────",
      'vec2 screenUV = gl_FragCoord.xy / screenResolution;',
      "//The bend in SCREEN space: the normal's change taken into view space (a world-xz difference",
      "//turned with the camera's yaw).",
      'vec2 refrUV = clamp(screenUV + (mat3(viewMatrix) * (Ns - N)).xy * uRefraction, vec2(0.001), vec2(0.999));',
      'vec3 behind = skyRadiance(-V);        //nothing behind: the sky seen through the water',
      'float behindDist = 1000.0;',
      'float bedColumn = -1.0;',
      'for(int attempt = 0; attempt < 2; ++attempt){',
        'vec2 uv = attempt == 0 ? refrUV : screenUV;',
        'float raw = texture2D(refractionDepthTexture, uv).r;',
        'if(raw >= 1.0) break;',
        'vec4 vp = inverseProjectionMatrix * vec4(uv * 2.0 - 1.0, raw * 2.0 - 1.0, 1.0);',
        'vp /= vp.w;',
        'vec3 P = (inverseViewMatrix * vp).xyz;',
        '//A bent sample that lands on something IN FRONT of the sheet is not behind it: retry',
        '//straight through.',
        'if(dot(P - vWorldPos, -V) < 0.0) continue;   //-V points from the camera to the fragment',
        'vec3 bgN = normalize(texture2D(gBufferNormal, uv).rgb);',
        'vec3 bgAlbedo = texture2D(refractionColorTexture, uv).rgb;',
        'behindDist = distance(vWorldPos, P);',
        "//Is P under WATER, and under how much? On the lead-in the sheet IS the creek's surface, so",
        "//anything below it is. Behind the FREE FALL, only where the creek's field has water at P",
        "//(the pool at the foot), up to that water's level: the cliff face, dry banks and rocks at",
        '//the foot are below a mid-fall fragment but in air, and lit as a bed under a column the',
        '//height of the fall they drew a near-black teal curtain behind the clear tongue.',
        'float surfaceAtP = vWorldPos.y;',
        'if(airborne > 0.5){',
          'surfaceAtP = (creekInWindow(P.xz) && creekWetAt(P.xz) > 0.5) ? min(creekLevel0(P.xz), vWorldPos.y) : -1e4;',
        '}',
        'if(P.y < surfaceAtP){',
          "//UNDER the water (the creek's bed below the lead-in): lit as water-shader.glsl lights",
          '//its seabed, by the sun refracted in and filtered down the column, plus the sky tinted',
          '//by the water. The above-water formula lit it as dry ground: a bright brown band',
          '//between the creek and the fall (Dante, round 5).',
          'vec3 sunDirInWater = refract(brightestDirectionalLightDirection, vec3(0.0, 1.0, 0.0), 1.0 / 1.33);',
          'vec3 toSunInWater = -sunDirInWater;',
          'float upY = max(toSunInWater.y, 0.05);',
          'float downPath = max(0.0, surfaceAtP - P.y) / upY;',
          'float sunCosZenith = max(dot(L, vec3(0.0, 1.0, 0.0)), 0.0);',
          'vec3 ext = waterAbsorption + waterScattering;',
          'vec3 sunDown = brightestDirectionalLight * (1.0 - fresnelAirToWater(sunCosZenith)) * exp(-ext * downPath);',
          'float bedShadow = getSunShadow(sunShadowMatrix * vec4(P + toSunInWater * downPath, 1.0));',
          'vec3 waterAlbedo = waterScattering / max(ext, vec3(1e-4));',
          "//The creek's caustics on the bed, as the creek computes them (the lead-in's bed lit",
          "//plain beside the creek's shimmering one, round 9).",
          'vec3 pSurfaceHit = P + toSunInWater * downPath;',
        'vec3 causticMod = vec3(1.0);',
        '#if($caustics_enabled)',
          '//Caustic modulation around 1.0 (brief 04 sec 2): the divergence of',
          '//refracted sun rays redistributes energy across the seabed -- total',
          '//energy is conserved, so the operator is a mean-1 multiplier.',
          '//',
          '//Pivot at CAUSTIC_TEXTURE_MEAN, not 0.5: the smoothstep contrast',
          '//curve maps the raw min(R,G) tap distribution (already low-mean',
          '//from the double-min in causticShader) into a left-skewed [0,1]',
          '//sample whose empirical mean sits near 0.25. Subtracting 0.5',
          '//instead would darken most of the seabed because most pixels live',
          '//well below 0.5; subtracting 0.25 is the correct zero-mean shift',
          '//for THIS texture+contrast-curve.',
          '//',
          '//Depth-contrast fade (brief 04 sec 2 item 2): caustic ray bundles',
          '//spread out with depth, so even when total energy is conserved the',
          '//contrast of the pattern flattens. exp(-downPath / CONTRAST_DEPTH)',
          '//gives sharp caustic webs in 0-2 m water and a soft diffuse',
          '//modulation past 3 e-folds (~24 m at default 8 m e-fold).',
          '//',
          '//The whole factor still rides on sunDown (already Beer-Lambert',
          '//attenuated by downPath) so ABSOLUTE caustic brightness also fades',
          '//with depth and sunset on top of the contrast fade.',
          'const float CAUSTIC_AMP             = 3.0;',
          'const float CAUSTIC_TEXTURE_MEAN    = 0.25;',
          'const float CAUSTIC_CONTRAST_DEPTH  = 8.0;',
          '//LO/HI are solved by src/python/make-caustic-map.py so the smoothstep',
          '//output distribution over the generated 1024px linear-intensity caustic',
          '//texture matches what the original 256px asset produced with the old',
          '//0.15/0.85 pair — same seabed energy and hot-line coverage, just sharper',
          '//filaments. Regenerating the texture re-solves these; keep this pair and',
          '//the projection-pass smoothstep in ocean-grid.js in sync with the script',
          '//output. CAUSTIC_TEXTURE_MEAN stays the tuned pivot it always was.',
          'const float CAUSTIC_THRESHOLD_LO    = 0.0;',
          'const float CAUSTIC_THRESHOLD_HI    = 1.0;',
          '//UV multiplier sets caustic texture tile size. The texture itself encodes',
          '//multiple caustic structures, so the visible caustic period is texture_tile / N.',
          '//0.3 → ~3.3 m tile, ~0.5-1 m visible caustic scale (real pool shimmer).',
          '//Previous 0.02 (50 m tile) was invisible at close range; 1.0 (1 m tile) was',
          '//sub-pixel and averaged to flat. 0.3 is the sweet spot for 1 unit = 1 m world.',
          '//(0.3 is now the DEEP-water scale, CAUSTIC_BASE_UV below; shallower beds get finer',
          '//cells, by depth.)',
          '//Project the caustic texture ALONG the refracted sun ray, not straight',
          '//down. pSurfaceHit (already computed above for the seabed shadow lookup)',
          "//is where THIS seabed point's refracted sun ray pierces the surface, so",
          '//sampling the caustic pattern there parallel-projects the surface web',
          '//down sunDirInWater onto the seabed. As the sun lowers the web slides',
          '//and stretches the way real caustics do, and a steep seabed face no',
          '//longer gets a smeared top-down slice. Collapses to the old straight-',
          '//down look exactly at solar zenith (sunDirInWater vertical ⇒',
          '//pSurfaceHit.xz == pointXYZ.xz).',
          '//ONE MODEL FOR EVERY BODY (hero-creek rounds 1-2). Round 1 gave creeks their own',
          '//constants and the pond beside them kept the ocean ones, so the two textures clashed',
          '//across the hand-off. The physics says a single model covers both:',
          '//- SCALE follows DEPTH. The ripples whose rays focus at depth h have curvature about',
          '//  4 / h (a lens of index n focuses at n / (n - 1) / curvature), and at slope s a',
          '//  ripple of curvature k has wavelength 2 pi s / k, about 0.16 h at s = 0.1. So the',
          '//  cells on a bed are about 0.16 x its depth: ~10 cm under a 0.6 m creek, ~0.8 m',
          '//  under 5 m of sea, which is where the ocean tile (0.3 UV, 3.3 m, ~4 cells) was',
          '//  already tuned. Deep water is unchanged. Two fixed octave scales are blended',
          '//  rather than one scale driven by depth, because multiplying world position by a',
          '//  depth that varies across the bed would warp the pattern.',
          '//- FOCUS. Rays need depth to converge: no pattern at the waterline, sharpening over',
          '//  the first ~0.25 m (the finest ripples, a few cm, focus there).',
          '//- DISPERSION. Red and blue refract about 0.6 mm apart per metre of depth at slope',
          '//  0.1 (index 1.331 vs 1.339): invisible in a creek, millimetres in the sea.',
          'const float CAUSTIC_BASE_UV = 0.3;',
          'const float CAUSTIC_TILE_PER_DEPTH = 0.65;',
          '#if(1)',
            "//A creek's focusing ripples are decimetres to metres long; at 0.25 m the cells read as",
            "//fine static grain beside the creek's 2 m foam (Dante, round 11). Look choice, flagged.",
            'const float CAUSTIC_MIN_TILE_M = 1.0;',
          '#else',
            'const float CAUSTIC_MIN_TILE_M = 0.25;',
          '#endif',
          'const float CAUSTIC_FOCUS_M = 0.25;',
          'const float CAUSTIC_DISPERSION_PER_M = 0.0006;',
          'float causticTile = clamp(CAUSTIC_TILE_PER_DEPTH * downPath, CAUSTIC_MIN_TILE_M, 1.0 / CAUSTIC_BASE_UV);',
          'float causticLevel = log2(1.0 / (causticTile * CAUSTIC_BASE_UV));',
          'float causticLevel0 = floor(causticLevel);',
          'float causticLevelT = causticLevel - causticLevel0;',
          'vec3 causticSampleRaw;',
          '#if(1)',
            '//Flowing water: the pattern rides the current (the ripples that focus it do), by the',
            "//same two-phase advection as the creek's ripples. It sat still under a moving creek.",
            'const float CAUSTIC_ADVECT_PERIOD = 2.0;',
            'float cPhA = fract(t / CAUSTIC_ADVECT_PERIOD);',
            'float cPhB = fract(cPhA + 0.5);',
            'float cMix = abs(1.0 - 2.0 * cPhA);',
            'causticSampleRaw = mix(',
              'causticOctaves(pSurfaceHit.xz - vFlowVel * cPhA * CAUSTIC_ADVECT_PERIOD, downPath, causticLevel0, causticLevelT, CAUSTIC_BASE_UV, CAUSTIC_DISPERSION_PER_M),',
              'causticOctaves(pSurfaceHit.xz - vFlowVel * cPhB * CAUSTIC_ADVECT_PERIOD + vec2(3.7, 1.9), downPath, causticLevel0, causticLevelT, CAUSTIC_BASE_UV, CAUSTIC_DISPERSION_PER_M),',
              'cMix);',
          '#else',
            'causticSampleRaw = causticOctaves(pSurfaceHit.xz, downPath, causticLevel0, causticLevelT, CAUSTIC_BASE_UV, CAUSTIC_DISPERSION_PER_M);',
          '#endif',
          'vec3 causticSample = smoothstep(vec3(CAUSTIC_THRESHOLD_LO), vec3(CAUSTIC_THRESHOLD_HI), causticSampleRaw);',
          'float causticDepthFade = exp(-downPath / CAUSTIC_CONTRAST_DEPTH) * smoothstep(0.0, CAUSTIC_FOCUS_M, downPath);',
          'causticMod = vec3(1.0) + causticDepthFade * causticIntensityMultiplier * CAUSTIC_AMP * (causticSample - vec3(CAUSTIC_TEXTURE_MEAN));',
        '#endif',
          'behind = bgAlbedo * (INV_PI * sunDown * max(0.0, dot(bgN, toSunInWater)) * causticMod * bedShadow + skyAmbientColor * waterAlbedo);',
          "//The creek's column: vertical depth plus its grazing-path proxy (HORIZONTAL_DEPTH_SCALE).",
          'bedColumn = (surfaceAtP - P.y) + length(vWorldPos.xz - cameraPosition.xz) * 0.008;',
        '}',
        'else {',
          '//Above the water (the cliff behind a fall): lit as the creek lights terrain it sees',
          '//above its surface.',
          'float bgShadow = getSunShadow(sunShadowMatrix * vec4(P, 1.0));',
          'behind = bgAlbedo * (INV_PI * brightestDirectionalLight * max(0.0, dot(bgN, L)) * bgShadow + skyAmbientColor);',
        '}',
        'break;',
      '}',
      '//Water the view crosses to get there: the column on the lead-in, the sheet on the fall.',
      'float waterPath = mix(bedColumn >= 0.0 ? bedColumn : min(behindDist, 50.0), min(behindDist, path), airborne);',
      'vec3 Tbody = exp(-(waterAbsorption + waterScattering) * waterPath);',
      'vec3 body = behind * Tbody + inscatter * (vec3(1.0) - Tbody);',
      '//FOAM ON TOP: the bubbles cover the water layer in proportion to the light they scatter',
      '//(1 − slabTdir), and the foam is matte, so the reflection and glint show only through its',
      "//gaps. bubbleLit is already the foam's radiance times its coverage.",
      'vec3 waterLayer = F * reflected + glint + (1.0 - F) * body;',
      'vec3 color = bubbleLit + slabTdir * waterLayer;',

      '//── Shape ───────────────────────────────────────────────────────────────',
      '//Side edges fray with the grain; an airborne, aerated jet opens into strands.',
      'float edgeN = abs(across) + (foamMask - 0.5) * uEdgeFray;',
      'float edgeAlpha = 1.0 - smoothstep(0.85, 1.0, edgeN);',
      'float strands = airborne * uBreakup * smoothstep(0.5, 1.0, aeration);',
      'float strandAlpha = smoothstep(strands - 0.1, strands + 0.1, foamMask + 0.25 * (1.0 - strands));',
      '//The G-buffer ground under the undistorted pixel, from the depth attachment (24-bit)',
      '//(the half-float linear depth steps 3 cm at 50 m and 6-12 cm at 100-200 m, coarser than',
      '//uSoftRange: the soft contact stair-stepped into a hard flickering edge in the distance).',
      'float gRaw = texture2D(refractionDepthTexture, screenUV).r;',
      'bool haveG = gRaw < 1.0;',
      'vec3 gView = vec3(0.0);',
      'float gY = 0.0;',
      'if(haveG){',
        'vec4 gv = inverseProjectionMatrix * vec4(screenUV * 2.0 - 1.0, gRaw * 2.0 - 1.0, 1.0);',
        'gView = gv.xyz / gv.w;',
        'gY = (inverseViewMatrix * vec4(gView, 1.0)).y;',
      '}',
      '//Soft contact with whatever is behind (the cliff it hugs, the ground it lands on).',
      'float soft = 1.0;',
      'if(haveG) soft = clamp((-gView.z - vViewDepth) / max(uSoftRange, 1e-3), 0.0, 1.0);',

      '//THE HAND-OFF. On attached rows (the lead-in and the landing tail) the sheet is the',
      "//complement of the creek: it draws exactly as much as the creek does not, by the creek's",
      "//own rules at this pixel. A fixed-length overlap either left the creek's holes half filled",
      '//or laid a second, slightly different water over it (round 7, the interfaces still',
      '//struggled). The ground is the G-buffer ground under the undistorted pixel, as the creek reads it.',
      'float creekVis = 0.0;',
      'float creekHere = 0.0;',
      '{',
        'creekVis = creekVisibleAt(vWorldPos.xz, gY, haveG);',
        'creekHere = creekVis > 0.0 ? creekLevel0(vWorldPos.xz) : -1e4;',
      '}',
      '//Attached rows also stop where the field says dry (they are water standing on the creek).',
      'float handoff = mix((1.0 - creekVis) * creekWetAt(vWorldPos.xz), 1.0, airborne);',
      '//Where the free fall comes down into water the creek draws, it dissolves over its last',
      '//PLUNGE_BLEND metres above that surface instead of cutting a hard line through it.',
      'const float PLUNGE_BLEND = 0.35;',
      '//Wherever the creek draws AT ALL, not in proportion to how much: a partly drawn creek over',
      '//the landing let the jet show through underneath it (round 11).',
      'handoff *= mix(1.0, smoothstep(0.0, PLUNGE_BLEND, vWorldPos.y - creekHere), step(0.02, creekVis) * airborne);',
      'float outAlpha = presence * handoff * edgeAlpha * strandAlpha * soft * uOpacity;',
      '//The sheet writes depth (so the tongue at the lip hides the fall behind it, instead of the',
      '//fall painting over it in row order, round 9): a faint fragment must not. Frayed edges,',
      "//strands and the hand-off's thin complement wrote depth at 1-30 % alpha, and the plunge mist",
      '//and spray drawn after the sheet were clipped by those invisible fringes. On the FREE FALL',
      "//only: the attached rows' alpha is the complement of the creek's visibility and must reach",
      '//zero smoothly, or a see-through band opens where the creek draws 80-99 %. LOOK KNOB:',
      '//raising it trims faint fringe off the fall; lowering it brings the clipping back.',
      'const float DEPTH_ALPHA_MIN = 0.2;',
      'if(uDebugMode == 0 && outAlpha < mix(0.004, DEPTH_ALPHA_MIN, step(0.5, airborne))) discard;',
      '#if($atmospheric_perspective_enabled)',
        '//Aerial perspective, as the creek applies it (above water only).',
        'if(underwaterFactor < 0.5) color = applyAtmosphericPerspective(color, vWorldPos);',
      '#endif',
      'gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(color), outAlpha));',

      '//$DEBUG_START$',
      'if(uDebugMode == 1) gl_FragColor = vec4(vec3(presence), 1.0);',
      'else if(uDebugMode == 2) gl_FragColor = vec4(vec3(aeration), 1.0);',
      'else if(uDebugMode == 3) gl_FragColor = vec4(airborne, 0.0, 1.0 - airborne, 1.0);   //the free-fall flag',
      'else if(uDebugMode == 4) gl_FragColor = vec4(vec3(clamp(thickness / 0.5, 0.0, 1.0)), 1.0);',
      'else if(uDebugMode == 5) gl_FragColor = vec4(vec3(1.0 - exp(-0.1 * tauB)), 1.0);',
      'else if(uDebugMode == 6) gl_FragColor = vec4(fract(grainUV), 0.0, 1.0);',
      'else if(uDebugMode == 7) gl_FragColor = vec4(vec3(outAlpha), 1.0);',
      'else if(uDebugMode == 8) gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(bubbleLit), 1.0));',
      'else if(uDebugMode == 9) gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(reflected), 1.0));',
      'else if(uDebugMode == 10) gl_FragColor = vec4(vec3(dot(Tbody, vec3(1.0 / 3.0))), 1.0);',
      'else if(uDebugMode == 11) gl_FragColor = linearTosRGB(vec4(aroAESFilmicToneMapping(body), 1.0));',
      'else if(uDebugMode == 12) gl_FragColor = vec4(creekVis, handoff, 0.0, 1.0);',
      '//$DEBUG_END$',

      "//The scene fog chunk only when atmospheric perspective is OFF — the water's own rule",
      "//(water-shader.glsl). With a-starry-sky's AP on, its fog chunk takes the fragment back to",
      '//linear, adds aerial perspective and tone-maps it AGAIN: right for terrain, which outputs',
      '//linear, but on this already tone-mapped sheet it washed the colour out toward the',
      "//terrain's orange, and the lead-in read as ground next to the creek (round 5).",
      '#if(!$atmospheric_perspective_enabled)',
        '#include <fog_fragment>',
      '#endif',
    '}',
    ];
    const updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedCode = originalGLSL[i];
      updatedCode = updatedCode.replace(/\$atmospheric_perspective_enabled/g, atmosphericPerspectiveEnabled ? '1' : '0');
      updatedCode = updatedCode.replace(/\$caustics_enabled/g, causticsEnabled ? '1' : '0');
      if(atmosphericPerspectiveEnabled && atmosphereFunctionsGLSL && updatedCode.indexOf('//ATMOSPHERE_FUNCTIONS_INJECTION_POINT') !== -1){
        updatedCode = atmosphereFunctionsGLSL;
      }
      updatedLines.push(updatedCode);
    }
    return updatedLines.join('\n');
  },

  vertexShader: [
    'precision highp float;',

    '//Waterfall sheet vertex stage (Phase 6). The ribbon is built on the CPU by',
    '//ARestlessOcean.WaterfallNappe.buildRibbon in WORLD space and the mesh sits at the',
    '//origin: a smooth, rigid-across sheet along the traced path of the free fall.',
    '//',
    '//THE SHAPE IS HERE. A real falling sheet is not a ribbon: it carries lumps and ridges',
    '//that travel down with the water, grow as it breaks up, and fray at the sides. So each',
    "//vertex is pushed along the sheet's normal by value noise sampled in the same",
    "//(across metres, time of flight) space as the fragment stage's grain, which makes the",
    '//lumps ride the water and stretch as the jet accelerates, exactly as the grain does.',
    "//Their height grows with the nappe's aeration (a glassy lip is smooth; a broken jet is",
    '//not). The side columns are also pushed in and out across the flow, so the edges are',
    '//ragged in geometry rather than a straight cut. The normal is rebuilt from the displaced',
    "//surface by finite differences of the same noise, in the ribbon's own frame.",
    '//FUDGE: the noise is a look choice (two octaves of value noise), not a jet instability',
    '//model; uLumpAmp/uLumpScale/uLumpRate/uEdgeWobble are its knobs.',

    'attribute vec4 aFlowA;       //tau (s of flight since the trace began), across (-1..1), thickness (m), speed (m/s)',
    "attribute vec4 aFlowB;       //aeration (0..1), presence (0..1), free-fall flag (0..1), this side's half-width (m)",
    'attribute float aFlowLump;   //lump weight: 1 inside a fall, ramping to 0 inside its ends (WaterfallNappe.resample)',
    'attribute vec3 aFlowTangent; //down the flow (unit)',
    'attribute vec3 aFlowAcross;  //horizontal, toward +across (unit)',

    'uniform mat4 sunShadowMatrix;',
    'uniform float t;',
    'uniform float uLumpAmp;      //m of lump at full aeration',
    'uniform float uLumpScale;    //m across per lump',
    'uniform float uLumpRate;     //lumps per second of flight along the fall',
    'uniform float uEdgeWobble;   //m the side edges wander in and out',
    "//The creek's WaterField, cascade 0 (the texture the flowing surface stands on; aliased).",
    'uniform sampler2D waterFieldCascade0;',
    'uniform vec2 waterFieldCascadeCenter[3];',
    'uniform float waterFieldCascadeHalfWidth[3];',

    'varying vec3 vWorldPos;',
    'varying vec3 vWorldNormal;',
    'varying vec4 vFlowA;',
    'varying vec4 vFlowB;',
    'varying vec4 vSunShadowCoord;',
    'varying float vViewDepth;',
    "varying vec2 vFlowVel;       //plan velocity (m/s), for the creek's ripple advection on the lead-in",
    "varying vec3 vFlowAcrossDir; //the ribbon's frame for the fragment stage (not the viewer-flipped normal)",
    'varying vec3 vFlowDownDir;',

    '#include <fog_pars_vertex>',

    "//The creek's level at xz (cascade 0), or `fallback` outside the flowing surface's window",
    "//(FlowSurfacePass draws within ~0.89 of cascade 0's half-width).",
    'float creekLevelAt(vec2 xz, float fallback){',
      'vec2 d = abs(xz - waterFieldCascadeCenter[0]);',
      'if(max(d.x, d.y) > 0.89 * waterFieldCascadeHalfWidth[0]) return fallback;',
      'vec2 uv = (xz - waterFieldCascadeCenter[0]) / (2.0 * waterFieldCascadeHalfWidth[0]) + 0.5;',
      'vec4 f = texture2D(waterFieldCascade0, uv);',
      "//Known-dry texels (RT0.a ≥ 1 there) hold their nearest wet texel's level — beside a fall",
      "//often the creek 3 m up, which yanked the ribbon's bank-side vertices into slivers (round 9).",
      'return f.a > 0.5 ? fallback : f.r;',
    '}',

    '//Value noise PERIODIC along y with period `per` cells (a whole number): the time term below',
    '//is wrapped, and noise that does not repeat at the wrap jumped every lump on the sheet at once.',
    'float wfHash(vec2 p){ return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }',
    'float wfNoise(vec2 p, float per){',
      'vec2 i = floor(p);',
      'vec2 f = p - i;',
      'f = f * f * (3.0 - 2.0 * f);',
      'float y0 = mod(i.y, per), y1 = mod(i.y + 1.0, per);',
      'return mix(mix(wfHash(vec2(i.x, y0)), wfHash(vec2(i.x + 1.0, y0)), f.x),',
                 'mix(wfHash(vec2(i.x, y1)), wfHash(vec2(i.x + 1.0, y1)), f.x), f.y);',
    '}',
    '//Two octaves, zero-mean, roughly -0.5..0.5. The second octave is exactly ×2 (was 2.03) so it',
    '//repeats too.',
    'float wfLump(vec2 p, float per){',
      'return 0.67 * wfNoise(p, per) + 0.33 * wfNoise(p * 2.0 + vec2(17.1, 5.3), 2.0 * per) - 0.5;',
    '}',

    'void main(){',
      'float acrossM = aFlowA.y * aFlowB.w;',
      'float tau = aFlowA.x;',
      'float speed = max(aFlowA.w, 0.5);',
      'float aeration = aFlowB.x;',
      '//The time term, wrapped for float precision on a whole number of lump cells that is also',
      "//whole in the edge wobble's ×1.7 (a multiple of 10), with the noise periodic at that count.",
      'float lumpCells = max(10.0 * floor(25.6 * uLumpRate + 0.5), 10.0);',
      'float lumpPhase = mod(t * uLumpRate, lumpCells);',
      "//Lumps on the free fall only: the attached ends are the creek's surface carried on, and",
      '//the landing tail (the most aerated rows) poked white lumps up through the pool.',
      'float amp = uLumpAmp * (0.15 + 0.85 * aeration) * aFlowLump;',

      'vec3 N = normalize(normal);',
      'vec3 T = normalize(aFlowTangent);',
      'vec3 A = normalize(aFlowAcross);',

      '//Displacement along the normal, and its derivatives across (per metre) and along (per',
      '//second of flight) for the rebuilt normal.',
      'const float DU = 0.2;   //m',
      'const float DT = 0.04;  //s',
      'vec2 q  = vec2(acrossM / uLumpScale, tau * uLumpRate - lumpPhase);',
      'float d0 = amp * wfLump(q, lumpCells);',
      'float du = amp * wfLump(q + vec2(DU / uLumpScale, 0.0), lumpCells);',
      'float dv = amp * wfLump(q + vec2(0.0, DT * uLumpRate), lumpCells);',
      'vec3 dPdu = A + N * ((du - d0) / DU);',
      'vec3 dPdt = T * speed + N * ((dv - d0) / DT);',
      'vec3 Nd = normalize(cross(dPdt, dPdu));',
      'Nd *= sign(dot(Nd, N) + 1e-6);',

      '//Ragged sides: the outer columns wander in and out across the flow.',
      'float edge = smoothstep(0.6, 1.0, abs(aFlowA.y));',
      '//Free fall only (aFlowLump), like the lumps: on the attached tail the edge columns swung',
      '//40 cm sideways over the banks and stuck out as flags at both ends of the foot (round 10).',
      'float wobble = uEdgeWobble * edge * (wfLump(q * vec2(0.6, 1.7) + vec2(41.7, 3.1), 1.7 * lumpCells) * 2.0) * (0.3 + 0.7 * aeration) * aFlowLump;',

      'vec3 displaced = position + N * d0 + A * sign(aFlowA.y) * wobble;',
      '//ATTACHED rows stand on the creek: at its level where it has one above the traced height',
      '//(so the two surfaces coincide wherever the creek draws, and the creek, polygon-offset',
      "//toward the camera, wins), at the trace's height where the creek's interpolated level",
      "//sinks under the brink. At the landing that is the pool's real level: rigid at the trace's",
      '//height, the tail ran under the pool and under the banks at its edges (round 7).',
      "//The creek's level as a MINIMUM: near the foot the field's cells still hold the ramp's",
      "//level (2.4 m at hero-creek's z 766 against a 1.9 m tail), and a plain sample yanked single",
      '//vertices half a metre up, folding the tail into edge-on strips.',
      'vec2 fd = aFlowTangent.xz;',
      'fd = dot(fd, fd) > 1e-6 ? normalize(fd) * 0.75 : vec2(0.0);',
      '//The level HERE, dropping to the downstream sample only where the level falls steeply',
      '//ahead (the ramp). The plain minimum sat the tail a few cm under a pool whose level eases',
      '//down downstream, so the creek covered it where it draws and it showed where the creek',
      '//fades: foam "right underneath the water" (round 10).',
      'float lvHere = creekLevelAt(displaced.xz, displaced.y);',
      'float lvDown = creekLevelAt(displaced.xz + fd, displaced.y);',
      'float creekY = mix(lvHere, min(lvHere, lvDown), smoothstep(0.1, 0.25, lvHere - lvDown));',
      '//...and ATTACHED_LIFT above it. The sheet draws ON TOP of the creek and its fragment alpha',
      "//is the complement of the creek's visibility there, so the two blend instead of stacking.",
      '//Coincident with the creek it lost the depth test to it (the creek is polygon-offset toward',
      '//the camera and writes depth even where it has faded to nearly nothing), which left a hole',
      '//at the foot: a faint creek in front of a hidden tail (round 7).',
      'const float ATTACHED_LIFT = 0.03;',
      'displaced.y = mix(max(creekY, displaced.y) + ATTACHED_LIFT, displaced.y, aFlowB.z);',
      'vec4 worldPos = modelMatrix * vec4(displaced, 1.0);',
      'vWorldPos = worldPos.xyz;',
      'vWorldNormal = normalize(mat3(modelMatrix) * Nd);',
      'vFlowA = aFlowA;',
      'vFlowB = aFlowB;',
      "//PLAN velocity: the unit tangent's xz part times the speed. normalize(planT) × speed took",
      "//the full 3D speed as horizontal and over-advected the lead-in's ripples on steep rows.",
      'vFlowVel = aFlowTangent.xz * aFlowA.w;',
      'vFlowAcrossDir = normalize(aFlowAcross);',
      'vFlowDownDir = normalize(aFlowTangent);',
      'vSunShadowCoord = sunShadowMatrix * worldPos;',
      'vec4 mvPosition = viewMatrix * worldPos;',
      'vViewDepth = -mvPosition.z;',
      "//The fog chunk (UnderwaterFogChunk, or a-starry-sky's) reads `mvPosition` and",
      '//`transformed` by those names — see the same note in water-vertex.glsl.',
      '#ifdef USE_FOG',
        'vec3 transformed = displaced;',
      '#endif',
      '#include <fog_vertex>',
      'gl_Position = projectionMatrix * mvPosition;',
    '}',
  ].join('\n'),
};
